### ISSUE TITLE
Edge case leads to "Not found" error on user's repository

### ISSUE THREAD

**Issue by bcoe** [googleapis/release-please#1014]
There's an edge-case cropping up on @abeMedia's repository that leads to `getFileContentsWithSimpleAPI` returning a 404, whereas using the data API is successful.

To be able to address this issue, we need to figure out a reproduction with @abeMedia (so far I have been unable to do so on a personal private GitHub repository).

Refs: https://github.com/googleapis/release-please/pull/982

**Comment by chingor13** [comment]
The `getFileContentsWithSimpleAPI` call uses an  API endpoint that returns different things based on what the target is (simple file vs directory vs a symlink). It's possible the file being looked up is a symlink.

**Comment by bcoe** [comment]
@abeMedia can you confirm whether you were using symlinks in the repository that was having issues?

**Comment by bcoe** [comment]
@abeMedia is it still a problem you are running into today, there have been quite a few changes to the library since August.

**Comment by abeMedia** [comment]
I'll test this weekend

**Comment by tmatsuo** [comment]
@bcoe  This issue is out of SLO now.

**Comment by bcoe** [comment]
@abeMedia closing for now, but let us know if you have a reproduction we can dig into?

**Comment by patoncrispy** [comment]
Hey @bcoe, I was actually trying to create a repro for something else, but this I'm getting this and I'm not sure why. My repo is public, though it was working before I switched to the manifest configuration. https://github.com/patoncrispy/release-please-repro/runs/7319142817?check_suite_focus=true

**Comment by patoncrispy** [comment]
You can see I haven't changed much in this diff: https://github.com/patoncrispy/release-please-repro/commit/c8802f93cb3aa838f791ac790ec5a258f606ded3
