### ISSUE TITLE
release-pr adds too many commits to the changelog when using merge commits for release PRs

### ISSUE THREAD

**Issue by creste** [googleapis/release-please#1016]
First, thank you for the great library!

#### Environment details

  - OS: Windows 10 19043.110
  - Node.js version: v14.15.4
  - npm version: 7.20.0
  - `release-please` version: 11.19.0

#### Steps to reproduce

  1. Create a monorepo with multiple packages in their own subdirectories: `pkgA/` and `pkgB/`
  2. In the GitHub repository's settings, make sure the Merge button allows merge commits
  2. Commit a "bug" code change to `pkgA/`
  4. Create a release-pr for `pkgA`:
```bash
release-please release-pr --repo-url=... --token=... --path=pkgA/ --package-name=pkgA --release-type=... --monorepo-tags=true
```
  5. Merge the release PR for pkgA using a **merge commit**.  This bug can only be reproduced when using a merge commit for the release PR.  If you use a rebase merge or a squash merge then you won't be able to reproduce the bug.
  6. Run `release-please github-release ...` to release the new version of `pkgA/`
  6. Commit another "bug" code change to `pkgA/`
  7. Create another release PR for `pkgA/` using `release-please release-pr ...`
  8. Look at the CHANGELOG in the release PR.  Notice the commits listed in the first release PR and also included in the second release PR, even though those commits were already released.

Here is an example of the first release PR showing a commit: https://github.com/creste/release-please-csharp/pull/4/files#diff-372463a7b9b02f6ff0089e816025cf05db1a851fec7a8cd1e706787d09100b48R8
Here is an example of the second release PR showing the same commit again: https://github.com/creste/release-please-csharp/pull/6/files#diff-2968a3d223a76e1279d0428fb1bfba2818416646b18b1fd1802891cdffa6ca60R8

I expected the second PR's CHANGELOG to not include commits that were already included in the first PR's CHANGELOG.

Note that this may also be reproducible without using `--path=...`.  I only tested on a monorepo with multiple packages.

#### Workaround

A workaround is to never use merge commits when merging release PRs into the default branch.

#### Investigation

Assume the steps above create a git history similar to this:
```
|
D - second bug fix in pkgA
|
C - merge commit for first release PR, and tag for first release
|\
|  B - commit in first release PR that includes changes to CHANGELOG, etc.
|/
A - first bug fix in pkgA
|
```

I think the root cause of this bug is due to `commitsSinceSha` expecting `commitsWithFiles`/`commitsWithLabels` to return a commit history that looks like "D <- C <- A", but those methods actually return a commit history that looks like "D <- B <- A".  This is important because `commitsSinceSha` uses commit C as its terminating condition because releases are always tagged at commit C instead of commit B.  Without commit C in the history, `commitsSinceSha` continues past commit C and includes commit A even though A occurred before C and B.

Another way to phrase it is `commitsSinceSha` expects to loop over the commit history shown by `git log` but it actually loops over the commit history shown by `git log --no-merges`.

The `commitsWIthFiles`/`commitsWithLabels` methods rely on GitHub's GraphQL API to get the commit history.  As far as I can tell, that API always return commits without merges and there's no way to modify that behavior.

#### Potential Fixes

**Possibility 1**

One potential fix is to modify [`graphqlToCommit`](https://github.com/googleapis/release-please/blob/72c2191ecdc369444c842ff96cbb2edb7230b261/src/graphql-to-commits.ts#L105-L152) to include commit C's SHA as an additional property on commit B, then modify [`commitsSinceSha`](https://github.com/googleapis/release-please/blob/master/src/github.ts#L399-L429) to check commit B's SHA _and_ commit C's SHA as a terminating condition.  For example, in this code:

https://github.com/googleapis/release-please/blob/72c2191ecdc369444c842ff96cbb2edb7230b261/src/graphql-to-commits.ts#L110-L123

If `prEdge` exists then a new field on the Commit object, e.g. `commit.mergeSha`, could be set to `prEdge.node.mergeCommit.oid`.  Then in `commitsSinceSha` the terminating condition at 

https://github.com/googleapis/release-please/blob/e365b169b83baba23d99494f519641f9647c03f4/src/github.ts#L417-L418

could be changed to:
```typescript
if (commit.sha === sha || commit.mergeSha === sha) {
```

**Possibility 2**

A different potential fix is instead of using `commitsSinceSha`, it may be possible to use `commitsSinceShaRest` because the REST API appears to return merge commits (e.g. D <- C <- A) as part of the linear history of a branch.  Thus, this terminating condition would find commit C and break out of the loop:
https://github.com/googleapis/release-please/blob/e365b169b83baba23d99494f519641f9647c03f4/src/github.ts#L329-L339

#### Miscellaneous

**Rust Releaser**
While investigating this issue I noticed the rust releaser has a comment documenting a similar problem:

https://github.com/googleapis/release-please/blob/e365b169b83baba23d99494f519641f9647c03f4/src/releasers/rust.ts#L121-L124

I'm not sure if this is truly a problem with using "--path" or with using merge commits, or both.  After looking at how the rust releaser solved the "--path" problem it's possible that fix may also work for the merge commit problem.  However, if this problem affects all releasers then the fix should probably be moved to `ReleasePR.commits()` instead of being re-implemented in every releaser.

**`observedSHAs` is not used**

I also noticed that `observedSHAs` is never used anywhere.  See this code:
https://github.com/googleapis/release-please/blob/e365b169b83baba23d99494f519641f9647c03f4/src/graphql-to-commits.ts#L86-L90

I'm not sure if that was intentional.  I did notice several commits that tried to fix problems with merge commits.  Please see these commits:
  * https://github.com/googleapis/release-please/commit/8f89e74e5f32d78e027f949ab1e6cbab32187a4e
  * https://github.com/googleapis/release-please/commit/e01cf0514a35427d7f87ebb39f02746da2529f35#diff-9d39e4480d5c37ac3d9572e25c3f5d713b58a7e2198ba4cc25c392c2b59ee00b

The description of https://github.com/googleapis/release-please/pull/452 seems to indicate that `prEdge.node.mergeCommit.oid` should reference a SHA seen earlier in the list.  That is not the behavior I'm seeing when querying GitHub's GraphQL API.  For example, I see the following node for the merge commit:

```json
              {
                "node": {
                  "message": "chore: release Creste.MultiProject.MultiVersion.Lib 1.0.0",
                  "oid": "f8ea75eced85b52c2336a4222dad6cce6e4a30ae",
                  "associatedPullRequests": {
                    "edges": [
                      {
                        "node": {
                          "number": 4,
                          "mergeCommit": {
                            "oid": "2fcd9bd52259ad076087b784942726b3212e2e05"
                          },
                          "files": {
                            "edges": [
                              {
                                "node": {
                                  "path": "src/Creste.MultiProject.MultiVersion/Creste.MultiProject.MultiVersion.Lib/CHANGELOG.md"
                                }
                              }
                            ],
                            "pageInfo": {
                              "endCursor": "MQ",
                              "hasNextPage": false
                            }
                          }
                        }
                      }
                    ]
                  }
                }
              },
```
I don't see "2fcd9bd52259ad076087b784942726b3212e2e05" referenced anywhere else in the commit history.  Therefore, I'm not sure the changes made in that PR ever worked.

**Comment by bcoe** [comment]
@creste thank you for the thorough bug report.

If I'm understanding correctly, merge commits work well in general, but an issue crops up specifically when merging the release PR? That's an interesting one.

I wonder if we could figure out a workaround to detect this specific edge-case, rather than modifying the underlying query -- getting the right working set of commits using the GitHub API has been quite finicky, so the less we can change the existing queries the better.

**Comment by bcoe** [comment]
@creste would you be able to try the latest release of `release-please`, @chingor13 undertook a fairly major rewrite of the library -- the bug might still crop up, but would be worth checking if it happens to have been corrected.

**Comment by ChipWolf** [comment]
I'm now seeing this issue, but with squash/rebase

**Comment by bcoe** [comment]
@ChipWolf would you be able to provide an example of a repository that is bumping into this issue?

**Comment by ChipWolf** [comment]
> @ChipWolf would you be able to provide an example of a repository that is bumping into this issue?

It's private but I've invited you

**Comment by bcoe** [comment]
@ChipWolf thank you, I'm not sure when I will be able to take a look, but will try to prioritize soon.

**Comment by ChipWolf** [comment]
> @ChipWolf thank you, I'm not sure when I will be able to take a look, but will try to prioritize soon.

@chingor13 solved this for us @bcoe https://github.com/googleapis/release-please/issues/1263#issuecomment-1027349384, pulled your access

**Comment by bcoe** [comment]
@creste sounds like the newer version of release-please might address the issues you were bumping into, let us know if you're still having problems.
