### ISSUE TITLE
Do not change modes of existing files

### ISSUE THREAD

**Issue by scop** [googleapis/release-please#1027]
release-please appears to not only create files with, but also change modes of existing files to mode [644](https://github.com/googleapis/release-please/blob/fd724c2a13947fb07de53fd9a9f9798b3b69ee22/src/github.ts#L1401) unconditionally.

This can actually cause breakage -- for example for python projects, `setup.py`, `projectname/__init__.py` and `version.py` found in the tree can be intentionally executable, and making them 644 will break that.

It's fine to create new ones with 644 (although honoring umask would be appropriate as a general practice, haven't checked if it's honored/not), but I suggest making it so that existing files' modes are not changed.

**Comment by chingor13** [comment]
Looking into this and it's less trivial to fix than I'd like. The create tree API does require file mode. However, the get file contents API does not return file contents. The git data API does return the file mode, but you have to recursively fetch directories to get to the file mode (via git tree API). If we switch exclusively to the data API, we'll likely need to write some kind of read-through cache to prevent an excessive amount of API calls.

**Comment by chingor13** [comment]
The GraphQL API can also fetch some file modes but it's not very efficient (limited to a directory at a time). Example query:
```
{
  repository(name: "java-asset", owner: "googleapis") {
    object(expression: "main:.github/workflows") {
      ... on Tree {
        id
        entries {
          mode
          name
        }
      }
    }
  }
}
```
