### ISSUE TITLE
Add option to specify "release-commit-message-pattern"

### ISSUE THREAD

**Issue by TimoGlastra** [googleapis/release-please#1031]
Currently, the `--pull-request-title-pattern` option allows to specify a pattern for the pull request title. This message is also used for the commit message. 

This may be a very specific use case, but under the Hyperledger GitHub org all commits are required to be signed off (https://developercertificate.org/). This is easily done by appending a specific line to the commit message. I've tried to do this with the `--pull-request-title-pattern`, but obviously this also changes the title of the PR (See [this PR](https://github.com/hyperledger/aries-framework-javascript-ext/pull/6) for an example).

The solution for me would be to be able to specify a separate commit message pattern so I don't have to modify the PR title pattern (something like `release-commit-message-pattern`).

Will PRs for this feature be accepted? A less generic approach would be to add a `signoff` option to this library that will specfically handle adding a `Signed-off-by` to the commit message (e.g. as is done in the [create-pull-request action](https://github.com/marketplace/actions/create-pull-request)).

**Comment by bcoe** [comment]
@TimoGlastra my preference would be for the `signoff` functionality, since it's already been proven out in the `create-pull-request-action`.

Would happily take a PR for this.

**Comment by TimoGlastra** [comment]
Cool, I've created a PR that adds the `--signoff` option. Let me know what you think
