### ISSUE TITLE
The optional release-type input for GitHub action

### ISSUE THREAD

**Issue by alexey-igrychev** [googleapis/release-please#1040]
We want to use this action not only for [supported release types](https://github.com/googleapis/release-please#release-types-supported) but also for arbitrary ones without bumping version in any project files (for instance, for projects written in Go). 

At the moment, using release type `simple` is the only available option. It seems to me that making the field optional or adding a new type (e.g. `none`) won't cost you anything and will save users from an unnecessary `version.txt` file in a project.

**Comment by ilya-lesikov** [comment]
We stumbled upon `go` release type which does exactly that. It wasn't mentioned in release-please-action, this should fix it: https://github.com/google-github-actions/release-please-action/pull/367

I guess this issue can be closed unless we still want something more generic.

**Comment by bcoe** [comment]
@alexey-igrychev does the `go` releaser work for your purposes?
