### ISSUE TITLE
`--bump-minor-for-patch-pre-major` not working (due to a wrong option name)

### ISSUE THREAD

**Issue by ilya-lesikov** [googleapis/release-please#1049]
#### Environment details

  - OS: Linux 5.11.0-27-generic #29~20.04.1-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux
  - Node.js version: v12.16.3
  - npm version: 6.14.4
  - `release-please` version: 11.24.0

#### Steps to reproduce

1. Push commit with message "feat: xxx" to your repo. Last released version in repo should be <1.0.0.
2. Make a new release PR with option `--bump-minor-for-patch-pre-major`:
```yaml
release-please release-pr --repo-url=ilya-lesikov/test --token=XXX --release-type simple --bump-minor-pre-major --bump-minor-for-patch-pre-major
```

#### Expected result
Release PR incremented patch version.

#### Actual result
Release PR incremented _minor_ version.

**Comment by tmatsuo** [comment]
Thanks for the report and the fix!
