### ISSUE TITLE
Automate release milestone creation, milestone closure, and posting release notices on issues/PRs attached to a milestone

### ISSUE THREAD

**Issue by ChipWolf** [googleapis/release-please#1077]
**Is your feature request related to a problem? Please describe.**
I'd like to track the progress towards a release using GitHub's milestones system.

 **Describe the solution you'd like**
When a release PR is created, an associated milestone could also be created. The milestone would close when the release is created. Any issues/PRs associated with the milestone could be updated (& locked) with a message stating the release is available.

 **Describe alternatives you've considered**
 Extending the GitHub action workflow to provide (some of) this functionality

**Comment by chingor13** [comment]
We don't currently have plans to support project management as part of this tool
