### ISSUE TITLE
Create a release PR without a commit for releasing

### ISSUE THREAD

**Issue by mmahalwy** [googleapis/release-please#1081]
Noticed in the nodejs example provided (https://github.com/yargs/yargs) they are using release-please but are not creating commits with `Release-As` to trigger the release-please PRs. They are using the github action. Any idea on how to make this work?

**Comment by chingor13** [comment]
release-please defaults to reading the semantic intent of a commit message using the conventionalcommits.org spec. `Release-As` is only used for overriding the release version in case you make a mistake and cannot rewrite the commit history.

**Comment by mmahalwy** [comment]
@chingor13 thanks for getting back to me! I see what you mean. Same time, I noticed this:
![image](https://user-images.githubusercontent.com/3749095/135897842-2920f688-8743-4d0d-9342-f64561b229f7.png)

I am not seeing where they'd be triggering the release-please PR. No commit for release was created

**Comment by mmahalwy** [comment]
@chingor13 should also mention we are using github action method

**Comment by azzamsa** [comment]
Wondering the same thing. I don't see any thing triggering release-please here: https://github.com/yargs/yargs/commit/e9379e27d49820f4db842f22cda6410bbe2bff10

The both the ci and release-please workflow also had the same trigger: 

```
on:
   push:
     branches:
       - main
```

Are they are creating a release pr in each commit to main, but only merge some of them?
