### ISSUE TITLE
release-please should increment version in `Cargo.toml`.

### ISSUE THREAD

**Issue by lukesneeringer** [googleapis/release-please#1096]
release-please seems to update `Cargo.lock` but not `Cargo.toml` when revving a release. I am using the recommended GitHub Action.

Sadly my repo is private, so I can not point you to it, but here is a screenshot:

![cargo](https://user-images.githubusercontent.com/4346/138951452-702dfd08-fc73-4d90-a34d-c50a350ef6bd.png)

Also, the CI checks never kick off for a reason I have not yet determined, but I expect this is not a release-please problem.

**Comment by chingor13** [comment]
Hi Luke,

Sorry for the delay in getting to this. We were/are in the midst of a major refactor.

For the `Cargo.toml` not updating, is it possible to paste a redacted snippet so we can repro and fix?

For CI not kicking off, this is a symptom of running release-please from an action. PRs created from a GitHub action will not trigger GitHub actions (presumably as an anti-infinite loop measure).

**Comment by chingor13** [comment]
For CI not starting, I opened https://github.com/google-github-actions/release-please-action/issues/404 which is more of a documentation issue. You'll want to provide credentials.

**Comment by jcornaz** [comment]
Hi, 

This seems to work for me on single-package repository (example: https://github.com/jcornaz/benimator/pull/17/files).

But I have the same problem when using a rust workspace (#1170).

@lukesneeringer. Is your repository a workspace?

**Comment by chingor13** [comment]
I think #1182 will fix this as well by ensuring that we always update the Cargo.toml version number with the release version of the component (rather than looking in the version map of component name to new version).
