### ISSUE TITLE
Release pr fails if prerelease found in git history when attempting to find latest tag on new projects using release please

### ISSUE THREAD

**Issue by davidacevedo** [googleapis/release-please#1097]
#### Environment details

  - OS: MacOs Big Sur
  - Node.js version: 14.x
  - npm version: 6
  - `release-please` version: 12.6.0

#### Steps to reproduce

  1. Create new repo (node repo in my case)
  2. Create any release version without release-please
  3. Create any prerelease version without release-please
  4. Add in release please action which then triggers [this piece of code](https://github.com/googleapis/release-please/blob/main/src/github.ts#L739-L752) that fails due to semver no longer being valid 

[Here's a sample repo with the error in the github action](https://github.com/davidacevedo/bug-release-please/runs/4016921280?check_suite_focus=true)

Quick fix would be to set this to false: https://github.com/googleapis/release-please/blob/main/src/releasers/node.ts#L30
Proper fix would be to get rid of this logic https://github.com/googleapis/release-please/blob/main/src/github.ts#L743-L750 as those lines of code break `semver.rcompare` due to `1.0.0-00001` not being valid semver. 

This affects new projects trying to use release please with existing releases/prereleases.

**Comment by chingor13** [comment]
Sorry for the delay in getting to this, we were/are in the midst of a major refactor.

The upcoming v13 should handle parsing pre-release versions. However, it's unclear exactly what the desired behavior here is (aside from not crashing).

Release Please does not currently handle any workflows that can switch between stable and pre-release versions. Release Please doesn't have a way for you to signal that you want it to propose a pre-release vs. the next stable version. In v13, if we detect a version 1.0.0-foo, then next patch version would be 1.0.1-foo (we keep the pre-release version). We do create a new `VersioningStrategy` interface that we could try and create something for signalling pre-release vs stable versions, but that is not yet designed.

**Comment by chingor13** [comment]
This should be fixed in the v13 version of release-please (v3 of the GitHub action)

**Comment by davidacevedo** [comment]
@chingor13 Sorry for not responding forgot about this over the holidays. I was mostly asking if the error could be fixed and it has with the new versions. Updating to release-please-action v3 seems to fix this issue in the sample repo. Thanks for the update.
