### ISSUE TITLE
Is it possible to create tags without prefix "v"

### ISSUE THREAD

**Issue by guoyingtao** [googleapis/release-please#1103]
I like release-please very much, but there is one thing I haven't figured it out how to solve.
My projects are using tags without prefixes like 1.0.0, 1.1.0, the tags created by release-please Github bot are v1.0.0, v1.1.0, etc.
I want to know how to make release-please create tags without the prefix "v", maybe there is a setting related to it but I haven't found it.

Thanks!

**Comment by bcoe** [comment]
@guoyingtao this is not something we currently support, so I've tagged this as a feature request. This is probably functionality that we're unlikely to add in the immediate future (so if possible working around might be best).

However, we are about to land a refactor to release-please, that might make adding customizations like this easier.

**Comment by chingor13** [comment]
We will likely need to support this feature in order to onboard our google-cloud-dotnet repository and preserve backwards compatibility.

**Comment by chingor13** [comment]
Merged in #1346
