### ISSUE TITLE
Add support for GitHub's automaticly generated release notes

### ISSUE THREAD

**Issue by bcoe** [googleapis/release-please#1106]
It's possible to hit an API and generate what would be populated for GitHub's automatically generated release notes.

It would be nice to support this, so that folks can use release-please in conjuntion with the GitHub feature.

**Comment by chingor13** [comment]
https://docs.github.com/en/rest/reference/repos#generate-release-notes-content-for-a-release

https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuring-automatically-generated-release-notes
