### ISSUE TITLE
Odd behavior with Python project, empty package name

### ISSUE THREAD

**Issue by scop** [googleapis/release-please#1140]
release-please(-action) results in some odd behavior with this revision of this project:
https://github.com/scop/pytekukko/tree/f0e87b16737d1cbbcf25dc7e527223ed87921261

Per the job log at https://github.com/scop/pytekukko/runs/4436620942?check_suite_focus=true#step:3:18, we're unsuccessfully trying to look for `__init__.py` and `src//__init__.py`, meaning `projectName` must have been empty.

But if it was empty, IIUC we should not have entered the code block that adds those files to the mix in the first place:
https://github.com/googleapis/release-please/blob/d8bb7caddfa14aabd3bfa19008c10ed911638a66/src/strategies/python.ts#L83
...i.e. `!projectName` would have evaluated to true. But it didn't, for some reason the branch with "No project/component found." log message was not taken, but rather the `else` branch was.

I understand I should have probably given a `package-name` in the actions config or added a `[project]` section in `pyproject.toml` so that `projectName` would have been initialized to something useful. But that's not the point of this report, rather I'm wondering why an empty `projectName` resulted in the above behavior. What made `!projectName` for an empty `projectName` evaluate to false, what am I missing?

**Comment by kalosisz** [comment]
@scop you are looking at main, but release-please-action@v2 doesn't use that. The relevant version in the action is v12.6.0, which didn't check for a non-null `projectName` eg https://github.com/googleapis/release-please/blob/9850c20a7d0dce0d6ca0b14c9cc45d41752f36fc/src/releasers/python.ts#L111

Those warnings were bugging me as well. They have got resolved in v13.0.0

If you wanted to test the latest action, please check https://github.com/google-github-actions/release-please-action/pull/398/files and specify the SHA of that

**Comment by scop** [comment]
Ah! Makes sense now. I can live with this, need to add `package-name` anyway until the tooling around (not release-please but other stuff) is more ready for specifying everything in just `pyproject.toml`. Thanks!
