### ISSUE TITLE
How to release via Manifest config w/ additional files?

### ISSUE THREAD

**Issue by axieum** [googleapis/release-please#1141]
Hi,

I have a Java (w/ Gradle) project acting as a mono-repo. I wish to increment the version of each submodule/package individually, which thus far appears to be "partially" working via the `manifest-pr` and `manifest-release` commands.

Please find the affected [.github/workflows/release.yml](https://github.com/axieum/fabric-release-please/blob/12479817b79c3ec3d05e06b454ef33d61109bc73/.github/workflows/release.yml), [release-please-config.json](https://github.com/axieum/fabric-release-please/blob/12479817b79c3ec3d05e06b454ef33d61109bc73/.github/release-please.json), and resulting pull request axieum/fabric-release-please#6.

1. The commit to be released does not appear in **its** package's section, I would expect it to be in both
2. It does not appear to know how to handle `extra-files: gradle.properties` argument, and hence any additional files are not included in the pull request, see [example-submod/gradle.properties#L5](https://github.com/axieum/fabric-release-please/blob/12479817b79c3ec3d05e06b454ef33d61109bc73/example-submod/gradle.properties#L5)
3. It fails to read the `release-type` from the manifest config when running `manifest-release`, but `manifest-pr` picks it up okay

If these are indeed three unique issues/bugs, I can split this issue up.

I understand this project is under active development for a major milestone, but some guidance would be greatly appreciated.

Thanks,

**Comment by axieum** [comment]
Just seen that the `manifest-*` commands will be deprecated.

I will come back to this after [google-github-actions/release-please-action](https://github.com/google-github-actions/release-please-action) has been updated to reflect the `config-file` and `manifest-file` arguments.

**Comment by chingor13** [comment]
In v3, manifest should still work, except the CLI command is rolled into the same `release-pr` and `github-release` commands. Also, in v13, the manifest config should support `extra-files` for each component in the manifest.

I think @bcoe has a candidate version of the GitHub action that is using the v13 release candidate version of this library if you're interested in trying it out.

**Comment by chingor13** [comment]
Digging into your config, you are using the `java-yoshi` strategy which was built to support our custom repository structure and not necessarily meant for public consumption. It is documented [here](https://github.com/googleapis/release-please/blob/main/docs/java-releases.md)

The `java-yoshi` strategy already handles multiple artifact versions (at the same or different versions). You will need to create a `versions.txt` file at the root of the component ([example](https://github.com/googleapis/java-asset/blob/main/versions.txt)).

Then, I would configure your manifest config `release-please.json` to only have a single component like:

```json
{
  "bump-minor-pre-major": true,
  "bump-patch-for-minor-pre-major": true,
  "packages": {
    ".": {
      "release-type": "java-yoshi",
      "extra-files": ["gradle.properties", "example-submod/gradle.properties"],
    }
  }
}
```

Additionally, the default location for the manifest file is `release-please-config.json` at the root of the component (vs. `.github/release-please.json`).

**Comment by axieum** [comment]
Hi @chingor13, 👋

Thank you for your detailed response, it is very insightful. I'm starting to believe that using the `simple` release strategy would be better suited for my use case. Do you think it's possible to **avoid** a `version.txt` file with said strategy and instead read the current version from the already existing **manifest file**? I could then use the changes you've made in #1157 to update any of my extra files. 🤔

Thanks,

**Comment by chingor13** [comment]
If we merge accept #1157, then we should probably create a separate strategy like `Custom` that only updates the `CHANGELOG.md` and leaves the rest up to configuration with the `extra-files` option.

Also, v13 is the version of release-please -- the action will have a different version tag (maybe v3? or maybe still v2 if we don't have to break the action's interface).

**Comment by axieum** [comment]
A strategy that only updates the `README.md` and the rest is up to the `extra-files` sounds great!

`v13` is the latest branch on the action - it is yet to be merged into `main` and doesn't appear to be tagged yet.

**Comment by axieum** [comment]
I've updated my use case and can confirm points 1 & 3 appear to be fixed. Point 2 is still an issue however. Please see resulting PR axieum/fabric-release-please#19 that fails to update any of the `gradle.properties`. 😊
