### ISSUE TITLE
Release tagging does not trigger other GitHub action workflows

### ISSUE THREAD

**Issue by sethvargo** [googleapis/release-please#1142]
1) Is this a client library issue or a product issue?

    No

2) Did someone already solve this?

    No

3) Do you have a support contract?

    No

#### Environment details

  - OS: Mac OS X
  - Node.js version: 12
  - npm version: 8.1.4
  - `release-please` version: 12.6

#### Steps to reproduce

I think release-please uses the GitHub API to create a release which makes a "fake" tag. This means workflows that rely on the [`push: tags` event](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onpushpull_requestbranchestags) are never run.

**Comment by sethvargo** [comment]
https://stackoverflow.com/questions/15672547/how-to-tag-a-commit-in-api-using-curl-command

**Comment by sethvargo** [comment]
I actually have no idea how release-please is generating a tag, because even when I create a tag via the API, it triggers the `on: push: tags` event:

```
curl -X POST -d '{"ref":"refs/tags/v0.2.0", "sha": "d0b40ea6053fb98039a53abe14fb1377f4c2a6ef"}' -H "Content-Type:application/json" -u ${GITHUB_USERNAME}:${GITHUB_TOKEN} "https://api.github.com/repos/sethvargo/gh-actions-testing/git/refs"
```

**Comment by sethvargo** [comment]
Creating a release where the tag doesn't exist _also_ triggers the workflow:

```text
curl -X POST -d '{"tag_name":"v0.3.0", "target_commitish": "d0b40ea6053fb98039a53abe14fb1377f4c2a6ef"}' -H "Content-Type:application/json" -u ${GITHUB_USERNAME}:${GITHUB_TOKEN} "https://api.github.com/repos/sethvargo/gh-actions-testing/releases"
```

So I'm not really sure why release-please isn't triggering the workflows.

**Comment by sethvargo** [comment]
@bcoe

**Comment by sethvargo** [comment]
Here's an example where release-please created a tag/release, but the "tag" workflow didn't trigger

**Comment by bcoe** [comment]
I belive this might be a constraint of the default credentials used in GitHub Actions, similar to this:

https://github.community/t/push-from-action-does-not-trigger-subsequent-action/16854/4

Just a hunch. But perhaps try using alternate credentials and see if an event triggers?

**Comment by sethvargo** [comment]
I think you're right. Would it make sense to document this? Something like https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs?

**Comment by bcoe** [comment]
@sethvargo I found this better rundown of what's going on:

https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token

I think documenting it somewhere prominent right in the README would be good, an alternate token is an option, or you can do what I did with yargs and run an additional step in the same workflow depending on outputs.

**Comment by chingor13** [comment]
I think this applies only to the GitHub action deployment of release-please and not on the core library. I opened https://github.com/google-github-actions/release-please-action/issues/404. Please reopen if you think this is an error.
