### ISSUE TITLE
v13: release is created with bad title

### ISSUE THREAD

**Issue by chingor13** [googleapis/release-please#1176]
Example: https://github.com/chingor13/release-please-playground/releases/tag/release-please-playground-v1.1.0

The tag is correct, but the title includes the PR title

**Comment by kalosisz** [comment]
@chingor13 the release `name` is not passed to `octokit.repos.createRelease`. in such a case, the release name if `${tag}: ${commit_message}`. you can check it by creating a release manually and only providing a tag and a commitish.
