### ISSUE TITLE
add `docker' as release-type

### ISSUE THREAD

**Issue by ncouture-invue** [googleapis/release-please#1191]
### TL;DR

release-type: docker

Releases a docker image to a registry.

**Comment by chingor13** [comment]
Thanks for filing this.

It's not clear to me how we can do this in a generalized way as tagging of images is often external of the Dockerfile (e.g. a build script running `docker build -t foo/bar:1.2.3` or something like a `cloudbuild.yaml` file)

**Comment by ncouture-invue** [comment]
> Thanks for filing this.
> 
> It's not clear to me how we can do this in a generalized way as tagging of images is often external of the Dockerfile (e.g. a build script running `docker build -t foo/bar:1.2.3` or something like a `cloudbuild.yaml` file)

Currently we tag our images using the strategy outlined by release-please-action and create major and minor tags.

https://github.com/google-github-actions/release-please-action/blob/main/README.md#creating-majorminor-tags

**Comment by chingor13** [comment]
This tool does not actually push any releases or libraries to any package registries -- it only helps you maintain version strings and CHANGELOG entries in code and helps create GitHub releases/tags.

If your Docker image publishing mechanism can be triggered and tagged from the GitHub release tag, then you can probably use the `simple` release-type strategy to maintain just the CHANGELOG in code.

**Comment by ncouture-invue** [comment]
> This tool does not actually push any releases or libraries to any package registries -- it only helps you maintain version strings and CHANGELOG entries in code and helps create GitHub releases/tags.
> 
> If your Docker image publishing mechanism can be triggered and tagged from the GitHub release tag, then you can probably use the `simple` release-type strategy to maintain just the CHANGELOG in code.

Thank you @chingor13 for the additional explanation. I had yet to look at the source code and understand better what release-please does specifically.

The issue I ran into is that some of our applications are *node* applications and even if they are not released as node libraries, the version is tracked for example in `package.json` and so this needs to be bumped as well as the version tag on the repo and then on the docker images being built.

That said I believe it may be simpler in our case to resort to agreing that node *applications* will not track their version in `package.json` but instead in the version.txt already managed by release-please.

I have attempted to bump the version of `package.json` in the same release-please Github Workflow that builds, tags, and publishes the docker images but ran into an issue I was unable to solve or workaround. Perhaps this was a limitation where the GITHUB_ACTION system user could not commit to the repository or that the additional commit that's required had a side-effect I had not predicted.

Let me know if it's of interest and I could repro. Otherwise I don't see how this release-type could be added to release-please as it was already trivial to authenticate to docker registry, build, tag and push docker images in a modified release-please.yaml workflow. 

All this using, as you recommended, the "simple" release-type strategy.

**Comment by chingor13** [comment]
Personally, I would probably use the `node` release type even though the application is not published to `npm`. release-please would manage the version in `package.json` and create release pull requests and GitHub releases.

Deploying/building the image could be triggered by the `release.created` webhook event (using some other workflow or integration).

> I have attempted to bump the version of package.json in the same release-please Github Workflow that builds, tags, and publishes the docker images but ran into an issue I was unable to solve or workaround.

In general, we separate the preparation of a release from the actual deployment/build of a release. In this case, we prepare a release by bumping version numbers in code (`package.json`), then create a release by tagging a release on GitHub. The deployment (building and tagging a docker image) would happen after the GitHub release is tagged.
