### ISSUE TITLE
Suggests duplicate release PR in between time release PR merged and release created

### ISSUE THREAD

**Issue by bcoe** [googleapis/release-please#1208]
I noticed that when using the release-please app, there's a race condition, such that an identical release PR is created before a release is tagged:

Refs: https://github.com/googleapis/nodejs-network-security/pull/27

**Comment by chingor13** [comment]
Weird, I would expect https://github.com/googleapis/release-please/blob/d29eda172597979cea5cb54ce6eb278a1dfb03a0/src/manifest.ts#L577-L585 to catch that

**Comment by chingor13** [comment]
Note that `findMergedReleasePullRequests()` uses the GraphQL API so maybe there's a delay in indexing between when a pull request is merged and when it's returned by the GraphQL API.

**Comment by chingor13** [comment]
Downgrading to p2 to see if 3101 fixed it

**Comment by chingor13** [comment]
We haven't seen this recently in the app, closing for now.

**Comment by sam3k** [comment]
Just for the record, I was seeing this error and the issue for me was that the last PR release please generated still had the `autorelease:pending` label on it as [mentioned in the docs](https://github.com/googleapis/release-please#release-please-bot-does-not-create-a-release-pr-why). 

Removing the label and manually re-triggering the workflow of the last release please job got rid of the error and began to create new PRs again.

**Comment by marcopeise** [comment]
Same class of timing issue as #2754: GitHub API lag between creating/updating a PR and subsequent REST calls against it. #1208 is about merge → next run visibility; #2754 is about create → immediate `addLabels` returning 422 `Issue not found`.

Fix PR for the label race: #2782 (Fixes #2754).
