### ISSUE TITLE
bump-minor-pre-major not behaving as expected prior to first release

### ISSUE THREAD

**Issue by bcoe** [googleapis/release-please#1209]
If a library has not been released yet, but has a package.json at a pre-major version, `bump-minor-pre-major` suggests `1.0.0` as the first release still.

Refs: https://github.com/pkgjs/parseargs/pull/36

**Comment by chingor13** [comment]
This is intended behavior - the initial release version is specified by the release strategy (or Release-As commit in #1222). For an initial release, there's no notion of version bumping as there was no previous release.
