### ISSUE TITLE
release-please(java): release PRs not updating all pom files

### ISSUE THREAD

**Issue by kolea2** [googleapis/release-please#1234]
Examples:
https://github.com/googleapis/java-bigtable-hbase/pull/3470
is missing

- https://github.com/googleapis/java-bigtable-hbase/blob/bigtable-1.x/bigtable-client-core-parent/bigtable-client-core/pom.xml
- https://github.com/googleapis/java-bigtable-hbase/blob/bigtable-1.x/bigtable-client-core-parent/bigtable-metrics-api/pom.xml

https://github.com/googleapis/java-bigtable-hbase/pull/3461
is missing

- https://github.com/googleapis/java-bigtable-hbase/blob/1.20.0-sp/bigtable-client-core-parent/bigtable-client-core/pom.xml

Separately, 1.25.2-sp's snapshot PR never generated (https://github.com/googleapis/java-bigtable-hbase/tree/1.25.2-sp).

**Comment by chingor13** [comment]
Looks like we are search for files on the default branch and not the target branch.
