### ISSUE TITLE
cargo-workspace plugin does not handle Cargo.lock files correctly

### ISSUE THREAD

**Issue by gsrushton** [googleapis/release-please#1250]
#### Environment details

  - OS: Ubuntu 20.04
  - Node.js version: 16.13.2
  - npm version: 8.1.2
  - `release-please` version: 13.4.2

#### Steps to reproduce

  1. Create a rust workspace project (https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html) containing a single package `crates/package`.
  2. Run release-pr and observe:
    1. release-please tries to add a patch for `crates/package/Cargo.lock`.
    2. release-please doesn't try to add a patch for `Cargo.lock`

When using a cargo workspace the individual crates within that workspace don't have their own Cargo.lock file. Rather, they share a single Cargo.lock file at the root of the workspace. Quoting from https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html:

> Notice that the workspace has only one Cargo.lock file at the top level of the workspace rather than having a Cargo.lock in each crate’s directory.

I'm happy to have a go at making this work correctly, I just need some pointers to make sure I head in the right direction.

**Comment by chingor13** [comment]
Help would be appreciated on this.

In a manifest (multi-component) repo, we treat individual components (paths) like standalone repositories. We build candidate release pull requests as though they were released individually. The manifest plugins consider all the candidate pull requests and often merge them together with the understanding of the monorepo structure. Thus, the plugins can know about workspaces and how components are interdependent.

In the case of a cargo workspace, it looks like we'd want to add an extra file updater for the root `Cargo.lock` to the combined release pull request that we merge from the multiple candidate pull requests.

**Comment by jcornaz** [comment]
Be aware that there isn't always a lock file (workspace or not) in rust projects. With rust, lock-files are commited for *applications*, but they are not commited for *libraries*. See: 

* https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html
* https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries

I just thought I would mention it. So that release-please remain resilient in case there is no lock file.

**Comment by gsrushton** [comment]
> Be aware that there isn't always a lock file (workspace or not) in rust projects. With rust, lock-files are commited for _applications_, but they are not commited for _libraries_. See:
> 
>     * https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html
> 
>     * https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries
> 
> 
> I just thought I would mention it. So that release-please remain resilient in case there is no lock file.

Thanks for the heads-up but I don't believe this is an issue for this work:
1. There is always a lock file, it's just a question of whether it should be included in version control.
2. As you state, it's good practice to omit the lock file from version control for libraries. This is to avoid downstream users from being locked into potentially conflicting dependencies when they depend on your library as cloned from VC. However, workspaces are not a library, and indeed downstream users can't declare dependencies on them. Therefore, I don't see a compelling reason why they shouldn't always be included in the version controlled assets.
3. Even if a user should want to omit them from version control I don't think it's the purview of this plugin to make that decision. If that functionality is required it should probably be handled (and may already be handled?) by release-please examining the contents of candidate pull requests against any `.gitignore` directives.

**Comment by jcornaz** [comment]
A workspace may be a library workspace. As it may be an application workspace. Of course, this issue should still be solved. I just wanted to make sure, that we don't break the behavior for library workspace by solving this issue.
