### ISSUE TITLE
Validation Failed: {"resource":"Release","code":"already_exists","field":"tag_name"}

### ISSUE THREAD

**Issue by jcornaz** [googleapis/release-please#1259]
#### Environment details

  - OS: ubuntu-latest
  - Node.js version: none
  - npm version: none
  - `release-please` version: Via github actions: `google-github-actions/release-please-action@v3.1.0`

#### Steps to reproduce

I am not so sure actually. I tried to create a SSCCE but without success. Instead here is the repository where I currenty have the problem:

* repository: https://github.com/jcornaz/benimator
* logs: https://github.com/jcornaz/benimator/runs/4925496243?check_suite_focus=true

Please note that I cannot (or don't know how to) recover from that problem! It is persistently failing. Which means I am back on manual release process for that repository :-/

I feel like it is probably due to the usage of either (or both):
* `release-as` footer in some commit essage
* the fact that I released some pre-release (`v2.0.0-rc.1` before `v2.0.0`)

Note, there is already an issue opened on the github action, that seems very similar: https://github.com/google-github-actions/release-please-action/issues/409. I open this one here because it is very likely of being a problem of `release-please` rather than of the github actions.

**Comment by jcornaz** [comment]
Thanks @chingor13, your adviced help. It no longer fails. Now it suggests to release version `2.0.0` (https://github.com/jcornaz/benimator/pull/32) which is already released. But I guess for my next release I'll be able to write a `release-as: 2.1.0` footer in a commit message, and it should go back to normal right?

However, that's more work-around anyway isn't it? Maybe the system could be made more robust? For example:

* When looking for existing pull requests, only fetch for *open* ones
* It coul fetch the tags to know what is the latest released version

**Comment by chingor13** [comment]
Yeah, release-please has a notion of what the last release commit/PR looks like and we should be more robust/resilient in finding the correct value.

Closing this one and tracking the improvement in #1266.
