### ISSUE TITLE
List.name='List' getting webpack error while building on netlify

### ISSUE THREAD

**Issue by Bilal-Bangash** [googleapis/release-please#1262]
#### Environment details

  - OS:Windows
  - Node.js version:14.16.0
  - npm version:6.14.11
  - `release-please` version:9.0.1

#### Steps to reproduce

  1. gatsby project with reactstrap version 9.0.1 while building on netlify returning below error in screenshot

![image](https://user-images.githubusercontent.com/53056567/151659021-925b469b-63db-4e26-a4d3-70f6b71572a5.png)

**Comment by chingor13** [comment]
Sorry, I don't see anything in that screenshot related to release-please. If you have a better stacktrace, we can try to help.
