### ISSUE TITLE
Detect and recover from detached tag edge-case

### ISSUE THREAD

**Issue by ChipWolf** [googleapis/release-please#1263]
> Appreciated @chingor13 this was the issue. A good enhancement feature to take from the back of this issue would be to spot if the latest version tag is detached from the target branch and to raise an error rather than going ahead with a release; would you agree?

---

While using the manifest releaser in a GitHub action, it seems release-please cannot find the latest release, so each release always contains all available commits _(unless the `lastReleaseSha` is set)_.

#### Environment details

  - release-please v3.1.0
  - GitHub Action hosted runner

#### Steps to reproduce

  1. Push some commits _(A, B, C)_
  1. Squash merge release PR
  2. Push some more commits _(X, Y, Z)_
  3. Observe new release PR contains all commits _(A, B, C, X, Y, Z)_ & the log output contains `No latest release pull request found.`
  
v9.0.0 _(with `lastReleaseSha` referencing the v8.6.0 release commit in the config)_
```
✔ Using configured lastReleaseSha 4dfee14217ffd785b6eff468bb4f392970a9019b as last commit.
✔ Splitting 3 commits by path
✔ Building candidate release pull request for path: .
⚠ No latest release pull request found.
✔ No latest release found for path: ., component: , but a previous version (9.0.1) was specified in the manifest.
✔ Considering: 3 commits
⚠ There are untagged, merged release PRs outstanding - aborting
✔ Building releases
✔ Building strategies by path
✔ Looking at files touched by path
✔ Building release for path: .
...
```
  
v9.0.1 _(after removing `lastReleaseSha` from the config)_
```
⚠ Expected 1 commits, only found 0
✔ Splitting 250 commits by path
⚠ No latest release pull request found.
✔ Building candidate release pull request for path: .
✔ Considering: 293 commits
✔ Looking for open release pull requests
✔ found 0 open release pull requests.
✔ Starting GitHub PR workflow...
...
```

**Comment by chingor13** [comment]
Are you able to link to your manifest config/repo?

**Comment by ChipWolf** [comment]
It's a private repo, @bcoe already has access & I've just invited you @chingor13

**Comment by chingor13** [comment]
From investigating the code, I can't see what's creating the GitHub release. However, the commit tagged by the 9.0.1 release (`b79ec10`) does not seem to match the commit we expect to see on the main branch (`afec168`).

In order to determine commits since the last release, we iterate backwards through commit history to find the commit SHA of the release. In this case, we don't see the SHA for 9.0.1 so it keeps iterating until it hits our max commits considered (250).

**Comment by ChipWolf** [comment]
Appreciate @chingor13 this was the issue. A good enhancement feature to take from the back of this issue would be to spot if the latest version tag is detached from the target branch and to raise an error rather than going ahead with a release; would you agree?

**Comment by bcoe** [comment]
@ChipWolf that's great news :raised_hands:, I switched this to be a `feature` request, and moved the resolution (and requests) to the body.

**Comment by ChipWolf** [comment]
This appears to have been fixed at some point, I can't replicate.
