### ISSUE TITLE
samples/package.json no longer updated during release

### ISSUE THREAD

**Issue by bcoe** [googleapis/release-please#1264]
It appears that `samples/package.json` is no longer updated for Node.js release, see:

https://github.com/googleapis/google-api-nodejs-client/pull/2880
https://github.com/googleapis/nodejs-firestore/pull/1665

This results in the samples running against the wrong version of the library after the release is merged (noticed due to failing PRs on google-api-client).

**Comment by chingor13** [comment]
Looks like we are passing `component` to `packageName`. The component is related to the package name, but can be different. The samples json updater can't find a package using the component name, so it's not updating anything.
