### ISSUE TITLE
Sometimes fails to find latest release when using Manifest.fromConfig

### ISSUE THREAD

**Issue by chingor13** [googleapis/release-please#1266]
If you are using `Manifest.fromConfig` (e.g. not using a manifest file in the repository), we can fail to find the correct latest release.

This could be because the release was manually tagged and doesn't match with what release-please expects.

See https://github.com/googleapis/release-please/issues/1259#issuecomment-1022603167

**Comment by kalosisz** [comment]
@chingor13  this is also related https://github.com/google-github-actions/release-please-action/issues/400
