### ISSUE TITLE
Option to show "chores" as part of release notes

### ISSUE THREAD

**Issue by bshaffer** [googleapis/release-please#1276]
For the PHP releases, we'd really like to show conventional commits labeled with "chore" as "Miscellaneous Chores"

See https://github.com/googleapis/repo-automation-bots/issues/3145

This was happening with our previous releases ([v0.172.0](https://github.com/googleapis/google-cloud-php/releases/tag/v0.172.0)), but recently this has gone away ([v0.173.0](https://github.com/googleapis/google-cloud-php/releases/tag/v0.173.0))

**Comment by chingor13** [comment]
This is a regression from v12 -> v13
