### ISSUE TITLE
Force push instead of close/open new PR

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/release-please#128]
On [gax-nodejs](https://github.com/googleapis/gax-nodejs/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed) I saw that the first commit after landing the bot came through.  The bot seems to close the existing release PR, and then just open a new one.  Is it worth having the bot force push it's changes on the same PR instead of creating a new one?

**Comment by bcoe** [comment]
should be handled by: https://github.com/googleapis/release-please/pull/152
