### ISSUE TITLE
Update the library version in the snippet metadata files

### ISSUE THREAD

**Issue by sofisl** [googleapis/release-please#1281]
Currently, snippet metadata files need the current version of the library [here](https://github.com/googleapis/nodejs-bigtable/blob/ad426f958a295a4ddf9cd1e90a0cc3c0b9603599/samples/generated/v2/snippet_metadata.google.bigtable.v2.json#L4). However the generator doesn't know what version of the library we're on, so it would be nice if release-please could update this field as well as wherever else it updates the version on the library (i.e., for Node, `package.json`. cc @amanda-tarafa, since this will affect all languages/snippet metadata files

**Comment by amanda-tarafa** [comment]
Is release-please the one who bumps the libray version? Or is it a per language script that does that, which is called by release-please?

**Comment by chingor13** [comment]
@sofisl If we were to build this, we would likely do as part of #1171. This is a non-standard file that doesn't apply to most release strategies.

Note that this library is completely agnostic to any of our other code generation pipelines so this version bump would happen at release time. This would probably mean that the next codegen after the release would pick up the new version.
