### ISSUE TITLE
Missing a bunch of "outputs" that were used by release-please-action

### ISSUE THREAD

**Issue by phated** [googleapis/release-please#1286]
The v13 rewrite of this project removed a bunch of outputs that the release-please-action used to provide. For example, the `upload_url` was removed completely, as raised in https://github.com/google-github-actions/release-please-action/issues/426

Additionally, the `body` was removed, which was used to provide release notes to other tools.

Some of these were documented in the "output" section of https://github.com/google-github-actions/release-please-action#configuration, while some (like "body" weren't); however @bcoe had opened this issue about the different fields that were added to outputs: https://github.com/google-github-actions/release-please-action/issues/297 

This issue seems to be affecting a lot of users of the GitHub Action (check out the issue tracker).

1) Is this a client library issue or a product issue?
This is an issue with the output of the release-please tool, as used by release-please-action to product outputs.

2) Did someone already solve this?
No

3) Do you have a support contract?
No

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - OS: Any (GitHub Action)
  - Node.js version: Node 12 (used by GHA)
  - npm version: Unsure
  - `release-please` version: v13.x (bundled in GHA)

#### Steps to reproduce

  1. Use the outputs of the GHA in v2
  2. Upgrade to v3 and see failures in release CI

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by chingor13** [comment]
So it looks like the one piece of data we are not returning is the `upload_url`. The `html_url` (url of the release) is being returned as `url`.

**Comment by phated** [comment]
Body (`body`) of the PR isn't available either.

**Comment by chingor13** [comment]
#1298 will now have release-please return `uploadUrl` and fixes some edge cases for how `body` is returned (as `notes`).

It will be up to the action to coerce those fields back to the names it was previously using if it wants to.

**Comment by chingor13** [comment]
https://github.com/google-github-actions/release-please-action/pull/437 should fix the outputs of the action
