### ISSUE TITLE
`include-component-in-tag: False` fails to parse generated pr body

### ISSUE THREAD

**Issue by axieum** [googleapis/release-please#1294]
Hi, 👋

#### Environment details

  - OS: GitHub Actions
  - `release-please` version: [v13.4.8]()
  - `release-please-action` version: [v1.1.1]()

#### Steps to reproduce

1. Create the following Manifest file

```json
{
  "release-type": "simple",
  "bump-minor-pre-major": true,
  "bump-patch-for-minor-pre-major": true,
  "group-pull-request-title-pattern": "chore: release v${version}",
  "extra-files": ["gradle.properties"],
  "packages": {
    ".": {
      "component": "fabric-example-mod",
      "include-component-in-tag": false
    },
    "example-submod": {
      "component": "example-submod"
    }
  }
}
```

2. Observe the suggested PR body, which contains the root package (with no component) as `: ${version}`

![image](https://user-images.githubusercontent.com/7577851/153692971-2dbbe26f-3d5b-4cf1-a561-1502690491ec.png)

_Sourced from axieum/fabric-release-please#32_

3. Merge the PR and observe the following warning logs

```
⚠ Summary: : 0.1.1 did not match the expected pattern
```

4. Observe the created GitHub release notes -

![image](https://user-images.githubusercontent.com/7577851/153693107-e49f8af6-22f5-4186-a8ed-08ce8c9af858.png)

#### Possible Cause

It appears that when the component is excluded from the tag (for the root package), it just sets the component to `''`.

https://github.com/googleapis/release-please/blob/7584fecd34794ed146117c80a7f37f8e64f9d0bf/src/util/pull-request-body.ts#L66-L68

The regex that parses the pr body, would possibly need updating too.

https://github.com/googleapis/release-please/blob/7584fecd34794ed146117c80a7f37f8e64f9d0bf/src/util/pull-request-body.ts#L111

Thanks for this evolving library,
Jonathan. 😊

**Comment by chingor13** [comment]
Thanks, this definitely looks like a bug and aesthetically, the PR body summary looks bad.
