### ISSUE TITLE
How to trigger npm preversion - npm version - npm postversion?

### ISSUE THREAD

**Issue by mauriciolauffer** [googleapis/release-please#1301]
Running the command `npm version *****` triggers some scripts which could be used to build and commit the distribution version of the project before publishing it.

When using `release-please` these scripts are not triggered. How to trigger npm `preversion` `version` `postversion`?

**Comment by chingor13** [comment]
release-please is language/tool agnostic and does not actually run any npm lifecycle events. Any actual publishing/building must be done by external automations.

An example could be to trigger a GitHub action workflow that runs only against release-please PRs that runs `npm run some-script` and commits the changes to the PR branch.
