### ISSUE TITLE
Add labels to manifest options when parsing config

### ISSUE THREAD

**Issue by psirenny** [googleapis/release-please#1302]
I'd like to change the default **"autorelease: pending"** GitHub label when using the release-please action. However, labels are not included in manifest options when the config file is parsed. [On these lines](https://github.com/googleapis/release-please/blob/main/src/manifest.ts#L973), `labels` and `releaseLabels` properties are missing.

**Comment by chingor13** [comment]
Thank, this does look like a bug (oversight)

**Comment by psirenny** [comment]
Thanks!
