### ISSUE TITLE
Manifest release not updating any package.json versions

### ISSUE THREAD

**Issue by dyladan** [googleapis/release-please#1317]
Our manifest releaser is not updating the `version` field of any package.json files. It recognizes that the versions have changed and correctly creates changelog files and updates the `dependencies` field to reflect what the new version should be, but the actual `version` field itself is incorrect

You can see an example of this here https://github.com/open-telemetry/opentelemetry-js-contrib/pull/924/files

#### Environment details

  - OS: macos and linux
  - Node.js version: 16
  - npm version: 7
  - `release-please` version: 13.4.12

**Comment by chingor13** [comment]
This looks like a bug for sure. We're updating the dependency versions, but not the main version in the `package.json`

**Comment by dyladan** [comment]
Is there anything I can do in the meantime to unblock my release? we just switched from the github action v2 to v3 and that changed the branch name which required a pull request with reviews and for me to go through the admin approval process to change our branch protection rule name. Not really something I'm excited to do again to roll back.

**Comment by chingor13** [comment]
I ran the CLI from the branch in #1319 and it created https://github.com/open-telemetry/opentelemetry-js-contrib/pull/926

It looks like there's a weird oddity with empty "Dependencies" sections in the changelogs, but the version numbers now look correct
