### ISSUE TITLE
Support for simple Java projects

### ISSUE THREAD

**Issue by mdvorak** [googleapis/release-please#1334]
There is a support via `java-yoshi` strategy, but that is tailored to Google needs, and it is quite confusing and error-prone for generic Maven/Gradle projects.

I propose creating basic `java` strategy, which does not require `versions.txt` file - this complex functionality is usually not needed, and easily can cause getting releases and actual artifact versions out-of-sync (by human error). `java-yoshi` should retain its current functionality.

Related PR draft: #1333

**Comment by chingor13** [comment]
We can create a simplified Java strategy, although I think we will really want to simplify it.

The annotations were an artifact from our previous release scripts and not necessarily something we want other folks to use. I would suggest a new Java class that only updates the pom.xml and CHANGELOG.md that also knows how to create the -SNAPSHOT PRs.

**Comment by chingor13** [comment]
We can create a simplified Java strategy, although I think we will really want to simplify it.

The annotations were an artifact from our previous release scripts and not necessarily something we want other folks to use. I would suggest a new Java class that only updates the pom.xml and CHANGELOG.md that also knows how to create the -SNAPSHOT PRs.
