### ISSUE TITLE
Inconsistency between config file and arguments when using CLI

### ISSUE THREAD

**Issue by mdvorak** [googleapis/release-please#1340]
As I'm digging in the code, I found out that there are two completely different paths how releases are handled in `manifest.ts`:

1. When using `release-pr --release-type ....`, manifest is created via `Manifest.fromConfig`, which ignores `.release-please-manifest.json` file altogether, and always searches for latest release via API
2. When using `release-please-config.json`, it requires  `.release-please-manifest.json` and never searches for latest release via API

I assume this is result of some historical development, and most users probably aren't using config file. I would however expect that it would behave same for either configuration option - if there is manifest json present, use it, if not, search for releases.

Question is: Should we do something about it? I think it affects minimum users. But for example java-yoshi strategy is broken when using the manifest file (and is therefore incompatible with config json file).

**Comment by chingor13** [comment]
When the manifest config was first created, it was added on as a secondary path. In v13, we refactored to make manifest and single configuration paths use the same code path.

If you want to use the manifest, then do not specify the `--release-type` CLI argument. It will load the release type from manifest config file based on path.

As for mismatches in versions. The manifest JSON is meant as as the source of truth for the last tagged release. If someone tags a release manually outside of release-please, we can't really determine what is supposed to be correct.
