### ISSUE TITLE
Make release-please package extendable

### ISSUE THREAD

**Issue by mdvorak** [googleapis/release-please#1341]
Right now, release-please is customizable, but only by forking it. 
By making it possible to register new strategies (etc) in `factory.ts` by 3rd party, it would be extendable by using pre-built npm package instead. I did not find any reason why configuration should be static.

Here is rough PR: #1342

**Comment by chingor13** [comment]
I think this would be a good addition.

So, we're going to export some methods like `registerStrategy(name: string, builder: (opts) => Strategy)`, etc?

**Comment by mdvorak** [comment]
> I think this would be a good addition.
> 
> So, we're going to export some methods like `registerStrategy(name: string, builder: (opts) => Strategy)`, etc?

Yeah, that is exactly my idea - I've already tried it in attached PR and it seems to work. It should work with custom release-please-bot or forked action (and, of course, with wrapped CLI).

**Comment by mdvorak** [comment]
@chingor13 I've finished PR, please check it out https://github.com/googleapis/release-please/pull/1342
