### ISSUE TITLE
Top level "release-as" doesn't override package's version if it has node workspace dependencies 

### ISSUE THREAD

**Issue by jeremytchang** [googleapis/release-please#1348]
We recently tried to update from v2 to v3 in our [mono repo](https://github.com/looker-open-source/sdk-codegen) and I think we're encountering a bug, so we can't migrate to it. 

In v2:
When we define a top level "release-as" in our [release-please-config.json](https://github.com/looker-open-source/sdk-codegen/blob/main/release-please-config.json) all packages without a package level`release-as` have their version correctly set to the top level "release-as".

In v3:
When we define a top level "release-as" in our [release-please-config.json](https://github.com/looker-open-source/sdk-codegen/blob/main/release-please-config.json) all packages without a package level `release-as` *but have node workspace dependencies* don't have their version set to the top level "release-as" anymore.

**Comment by chingor13** [comment]
Closing as I couldn't reproduce and haven't heard back.

**Comment by jeremytchang** [comment]
Hi! Sorry for the late reply and lack of supporting documentation. We are looking to move to v3 and have hit this issue again.

Here's the rundown (I will link to both current file and simplified gist): 

We have a monorepo with packages that are both calendar versioned and conventionally/semantic versioned. 

Release please config:
We have a release please config setup to allow for both calendar and semver versioning at the same time. We make use of the top-level release-as to set calendar version on any packages without package scoped release-as. Any package scoped release-as naturally does semver. Release please config: https://github.com/looker-open-source/sdk-codegen/blob/main/release-please-config.json, its gist: https://gist.github.com/jeremytchang/7ea532963718f1fc93d1146efc2209b2. For this example we'll focus on the sdk and hackathon package. Note that we have the top level release-as set to 23.0.0. 

Release manifest:
Our release manifest is at https://github.com/looker-open-source/sdk-codegen/blob/main/.release-please-manifest.json and its gist: https://gist.github.com/jeremytchang/48964c5da29c863c6c9a036d8e78f66f. Note both sdk and hackathon package are at 22.20.1

Release PR:
Release please created a release PR with sdk's version set to 23.0.0, but only patches hackathon's version to 22.20.2. PR here: https://github.com/looker-open-source/sdk-codegen/pull/1241. The PR description Gist here: https://gist.github.com/jeremytchang/da0056d57200ad8c8baa16a202a57c40. We expect hackathon to set to 23.0.0 since it should follow the top level release-as.

The package.json's of each package:
We surmise this possible could be because hackathon has a dependency on the 23.0.0 sdk package while sdk package does not have a dependency on a monorepo package that's been updated. hackathon's package.json: https://gist.github.com/jeremytchang/b0b98d1a648d2e32c739d51f61a4ce88 sdk's package.json (note that sdk-rtl was not updated): https://gist.github.com/jeremytchang/6d50979c53e607a8228700e7b063e67d.

I hope all this information helps.
