### ISSUE TITLE
[java-snapshot] should remove label if PR changes from regular release to snapshot

### ISSUE THREAD

**Issue by chingor13** [googleapis/release-please#1352]
https://github.com/googleapis/java-bigtable/pull/1215 was originally opened as a regular release, but changed to a snapshot. Automation then tried to release the snapshot and failed.

**Comment by mdvorak** [comment]
Labels are not updated at all during PR update.

**Comment by chingor13** [comment]
This is extremely rare and we probably don't actually need this.
