### ISSUE TITLE
Empty commits dependent on what packages have more recently been changed

### ISSUE THREAD

**Issue by ivomurrell** [googleapis/release-please#1360]
#### Environment details

  - OS: macOS 12.2.1
  - Node.js version: 16.14.0
  - npm version: 8.5.4
  - `release-please` version: 13.8.0

#### Steps to reproduce

  1. Create a monorepo with multiple packages managed by release-please.
  2. Based on the functionality added in #752, create an empty commit with a `release-as` footer specifying a new version, e.g., `7.7.7`.
  3. Generate a release PR for the empty commit. Instead of creating a release candidate for `7.7.7` for every package in the monorepo, observe that no PR is created.

#### Why this is happening

It appears that this is happening because `commit-split.ts` is only adding the empty commit to packages that have had more recent commits which bump the package's version. Any package that hasn't been modified by subsequent commits won't be included in the empty commit's release. If the empty commit is the latest commit then no packages will be released.

Perhaps we could pre-populate the `splitCommits` object with the path filters set in `this.packagePaths` if that is set?

**Comment by ivomurrell** [comment]
It looks like that special case has already been implemented in #752: if the [`includeEmpty`](https://github.com/googleapis/release-please/blob/main/src/util/commit-split.ts#L33) option is set in `CommitSplit` then all components will be updated for an empty commit, else no components will be updated. The options is currently always set to `true` in [`manifest.ts`](https://github.com/googleapis/release-please/blob/main/src/manifest.ts#L531).

**Comment by ivomurrell** [comment]
For what it's worth, our main use case for this is bumping all of our packages to a new major version now that we've switched to release-please and started handling semantic version properly. There doesn't seem to be any other way to force an update like that (excluding artificially touching files in all the components.) I could also think of a case where you, for example, officially drop support for an older version of Node in your repository, which would be a breaking change but not necessarily one that will affect code in every component.

**Comment by chingor13** [comment]
@ivomurrell , I have a fix for empty commits correctly applying to all components, but if all your components should be linked at the same version at all times, you can look at the [`linked-versions` plugin](https://github.com/googleapis/release-please/pull/1327) (needs better documentation).
