### ISSUE TITLE
There are untagged, merged release PRs outstanding - aborting

### ISSUE THREAD

**Issue by CBenoit** [googleapis/release-please#1406]
Hi,

I'm trying to configure a repository to use release-please to automate release process.
I've started with a dummy repository to play around with it:

https://github.com/CBenoit/actions-tests

I got the first release PR successfully: https://github.com/CBenoit/actions-tests/pull/1

However, now it's aborting with this message:
```
❯ Found pull request #1: 'chore: release main'
⚠ There are untagged, merged release PRs outstanding - aborting
```
See full logs [here](https://github.com/CBenoit/actions-tests/runs/6104681290).

Notice that I have tagged the release commit: https://github.com/CBenoit/actions-tests/tags
That's the correct commit as seen on the main branch.
Also, I expected `release-please` to add the tags automatically instead of having to add them manually, maybe I missed something. The PR didn't get the tag `autorelease: tagged` which is suspicious.

I also tried to specify [the last release SHA manually](https://github.com/CBenoit/actions-tests/blob/0defda4bc3411983cf227718585f7141061e51e7/release-please-config.json#L3).

This might be related to https://github.com/googleapis/release-please/issues/1263 but I'm not too sure.

Do you have any idea?

Thank you!

**Comment by chingor13** [comment]
The `release-please` binary has 2 commands: `release-pr` (opens a release pull request) and `github-release` (tags and creates a GitHub release for a merged release pull request).

It looks like you are running `release-please` manually via GitHub actions. If you do, you'll want to run the `github-release` command first, then the `release-pr` command after.

Alternatively (and probably more maintainable), you can use our pre-built action for running release-please: https://github.com/google-github-actions/release-please-action

**Comment by CBenoit** [comment]
Thank you, apparently I misread the documentation.
Have a great day!
