### ISSUE TITLE
One PR keeps getting overwritten by two conflicting configurations

### ISSUE THREAD

**Issue by codyoss** [googleapis/release-please#1411]
#### Steps to reproduce

  1. I have two release PRs configured at the base of the repository. One is a manifest release for many projects I oversee and the other is a non-manifest. The two I don't think can be combined, I could be wrong, because of I need the component to not do anything for the root release but for the manifest release it is used for proper tagging. [config 1](https://github.com/googleapis/google-cloud-go/blob/main/release-please-config-yoshi-submodules.json) [config 2](https://github.com/googleapis/google-cloud-go/blob/main/release-please-config.json)
  2. Because the action for both is configured at the root of the repository both releases fight over the same PR. The last one to run wins. [action config](https://github.com/googleapis/google-cloud-go/blob/main/.github/release-please.yml) I can't really show an example because you need to watch a PR overtime and the changes are blasted away due to the force push nature of release-please.

#### How this could be fixed

1. Have an option to specify a branch prefix for a release PR. That way I could configure these two to be separate PRs
2. In a manifest release support a special component name that will not be included as a part of tagging

**Comment by chingor13** [comment]
If I'm following, this is happening because both configs are trying to use the `release-please--branches--main` branch.

I think option 2 would also make it so we only have to make a single pass through commits.

**Comment by codyoss** [comment]
@chingor13 That is correct. And I think you are right, that is a strong case for #2.
