### ISSUE TITLE
There are untagged, merged release PRs outstanding - aborting on other branch than default

### ISSUE THREAD

**Issue by paoll** [googleapis/release-please#1444]
When using `release-please-action` on another branch than the default one, the PR is correctly opened, but once merged it fails to create the release:

```shell
 ✔ Looking for latest release on branch: hotfix/v3.1.0-bug with prefix: <repository-name>
✔ Building releases
✔ Building strategies by path
✔ Building release for path: .
⚠ pullRequestTitlePattern miss the part of '${scope}'
⚠ pullRequestTitlePattern miss the part of '${component}'
⚠ pullRequestTitlePattern miss the part of '${version}'
✖ Bad pull request title: '[HOTFIX] - chore(hotfix/v3.1.0-bug): release 3.1.0-hotfix1'
✔ No release necessary for path: .

✔ Looking for latest release on branch: hotfix/v3.1.0-bug with prefix: <repository-name>
✔ Building pull requests
✔ Building strategies by path
✔ Collecting release commit SHAs
✔ Collecting commits since all latest releases
✔ Splitting 4 commits by path
✔ Building candidate release pull request for path: .
✔ Considering: 5 commits
⚠ There are untagged, merged release PRs outstanding - aborting
````

The PR is still labelled as `autorelease: pending`, thus the release is not created.

My configuration is the following one:

```shell
[...]
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: ${{ github.event.repository.name }}
          token: ${{ secrets.token }}
          default-branch: ${{ github.ref_name }}
          pull-request-title-pattern: "[HOTFIX] - chore${scope}: release${component} ${version}"
          monorepo-tags: false
```

There is a related issue on https://github.com/google-github-actions/release-please-action/issues/443

**Comment by chingor13** [comment]
The warning for untagged, merged release PRs is because it somehow didn't find the release PR to tag. (`✔ No release necessary for path: .`).

Can you add the head branch name of the merged release PR to help debug?

**Comment by paoll** [comment]
The head branch name is `hotfix/v3.1.0-bug` and the branch name from which the PR is opened is `release-please--branches--hotfix/v3.1.0-bug--components--pao-test-deployment`

Unfortunately I cannot provide any repository link directly as it's on private repositories, but if that helps I can try reproduce on public repository.

**Comment by chingor13** [comment]
This looks unrelated to the other linked issue and appears to be a problem with the way we handle custom pull request titles with regexes.
