### ISSUE TITLE
`group-pull-request-title-pattern` doesn't work with `linked-versions` plugin

### ISSUE THREAD

**Issue by phated** [googleapis/release-please#1456]
#### Environment details

  - OS: Linux / GHA
  - Node.js version: 12 (I think?)
  - npm version: N/A
  - `release-please` version: 13.16.5 (v3.2.5 of the action)

#### Steps to reproduce

  1. Create a "linked-versions" manifest config
  2. Add `"group-pull-request-title-pattern": "chore: Release ${component} ${version}"` to the config, like https://github.com/phated/grain/commit/9afc27357724112117cd6c4cb2a900198423a4c4
  3. Try to create a release. The `${component}` and `${version}` will be blank

I believe this issue is related to there being no "rootPackage" supplied for the Merge plugin. Ideally, we'd have access to the groupName as "component" and the linked version as "version".

**Comment by phated** [comment]
I was able to get the `version` to show up (it seemed caused by combining `linked-versions` and `node-workspace`, I'll open a separate issue for the incompatibility).

However, it now hits the log for `Bad pull request title: 'chore: Release Grain 0.5.0'` and bails without creating a release. Why would that happen?

**Comment by luxaritas** [comment]
> However, it now hits the log for Bad pull request title: 'chore: Release Grain 0.5.0' and bails without creating a release. Why would that happen?

I was just trying to use `group-pull-request-title-pattern` without `linked-versions` and I get the same error. Same even if I set `pull-request-title-pattern` as well. I originally set it to `chore(repo): Release next package versions`, thought it was the parens due to how the regex works in the PR title parsing, but even `chore: Release next package versions` has that error.

**Comment by luxaritas** [comment]
I think I've figured out what's going on, and it seems that there's two issues:
1) Manifest#buildReleases shells out to getStrategiesByPath passing in the config for the particular package - it doesn't have access to the group PR title pattern, and when buildRelease is called on the strategy, BaseStrategy uses pullRequestTitlePattern or MANIFEST_PULL_REQUEST_TITLE_PATTERN to build the PR title - so as currently implemented, you have to set _both_ group-pull-request-title-pattern and pull-request-title-pattern for it to be able to parse the title correctly.
2) PullRequestTitle.parse only returns a PullRequestTitle if the regex match has groups - so at least one of scope, component, version, or branch _has_ to be included and non-empty in the PR title
