### ISSUE TITLE
`linked-versions` and `node-workspace` plugins are incompatible 

### ISSUE THREAD

**Issue by phated** [googleapis/release-please#1457]
#### Environment details

  - OS: Linux / GHA
  - Node.js version: 12 (I think?)
  - npm version: N/A
  - `release-please` version: 13.16.5 (v3.2.5 of the action)

#### Steps to reproduce

  1. Create a "linked-versions" manifest config
  2. Add `"node-workspace"` plugin
  3. Try to create a release

Once the `node-workspace` plugin is run, it crashes (?) because it expects a version to exist on the PullRequest that `linked-versions` produced.

**Comment by chingor13** [comment]
Apologies on the slow response to this. This is going to probably require a non-trivial change to the plugins. The workspace plugin is updating files directly and not creating a new pull request for components that require a version bump. Then the linked versions plugin has no notion that another component was touched and that it's version needs to be linked to others.
