### ISSUE TITLE
Release Please often fails recently. Can you investigate the failures?

### ISSUE THREAD

**Issue by suztomo** [googleapis/release-please#1458]
For the Java BOM release last week, I found that following releases failed:

- https://github.com/googleapis/java-binary-authorization/issues/222
- https://github.com/googleapis/java-resource-settings/issues/178
- https://github.com/googleapis/java-language/issues/851
- https://github.com/googleapis/java-websecurityscanner/issues/695
- https://github.com/googleapis/java-run/issues/38
- https://github.com/googleapis/java-dlp/issues/889
- https://github.com/googleapis/java-api-gateway/issues/256
- https://github.com/googleapis/java-dataplex/issues/65
- https://github.com/googleapis/java-containeranalysis/issues/887
- https://github.com/googleapis/java-apigee-connect/issues/175
- https://github.com/googleapis/java-resourcemanager/issues/781
- https://github.com/googleapis/java-pubsub/issues/1147

# Symptom

The symptom is that Release Please successfully tags the repository and stops there:

<img width="949" alt="Screen Shot 2022-06-01 at 10 05 54 AM" src="https://user-images.githubusercontent.com/28604/171423921-8915cb47-49bd-45ed-abbc-ad3505ae73cf.png">

For now, I manually triggered the 12 jobs via Fusion (using `AUTORELEASE_PR=` environment variable and the tag as committish; thanks @Neenu1995 ).

I feel the failure rate is higher than the previous cycle. Would you investigate?

CC: @Neenu1995 @chingor13

**Comment by Neenu1995** [comment]
This has been the case for the last few bulk releases. But the issue seems to be with release-trigger and not release-please.

**Comment by chingor13** [comment]
As Neenu points out, this is an issue in release-trigger, not release-please

**Comment by suztomo** [comment]
Thank you. I subscribed the issue.
