### ISSUE TITLE
Update release PR on every change (instead of only changes that modify the changelog)

### ISSUE THREAD

**Issue by dnephin** [googleapis/release-please#1459]
**Is your feature request related to a problem? Please describe.**

We've been using release-please to manage our release and changelog. We've noticed that the release PR is only updated if the PR includes a commit with either `fix:` or `feat:`.

Sometimes we have PRs that add tests or fix problems with our release workflows. We'd like to include those commits in the release branch, but we don't want them to be included in the changelog (because our users aren't interested in those changes).

I wasn't able to find any option to make this happen, so I'm assuming it's not possible right now.

 **Describe the solution you'd like**

I'd like to be able to configure release-please so that all changes that go into main are included in the release PR, but only the categories that are "not hidden" are added to the changelog.

Either a top-level setting, or a new field in the `changelog-sections` would work fine for us.

 **Describe alternatives you've considered**

Not sure about any alternatives.

Thank you for your consideration!

**Comment by alioguzhan** [comment]
This is also almost a blocker for us. We would like to see every commit in the PR, regardless of the commit type. Here is the scenario:

1. Push a `feat: xxx` commit to the main branch.
2. Release-Please creates a PR for a new release. (it is a `feat` commit after all)
3. I push another `chore: xxx` commit to the `main` branch.
4. Release-please DOES NOT rebase its own PR branch. So my chore commit is not included in the upcoming release.

This can be verified by checking out to release-please branch in your machine. My `chore` commit won't be in the commit history. It would be something like this:

```
- chore(main): release 0.2.0
- feat: xxxxx
- ....
```

Yet it should be:
```
- chore(main): release 0.2.0
- chore(deps): xxxxx
- feat: xxxxx
- ....
```

**Comment by chingor13** [comment]
This seems like a reasonable option to add. We would likely want to implement it as an option for the manifest like `always-update` (default to `false`, the current behavior).

We intentionally implemented it to only push on changes to not overload our CI systems when we have many non-release-note-worthy commits.

**Comment by jimeh** [comment]
I'd love to see `always-update` option myself too. @chingor13 any update on this?

**Comment by tabfugnic** [comment]
@chingor13 Makes sense not to overload the CI systems. I could also be something like `keep-main-synced` and defaulting to `true` so that it doesn't change the release behavior outwardly, but does ensure that the Release PR is always up-to-date with `main`

Understand that's still a breaking change, but feels like a sensible default.

**Comment by adambiggs** [comment]
Any progress on this? We have Renovate configured to auto-merge safe dependency updates, and would like these updates to be included in release PRs. 

Currently workaround is to set a custom `changelog-types` that includes `chore` commits in the changelog, but something like `always-update` would fix the issue without adding any clutter our `CHANGELOG.md`.

Another option that would give more control might be something like `update-types`, where we could specify commit types that would trigger a PR rebase separately from those that trigger a changelog update:

```yaml
update-types:
  - feat
  - fix
  - chore
```

Would be even more powerful if you could include scope:

```yaml
update-types:
  - feat
  - fix
  - chore(deps)
```
