### ISSUE TITLE
Github Enterprise Support broken + fix

### ISSUE THREAD

**Issue by cbarrac** [googleapis/release-please#1473]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

1) Is this a client library issue or a product issue?
Product issue

2) Did someone already solve this?
Me!

3) Do you have a support contract?
No

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - OS: macOS 12.4
  - Node.js version: v18.3.0
  - npm version: 8.12.1
  - `release-please` version: 13.8.3

#### Steps to reproduce

  1. Set --api-url to an enterprise server
  2. Observe release-please using github.com
  3. Dump option in github library 'create' function (https://github.com/googleapis/release-please/blob/main/src/github.ts#L212), observe apiUrl and graphqlUrl options are not passed / are undefined.
  4. Update release-please.ts (https://github.com/googleapis/release-please/blob/main/src/bin/release-please.ts#L721-L725) to add in
 ```
apiUrl: argv.apiUrl,
graphqlUrl: argv.graphqlUrl,
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by khuedoan** [comment]
I'm experiencing the same problem, I've created a PR based on your findings.
