### ISSUE TITLE
Support tag name customization

### ISSUE THREAD

**Issue by mshrtsr** [googleapis/release-please#1495]
Hi there, and thanks for your great package.

 **Is your feature request related to a problem? Please describe.**

I plan to migrate my monorepo release workflow from `lerna version` to `release-please`.
By default, lerna creates tags like `${packageName}@${version}`. (version does not contain a `v`)
I want to keep tag name rules, but release-please doesn't have a tag name customization feature.

 **Describe the solution you'd like**

Add options about tag name customization.

 **Describe alternatives you've considered**

If I can create and use a custom release strategy that extends `node`, that's also good.

 **Additional context**

I find `separator` and `includeV` properties of the `TagName` class, but there is no way to pass value from users.

https://github.com/googleapis/release-please/blob/main/src/util/tag-name.ts

**Comment by mshrtsr** [comment]
@chingor13 
Thank you for your response!

I was running release-please with manifest config, and I succeeded in changing my tag name using the options you suggested.

By the way, I could not find `include-v-in-tag` and `tag-separator` options on a [manifest config] document.
Can I create a PR for this?

**Comment by andreafspeziale** [comment]
Hello everyone and thanks for your hard work! I've been using https://www.npmjs.com/package/standard-version which now is advising `release-please`, it would be nice to have some easy and intuitive option like https://github.com/conventional-changelog/standard-version/blob/master/README.md#prefix-tags 🙏

**Comment by chingor13** [comment]
> By the way, I could not find `include-v-in-tag` and `tag-separator` options on a [manifest config](https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md) document.
> Can I create a PR for this?

Sorry, missed this question -- yes we'd love contributions from the community. We also recently added a [JSON Schema definition for the config files](https://github.com/googleapis/release-please/blob/main/schemas/config.json) that also include descriptions of the various options.

**Comment by mshrtsr** [comment]
@chingor13 
Sorry for the late response.

I just found you added the link of JSON Schema in https://github.com/googleapis/release-please/commit/8a7bfc165755cec97cc9a3baa39ccd21e719644c.
It looks better solution than adding a description of each option to the document.

Thank you for responding!
