### ISSUE TITLE
Can I configure the pattern of release tags?

### ISSUE THREAD

**Issue by mrchrmn** [googleapis/release-please#1497]
Is it possible to change the naming pattern of the tags generated by each release? I would prefer the tag to start with the version number in order for it to be recognised as a semantic version in our pipeline. 

Unfortunately I haven't found a way to configure it through the settings file. In the code I see there are options for "v or no v" and the separator but that seems to be it. 

We use the release-please Github Action, by the way, not the CLI.

Thanks for reading this :)

**Comment by chingor13** [comment]
Are you looking for just the version number? Or an actual different pattern (e.g. `1.2.3 component-name`)?

For skipping a component name, there should be an `include-component-in-tag` manifest option.
