### ISSUE TITLE
Bumping dotnet csproj files

### ISSUE THREAD

**Issue by patoncrispy** [googleapis/release-please#1514]
Hi there. I'm here because standard-version is deprecated. 

I have a TypeScript and .NET monorepo. I can see how I can use release-please to manage Node-based projects, but I can't quite figure out how to work with .NET projects. All I'm interested in doing is bumping the Version property in a csproj file. I can see there was an attempt to add support for .NET in #549, but there is also a .NET updater in the code base and there aren't any instructions on how to use that.

Any guidance someone can offer would be greatly appreciated.

**Comment by patoncrispy** [comment]
OK great I'll give that a go! A `dotnet` strategy would obviously be ideal though. :) Thanks.

**Comment by patoncrispy** [comment]
Hey @chingor13 I tried using the `extra-files` with a `simple` strategy as you suggested, but the file isn't being touched. I [searched the repo](https://github.com/googleapis/release-please/search?q=extraFiles) and it seems the `extraFiles` property is only being used in `java` strategies. Is that correct?

**Comment by chingor13** [comment]
The simple strategy should inherit from the base strategy and should [support generic xml updates](https://github.com/googleapis/release-please/blob/002231acfa49b3859a7eaee184a2b520eb6611d3/src/strategies/base.ts#L339-L344)

To use the generic-xml updaters, make sure you're using the `type: xml` in the manifest config. Example:

```json
{
  "packages": {
    ".": {
      "component": "foo",
      "extra-files": [
        { "type": "xml", "path": "src/foo.csproj", "xpath": "//path/to/field" }
      ]
    }
  }
}
```

**Comment by patoncrispy** [comment]
Sorry I should have closed this. I figured out I had my paths all wrong! I didn't realise that `packages[].package.extra-files[].path` was relative to the package path.
