### ISSUE TITLE
manifest release creates wrong tags for packages when custom pr title uses version

### ISSUE THREAD

**Issue by daton89** [googleapis/release-please#1536]
Using manifest release with ` "group-pull-request-title-pattern"` leads to wrong tags in the github release.

Given this configuration and manifest:
```
// config
{
  "group-pull-request-title-pattern": "chore${scope}: release${component} ${version}",
  "packages": {
    ".": {},
    "apps/app1": {},
    "apps/app2": {},
    "apps/app3": {},
    "libs/lib1": {}
  }
```

```
// manifest
{
    ".": "1.34.0",
    "apps/app1": "7.91.0",
    "apps/app2": "1.31.0",
    "apps/app3": "1.0.11",
    "libs/lib1": "4.91.0"
}

```

The tags for all the apps and libs in the github release are created with app1-v1.34.0 app2-v1.34 ... instead of app1-v7.91.0 app2-v1.31.0 ...

Therefore release-please doesn't handle the next release correctly because it will take old commits into consideration, leading to several other errors

#### Environment details

  - `release-please` version: 'google-github-actions/release-please-action@v3' (SHA:63edea1103e00b7d8a5c96cbdc97cc9ebf7c037c)

**Comment by chingor13** [comment]
Thanks, this seems to be the same issue as #1527
