### ISSUE TITLE
For Cloud SDK Java, show the corresponding Libraries BOM version in release notes

### ISSUE THREAD

**Issue by bcoe** [googleapis/release-please#1539]
This feature request is from @suztomo, for the CHANGELOG/GitHub release notes of the Java SDK.

**Comment by chingor13** [comment]
@suztomo Can you elaborate this feature request?

**Comment by suztomo** [comment]
# Background

A Java SDK release is a release of the Libraries BOM. We recommend Java users to use the Libraries BOM https://cloud.google.com/java/docs/bom. A release of the Libraries BOM include the compatible, latest versions of the Google Cloud Java libraries. 

Note that a Libraries BOM release always occurs after the included libraries are released to Maven Central.

# Problem

Library users who find a library release note cannot tell which Libraries BOM they should use to use the new features or bug fixes. For example, https://github.com/googleapis/java-spanner/releases/tag/v6.25.7 does not tell the Libraries BOM version that has google-cloud-spanner 6.25.7.

I think Release Please is best positioned to solve this problem, by adding the BOM version information to existing release notes of the client libraries.

**Comment by chingor13** [comment]
> by adding the BOM version information to existing release notes of the client libraries.

I'm not sure how release-please is can do this -- the libraries-bom version that includes the newly released library does not yet exist

**Comment by suztomo** [comment]
I also think current implementation of release please operation lifecycle does not fit to solve this problem. (Let’s not stick to the “solution” above. It's just my abstract idea)

**Comment by chingor13** [comment]
Release Please does not keep updating the GitHub releases after they have been created. Other automation could update the notes after the libraries-bom has published.

Closing as there's not much we can do here within release-please.
