### ISSUE TITLE
[java] erroneously opened a new snapshot release PR after merging a snapshot PR

### ISSUE THREAD

**Issue by chingor13** [googleapis/release-please#1540]
[A snapshot bump PR](https://github.com/googleapis/java-bigtable/pull/1321) was merged 2022-07-26 1:50pm PST. Release-Please then opened a [new snapshot bump PR](https://github.com/googleapis/java-bigtable/pull/1325) which was then re-used to become a new release. The caused the release to fail to be tagged because it was labeled incorrectly.

Somewhat related: #1352

**Comment by kolea2** [comment]
Some extra info for debugging - a new snapshot PR was still opened up after the release PR (labeled as snapshot) was merged https://github.com/googleapis/java-bigtable/pull/1331

**Comment by tmatsuo** [comment]
Do we have a repro, or hypothesis of repro?

**Comment by chingor13** [comment]
This seems to be exceedingly rare. closing until it happens again and we have logs
