### ISSUE TITLE
[java/maven] Make creation of snapshot releases optional

### ISSUE THREAD

**Issue by richardtippl-ext90046** [googleapis/release-please#1547]
**Is your feature request related to a problem? Please describe.**

Current `java`/`maven` strategy forces the opinion that java releases should be always followed by a SNAPSHOT release. Not every application follows this pattern. I would like to "just" create a release by incrementing versions without snapshots.

This is how every other strategy behaves, I think there should be a way to get the `maven` strategy to behave in the same way.

 **Describe the solution you'd like**

I don't know if release-please provides a way to pass additional config options to strategies, but it would be ideal if I could disable the snapshotting feature while keeping the rest of the `maven` strategy.

 **Describe alternatives you've considered**

One alternative is by using the `simple` strategy and list POM files in the `extraFiles` section as such:

```yaml
releaseType: simple
extraFiles:
  - type: pom
    path: pom.xml
```

However release-please doesn't seem to support filename globbing, as such multi-module maven projects with multiple POM files would require adding file definition for each file instead of simply setting `**/pom.xml`.

I'm not sure which one of the 2 possible solutions is harder to implement.

**Comment by mdvorak** [comment]
I see two ways to implement this:
a) add yet another option, which would have to be then propagated to action and bot options - I'm not fond of that
b) add another variant of maven strategy, without snapshots, something like `maven-simple`

Adding support for globs in `extraFiles` would be probably best solution, but also pretty complex.

**Comment by chingor13** [comment]
I think we should be able to do the `skipSnapshot` option and potentially support globs in `extraFiles`.

> a) add yet another option, which would have to be then propagated to action and bot options - I'm not fond of that

I'm ok with not propagating all options to the app and actions. We should perhaps push folks towards using the manifest configs (even for single library repositories) as it improves the determination what the latest release version/SHA is (reduced API calls and it's more explicit).

> support globs in `extraFiles`

This is pretty complex as I'm not aware of an existing glob search function in the GitHub API
