### ISSUE TITLE
Allow titleCase to be configured for CHANGELOG items

### ISSUE THREAD

**Issue by bcoe** [googleapis/release-please#1548]
The commit messages from many different stakeholders feed into cloud.google.com/release-notes, this can lead to variations in the usage of title case (vs., lower case commit messages), see:

![Screen Shot 2022-08-04 at 11 52 33 AM](https://user-images.githubusercontent.com/194609/182891743-f9f8de8e-f410-49cc-9946-92d998a9d21d.png)

It would be nice to be able to turn on title casing as a config option, for consistency.

**Comment by chingor13** [comment]
In offline discussions, we determined this is going to be infeasibly difficult due to edge cases.
