### ISSUE TITLE
Is there a way to merge/finalize the PR from the cli?

### ISSUE THREAD

**Issue by maximedupre** [googleapis/release-please#1549]
Maybe I don't totally understand the whole process, but it seems like it would be handy to have a flag that could be passed to `release-please release-pr` that would merge the PR. 

This way, everything could be done from the command line, instead of having to go on Github to manually merge the PR.

This could allow chaining all the commands for an "end to end release": `release-please release-pr --merge && release-please github-release && npm publish`

If this makes sense, perhaps this could be labelled as a "feature request" instead.

**Comment by chingor13** [comment]
Merging the PR is outside the scope of this tool. For 99% of users, you will want to review/control when you are making a release.

If you do want to automated it, there are many tools already available to handle merging a PR. Example: you could set up another GitHub action workflow to automatically approve and merge a PR using the `gh` official command line tool.
