### ISSUE TITLE
Version occasionally reverting to initial versions

### ISSUE THREAD

**Issue by chingor13** [googleapis/release-please#1567]
It appears that when we are using `Manifest.fromConfig()`, our search for the latest release version can return invalid results.

1. We grab the latest X commits on the target branch
2. We look for a merged release pull request
3. We fallback to latest GitHub releases that have a SHA matching a recent commit
4. We fallback to latest GitHub tags that have a SHA matching a recent commit

If step 1 fails (GraphQL), then we have an empty commit set, so step 2, 3, and 4 all fail. Thus release-please assumes we've never created releases before and propose a new release with the initial default version.

Example: https://github.com/googleapis/java-storage/pull/1564 (look at the initial proposed PR).

**Comment by chingor13** [comment]
If step 1 fails, we probably want to error out in this case.

**Comment by suztomo** [comment]
This happened to https://github.com/googleapis/java-notification/pull/643
