### ISSUE TITLE
React Native Expo support (or custom Strategy/Parser path configuration)

### ISSUE THREAD

**Issue by soulfresh** [googleapis/release-please#1568]
**Is your feature request related to a problem? Please describe.**
I'd like to use `release-please` to release React Native Expo projects. These projects will require a custom Strategy and Parser because they store version information in a file called `app.json`. The version numbers in `app.json` include a non-semver versioning pattern for the Android version number but semver for the iOS and web versions in the same file. Reading through the docs and the code, it doesn't seem possible to provide a path to my own custom Strategy and Parser files.  

 **Describe the solution you'd like**
Either of:
- My preferred solution would be to allow configuring `release-please` with the path to my own custom Strategy/Parser files. 
- I'm also happy to submit a PR with a React Native Expo Strategy if you're open to that.

 **Describe alternatives you've considered**
The current `release-please` API will require me to update the `app.json` version numbers in a separate CI process after the release PR is merged. This means that there will always be a second commit right after the release commit and the releases don't accurately describe the state of the release. I could instead amend the PR commit with the updated `app.json` but I'm hesitant to amend git history in an automated process.

I'm open to any other options for achieving this with the existing API.

**Comment by chingor13** [comment]
Can you given an example of the non-semver version pattern and perhaps an example of the app.json? This library relies on semantic versioning and conventional commit messages, so non-conforming version number could be a non-starter.

**Comment by soulfresh** [comment]
The non-semver value used for Android builds  is a simple incrementing value ( [versionCode](https://docs.expo.dev/versions/latest/config/app/#versioncode) ). There is a plugin for [standard-version](https://github.com/expo-community/standard-version-expo) that is used in many projects that actually bases the version code on a combination of the semver version and the Expo SDK version: `[SDK][MAJOR][MINOR][PATCH]` (so 1.2.3 would become XX00102003). 

Here's an example [app.json](https://github.com/expo-community/standard-version-expo/blob/main/test/stub.ts). Notice the `android.versionCode` and how it relates to the `version` and `sdkVersion`.

Here's the Android documentation on [versionCode](https://developer.android.com/studio/publish/versioning.html).

The reason I proposed allowing a configuration option to load custom Strategy/Parser plugins was so I could keep the Android versioning logic outside of this repo. 

Totally understand if this is not something you want to support.

**Comment by chingor13** [comment]
Thinking about this more -- is this something that is unique to the `app.json` file (or is this formatting used across the entire codebase)? If it's unique to that `app.json` file, we could write a custom `Updater` class for that knows how to format the version string in that file.

**Comment by soulfresh** [comment]
Yes, it's specific to the `app.json` file. All other version numbers are semver.

**Comment by chingor13** [comment]
Ok, this can be accomplished with a new Strategy for react native expo and a new Updater class for updating this file with the version format.

**Comment by soulfresh** [comment]
Sounds good. I think I'll have time in the next couple weeks to give it a try.
