### ISSUE TITLE
Running at night

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/release-please#158]
There are always gonna be a few releases we sit on for a bit.  It seems like something is happening in a nightly cron somehow that's triggering the tool to get run:
![image](https://user-images.githubusercontent.com/534619/58187959-b1a1e480-7c6c-11e9-931b-3e0f0bb6d820.png)

It would be awesome if it only ran after things landed into master :)

**Comment by bcoe** [comment]
@JustinBeckwith I think the solution to the spam issues that you've brought up would be to check whether the CHANGELOG content has changed since a PR was last opened, and to short-circuit if it hasn't -- does this sound reasonable?
