### ISSUE TITLE
Support $schema property in manifest config schema

### ISSUE THREAD

**Issue by luxaritas** [googleapis/release-please#1582]
**Is your feature request related to a problem? Please describe.**
When supplying a schema key in json files, editors can pick up on for intellisense, validation, etc. Currently, adding this key to release-please-config.json raises a validation error saying that $schema isn't a valid key (a bit ironic!).

 **Describe the solution you'd like**
It would be great to add `$schema` as a valid (URI) property. It's a simple change I'm happy to PR as long as there's no concerns.

**Comment by chingor13** [comment]
Yes, that would be a great addition.

For posterity, that field is defined: https://json-schema.org/draft/2020-12/json-schema-core.html#name-the-schema-keyword
