### ISSUE TITLE
strange interaction with `autorelease: snooze` and the GitHub app

### ISSUE THREAD

**Issue by chingor13** [googleapis/release-please#1583]
I think we're seeing weirdness with the snooze functionality because the GitHub app is marking the pull request as `autorelease: closed` when the PR is closed (even with snoozing).

[Merged release PR without `autorelease: pending` label](https://github.com/terraform-google-modules/terraform-google-project-factory/pull/737)

[Closed, snoozed PR](https://github.com/terraform-google-modules/terraform-google-project-factory/pull/713)

```
updated code for 741, but update requested for 713
```

Then it the library tries to reopen the snoozed PR and there is an existing PR open for that branch so validation fails

```
Validation Failed: {"resource":"PullRequest","code":"custom","field":"state","message":"state cannot be changed. There is already an open pull request from release-please--branches--master to master."}
```

**Comment by SurferJeffAtGoogle** [comment]
This issue will fall out of SLO in 6 days.
