### ISSUE TITLE
plugin node_workspace doesn't work with pnpm?

### ISSUE THREAD

**Issue by agufagit** [googleapis/release-please#1587]
I'm trying to update local deps, monorepo is pnpm workspace

i tried to use plugin node_workspace, and got error:
```
Unsupported URL Type "workspace:": workspace:^0.2.0
```

I see that there is no way to write a custom manifest plugin

I did write a script, which's just simply 'cd' into each package folder, regex match workspace deps in package.json, and run 'pnpm update --workspace @scope/package1 @scope/package2'.  The reason to run 'pnpm update' is to update pnpm-lock.yaml file also, for pnpm --frozen-lock option.

I'm not sure if this script fits your plugin system, if you want this, I can contribute

**Comment by chingor13** [comment]
Related: #1098

**Comment by agufagit** [comment]
I'll do it in my spare time, so this means I have to manually modify pnpm-lock.yaml file right?

**Comment by chingor13** [comment]
> modify pnpm-lock.yaml file right?

I'm not sure exactly how a pnpm workspace works, but we do have updaters already for [generic yaml files](https://github.com/googleapis/release-please/blob/main/src/updaters/generic-yaml.ts) and workspace plugins can add additional files to update.

**Comment by oneton** [comment]
I've run into the same problem. My Github action failed after logging "Building list of all packages". I must admit I did not run a debugger, but by analysing the code I found the following:
- NodeWorkspace->buildAllPackages (node-workspace.ts) is called from the WorkspacePlugin
- This method creates instances of Package (defined in the same file), which extends Package from @lerna/package
- The constructor for @lerna/package calls resolve() from downstream dependency npm-package-arg
- npm-package-arg doesn't recognise the workspace: protocol

It seems lerna is working on pnpm support as we speak, which will most likely resolve the issue.
https://github.com/lerna/lerna/pull/3284

**Comment by agufagit** [comment]
awesome, I'll just wait then

**Comment by oneton** [comment]
It might be useful to keep this issue open. Updating the lerna dependencies would be the minimum change required to address this once the lerna changes have been completed.

**Comment by agufagit** [comment]
ok

**Comment by freddy38510** [comment]
Hello guys,

I just noticed that the [commit](https://github.com/lerna/lerna/pull/3284) has been merged and [lerna v5.5.0](https://github.com/lerna/lerna/releases/tag/v5.5.0)  supports pnpm.

**Comment by re-taro** [comment]
Hello, I have the same issue.

I would assume that [this PR](https://github.com/googleapis/release-please/pull/1449) will be resolved once it is merged, but what do you think?

**Comment by mpetrunic** [comment]
@chingor13 Merging #1449 will add support for this^^

**Comment by nahsi** [comment]
Still doesn't work with pnpm.
#1819 added yarn support.
