### ISSUE TITLE
How fix a release that went out as major bump

### ISSUE THREAD

**Issue by sir-captainmorgan21** [googleapis/release-please#1594]
Hi! We are maintaining a mono repo and are using the manifest to manage our releases. We accidentally pushed out a few packages as major release versions when they should have been patches. We ran the command to generate the release pr AND merged that release pr, so the releases are out and published.

What is the best way to essentially revert those versions and release the proper version number?

**Comment by chingor13** [comment]
Assuming you did not push to package managers, I would probably:
* revert the release PR
* Delete the releases/tags created by that PR
* Use the BEGIN_COMMIT_OVERRIDE feature to rewrite the commit message to not be a breaking change or use a new Release-As commit to fix the version.

If you did publish to package managers, you may be out of luck if you cannot yank releases.

**Comment by sir-captainmorgan21** [comment]
@chingor13 awesome. Thank you. Yanking published packages is no issue. Will try this out
