### ISSUE TITLE
How to fix release notes

### ISSUE THREAD

**Issue by VividLemon** [googleapis/release-please#1608]
Thanks for stopping by to ask us a question! Please make sure to include:
- What you're trying to do
Trying to override the release notes in the release-please PR
- What code you've already tried
In relation to https://github.com/googleapis/release-please#how-can-i-fix-release-notes
What I tried was first, to override the message in the ORIGINAL MERGED PR (**NOT** the release please pr, but the actual change)
I then reran the ci suite, the release please pr had no change. In this instance, I had triggered a rerun by merging a new PR. Which had no affect, beyond adding the new content in the second PR

Then, I tried maybe copying and pasting this code 
```
BEGIN_COMMIT_OVERRIDE
feat: add ability to override merged commit message

fix: another message
chore: a third message
END_COMMIT_OVERRIDE
```
directly into the release-please PR. 
Which had no affect. In this instance I had reran the test suite by using the Github 
![image](https://user-images.githubusercontent.com/31498096/187290741-3322e964-a84e-4c00-94a9-120e2a210a4e.png)
button
- Any error messages you're getting
None

Putting the commit override in the original PR and in the release-please (unmerged) pr both had no affect. How can I achieve https://github.com/googleapis/release-please#how-can-i-fix-release-notes ? Tyvm

**Comment by chingor13** [comment]
How are you running release-please? It's usually not run as status checks on pull requests. Generally, it's run via `push` events to the default branch either via GitHub action workflows (listening to push events) or via an installed GitHub app.

For GitHub actions, you'll want to find the workflow that ran and re-run that one. For the GitHub app, we have a `release-please:force-run` label that can be applied to the pull request.

**Comment by VividLemon** [comment]
> Generally, it's run via `push` events to the default branch

This is true, but it would have been reran when `I had triggered a rerun by merging a new PR` during the push process before merging. Yet, on push, on merge, on rerun of job via github, all of saw no change to the release-please PR. You can view the lib https://github.com/cdmoro/bootstrap-vue-3 and this relevant workflow https://github.com/cdmoro/bootstrap-vue-3/blob/main/.github/workflows/release-main.yaml

**Comment by chingor13** [comment]
Can you link the PR where you used the commit override? I'm not seeing it so I'm not able to debug further.

**Comment by VividLemon** [comment]
Truth be told, I deleted them after my final PR of the day and before I made this issue posting. Perhaps you could show me a better example instead? Does the override message need to be from the author? Or can a maintainer also override? Perhaps that has something to do with it?

**Comment by VividLemon** [comment]
I figured out the issue. I was posting the changes as a `comment` rather then editting the PR `body`
