### ISSUE TITLE
Requesting Clarification Regarding Deprecated Commands

### ISSUE THREAD

**Issue by yanok9812** [googleapis/release-please#1610]
From this [doc](https://github.com/googleapis/release-please/blob/main/docs/cli.md#create-a-manifest-pull-request-deprecated), I know that the release-please CLI commands `manifest` and `manifest-pr` are deprecated. However, is supplying those commands to github action deprecated too? For example, is the below usage of release-please github action deprecated? I guess it's not deprecated because it appeared in this [doc](https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md#using-with-github-actions-and-lerna). Could anyone clarify?

Github Action Usage example
```
.......
steps:
  - uses: google-github-actions/release-please-action@v3
    with:
      command: manifest
.......
```

BTW, I'm trying to implement automatic release workflow in a monorepo using release-please.

**Comment by chingor13** [comment]
The CLI options in the binary provided by this library are separate from the inputs provided by the action. The CLI has deprecated those commands, but the action is not planning to at this time.
