### ISSUE TITLE
release-please bootstrap with --dry-run executes live operations

### ISSUE THREAD

**Issue by jadecristal** [googleapis/release-please#1617]
#### Problem:

When running with `--dry-run`, the `release-please bootstrap` command creates a real commit with new files and opens a real PR using the GitHub API, in violation of the defined behavior from the [CLI documentation for global flags](https://github.com/googleapis/release-please/blob/main/docs/cli.md#global-options).

#### Expected behavior:

Using the `--dry-run` flag should cause `release-please` to solely indicate what **would** be done, _not_ actually do it.

#### Sample:

```shell
$release-please --token=REDACTED_TOKEN --dry-run --repo-url=USERNAME/REDACTED_REPO bootstrap
✔ Starting GitHub PR workflow...
✔ Successfully found branch HEAD sha "REDACTED_SHA".
✔ Successfully created branch at https://api.github.com/repos/USERNAME/REDACTED_REPO/git/refs/heads/release-please/bootstrap/default
✔ Got the latest commit tree
✔ Successfully created a tree with the desired changes with SHA REDACTED_SHA
✔ Successfully created commit. See commit at https://api.github.com/repos/USERNAME/REDACTED_REPO/git/commits/REDACTED_SHA
✔ Updating reference heads/release-please/bootstrap/default to REDACTED_SHA
✔ Successfully updated reference release-please/bootstrap/default to REDACTED_SHA
✔ Successfully opened pull request available at url: https://api.github.com/repos/USERNAME/REDACTED_REPO/pulls/1.
✔ Successfully opened pull request: 1.
{
  headBranchName: 'REDACTED_REPO/bootstrap/default',
  baseBranchName: 'main',
  number: 1,
  title: 'chore: bootstrap releases for path: .',
  body: 'Configuring release-please for path: .',
  files: [],
  labels: []
}
```

#### Environment details

  - OS: MacOS 12.5.1
  - Node.js version: 16.17.0
  - npm version: 8.15.0
  - `release-please` version: 14.2.4

#### Steps to reproduce

  1. Run the `release-please` tool in a new repository containing valid content with the `--token` and `--dry-run` and `--repo-url` set to valid values, and specify the `bootstrap` command. See the above section "Example" for sample input/output of running this command.
  2. Instead of specifying what files, commit(s), and/or PR would be created, `release-please` interacts with the GitHub API to actually create a PR after creating files and a commit.

**Comment by chingor13** [comment]
This is an oversight in the implementation of the `bootstrap` command.
