### ISSUE TITLE
Enterprise Server - Connection to Server

### ISSUE THREAD

**Issue by Jonas-Alber** [googleapis/release-please#1618]
Thanks for stopping by to ask us a question! Please make sure to include:
- What you're trying to do
Hello, I am trying to log in to our company enterprise server using release-please. Thereby release-please uses as url: myserver.com/repos/username/repo_name
But the repos on the Server are accessed differently: myserver.com/username/repo_name
- What code you've already tried
Here I give the request using the following command:
release-please bootstrap --token=$GITHUB_TOKEN --api-url=https://myserver.com --graphql-url=https://myserver.com --repo-url=username/project_name --release-type=terraform-module
Is there any way to stop adding the /repos/ to the URL?
- Any error messages you're getting

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**Comment by chingor13** [comment]
> Is there any way to stop adding the /repos/ to the URL?

This is built into the endpoints for octokit. We can only [configure the `baseUrl`](https://github.com/octokit/octokit.js/#constructor-options). Is your company using some kind of rewriting proxy? As far as I know, GitHub enterprise URLs use the same path structure as GitHub's API.
