### ISSUE TITLE
Where does release-please pick up the latest version

### ISSUE THREAD

**Issue by shinokada** [googleapis/release-please#1635]
I have a NPM version of 0.2.2 in package.json.
When I used release-please, it creates release 0.2.0.

Where does release-please pick up the version? Is it from package.json or Changelog.md?

**Comment by chingor13** [comment]
If you are using a manifest, it parses the latest released version from the `.release-please-manifest.json` file. It then looks up the SHA for that release from GitHub releases or tags.

If you are not using a manifest, it looks at merged release-please PRs (parses the pull request for info), GitHub releases, and GitHub tags and tried to determine the highest version that is on your target branch.

In either case, if it's proposing the wrong version, you are likely missing a GitHub release or tag for your latest release (or it's pointing to a SHA that is not on your target branch).
