### ISSUE TITLE
Provide an easy way to configure https proxy

### ISSUE THREAD

**Issue by julianiag** [googleapis/release-please#1636]
**Is your feature request related to a problem? Please describe.**
When using the `release-please` in a self-hosted runner that is behind a proxy, we would like an easy way to configure the https proxy with default option.

 **Describe the solution you'd like**
In `github.ts`, update the `create` method to something like
```
 // import {HttpsProxyAgent} from 'https-proxy-agent';
 static async create(options: GitHubCreateOptions): Promise<GitHub> {
    const apiUrl = options.apiUrl ?? GH_API_URL;
    const graphqlUrl = options.graphqlUrl ?? GH_GRAPHQL_URL;
    const releasePleaseVersion = require('../../package.json').version;
    const apis = options.octokitAPIs ?? {
      octokit: new Octokit({
        baseUrl: apiUrl,
        auth: options.token,
        request: options.defaultHttpsProxy
          ? {
              agent: new HttpsProxyAgent({
                host: options.defaultHttpsProxy.host,
                port: options.defaultHttpsProxy.port,
              }),
            }
          : undefined,
      }),
//... rest of code
```
 **Additional context**
I would like to make the PR if we agree the solution.

**Comment by chingor13** [comment]
This seems reasonable to feature to add.

I might prefer the option added to `GitHubCreateOptions` be just `proxy` or `httpsProxy` (dropping "default").

Another option is to make the underlying request.agent configurable. Ideally, we'd like to minimize dependencies (it looks like `https-proxy-agent` is another third-party dependency). If we can make the `GitHubCreateOption` add an optional `requestAgent` option that's an interface for [`http.Agent`](https://nodejs.org/api/http.html#http_class_http_agent) (this seems like a built-in interface), then the caller could inject their own implementation (and declare/require the `https-proxy-agent` themselves). We won't be able to skip the dependency, however, if we need the CLI to provide this proxy configuration.

**Comment by julianiag** [comment]
Thanks @chingor13 for the feedback. I have submitted a #1639 based on your feedback point 1. Please let me know your feedback. This implementation is inspired by https://github.com/semantic-release/github (see the source code https://github.com/semantic-release/github/blob/8cb77a1365e07f8852c77164ca7a5a23715adcf1/lib/get-client.js#L36) which provides an easy way for user to configure proxy.

For point 2. I understand that as maintainers, we always prefer to less dependencies so it is easier for us to maintain the OSS. However, it would be nicer if we could also provide an easier and nicer Deverloper/User experience for users who use this lib.

What do you think 😄 ?
