### ISSUE TITLE
Release Please marked non-snapshot pull request as "autorelease: snapshot"

### ISSUE THREAD

**Issue by suztomo** [googleapis/release-please#1641]
Somehow this non-snapshot pull request was marked as "autorelease: snapshot" and thus I had to manually edit the labels to make the release.

https://github.com/googleapis/java-cloud-bom/pull/5124#issuecomment-1251115440

<img width="691" alt="Screen Shot 2022-09-19 at 10 38 14 AM" src="https://user-images.githubusercontent.com/28604/191072505-5bcaa075-771a-48b0-b7e5-6b6732032ea9.png">

**Comment by chingor13** [comment]
I think this is a race condition from a couple of bot attempts running simultaneously.
