### ISSUE TITLE
HTML tags in commit messages can break PR message parsing, causing missing package releases

### ISSUE THREAD

**Issue by apaleslimghost** [googleapis/release-please#1659]
#### Steps to reproduce

  1. Commit something in a repo that uses manifest releases with an unclosed HTML tag in the commit message 
  2. Merge the release PR
  3. Wait for `release-please` to create releases
  4. Observe that some of the packages haven't been released

This is (i think) because the HTML parsing step in [`extractMultipleReleases`](https://github.com/googleapis/release-please/blob/d0fbd90659f14b975ba56570712b8a4b1ed59e25/src/util/pull-request-body.ts#L121) sees the later `<details>` tags as nested inside the unclosed tag in the commit message, and so it's not returned by `root.getElementsByTagName`. [RunKit that demonstrates the issue](https://runkit.com/quarterto/63331c334561bc0009a469ac)

I think the correct fix would be to HTML-encode the commit messages when generating the PR message in the first place.

**Comment by chingor13** [comment]
So the tag functionality is likely failing on that release PR. As a workaround, if you edit the `<picture>` tag to `&lt;picture&gt;`, and re-run it, does it work?

#1661 would generate the release notes with escaped tags. We probably can't fix the parsing after the fact though.

**Comment by apaleslimghost** [comment]
i ended up creating a manual tag for the one package that it skipped, and adding a `commitlint` rule to prevent us committing tags again. the PR looks good, thanks!
