### ISSUE TITLE
`cargo-workspace` plugin cannot handle dependency cycles in dev-dependencies

### ISSUE THREAD

**Issue by thomaseizinger** [googleapis/release-please#1662]
Thanks for stopping by to let us know something could be better!

~**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.~

1) Is this a client library issue or a product issue?
~This is the client library for . We will only be able to assist with issues that pertain to the behaviors of this library. If the issue you're experiencing is due to the behavior of the product itself, please visit the [ Support page]() to reach the most relevant engineers.~

It is a library issue.

2) Did someone already solve this?
  - Search the issues already opened: https://github.com/googleapis/release-please/issues: **Couldn't find anything.**
  - Search the issues on our "catch-all" repository: https://github.com/googleapis/google-cloud-node: **Couldn't find anything.**
  - Search or ask on StackOverflow (engineers monitor these tags): http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js: **I don't think this applies here.**

3) Do you have a support contract?
~Please create an issue in the [support console](https://cloud.google.com/support/) to ensure a timely response.~

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - OS: Manjaro Linux
  - Node.js version: 18.8.0
  - npm version: 8.19.1
  - `release-please` version: 14.7.2

#### Steps to reproduce

  1. Have a cargo workspace that has dependency cycles with _dev_ dependencies.
  2. Try to use the cargo-workspace plugin of release-please.

Cargo supports dependency cycles in the form of A -dep-> B -dev-dep-> A. In other words, I can have a crate A that depends on B but B can depend on A again in its `dev-dependencies`. `release-please` doesn't seem to allow this which I think is an unnecessary restriction. Version bumping of `dev-dependencies` should not impact the version of a package so perhaps `dev-dependencies` should just be ignored here: https://github.com/googleapis/release-please/blob/main/src/updaters/rust/common.ts#L71

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by chingor13** [comment]
Sorry, for the super late response to this one.

It looks like there's 2 issues:
1. release-please throws an error on circular dependencies which could be valid
2. you'd like an option for a dev-dependency version bump not forcing a patch bump

**Comment by thomaseizinger** [comment]
> Sorry, for the super late response to this one.
> 
> It looks like there's 2 issues:
> 
>     1. release-please throws an error on circular dependencies which could be valid
> 
>     2. you'd like an option for a dev-dependency version bump not forcing a patch bump

Correct. We've resolved (1) on our end by getting rid of circular dependencies. That had other positive impacts.

I think (2) is still an issue. Bumping a dev-dependency should not warrant a version bump because it is not user facing.

**Comment by EqualMa** [comment]
I found a workaround by renaming dependencies:

```toml
[dev-dependencies]
my-lib-dev = { path = "../my-lib", package = "my-lib" }
```

Then you can `extern crate my_lib_dev as my_lib` so that you can use `::my_lib` other than `::my_lib_dev`.

The `cargo-workspace` plugin is not smart enough to find out `my-lib-dev` is actually `my-lib`. Thus, cycle dependencies won't be reported.
