### ISSUE TITLE
Release Please not bumping versions within a package

### ISSUE THREAD

**Issue by ddixit14** [googleapis/release-please#1676]
Release Please is not doing annotation based version bumps within a package in the java [monorepo](https://github.com/googleapis/google-cloud-java/pull/8444). I highly suspect that we need to declare all the artifacts we need to bump in the config file. 
![image](https://user-images.githubusercontent.com/90280028/193627432-444dfabc-b43f-4f69-bbb0-c20881f778df.png)

**Comment by chingor13** [comment]
It looks like somehow the `maven-workspace` is interfering with normal version updates. When debugging, the `java-accessapproval/pom.xml` is being marked as a `PomXml` updater (which doesn't know about the annotations). This updater should probably be a `CompositeUpdater` that has both a `PomXml` updater (from any workspace bumps) and a `JavaUpdate` (from the `java-yoshi` strategy).

**Comment by chingor13** [comment]
The maven-workspace plugin is throwing away any existing changes to the pom.xml: https://github.com/googleapis/release-please/blob/df627b3bfc61cce25bcdc54ef7c282019479754a/src/plugins/maven-workspace.ts#L221
