### ISSUE TITLE
Manually tag Firestore Go v1.7.0

### ISSUE THREAD

**Issue by telpirion** [googleapis/release-please#1684]
The Firestore Go client library v1.7.0 is stuck and cannot be released. It seems like this release will need to be manually tagged.

PRs:
+ https://github.com/googleapis/google-cloud-go/pull/5339
+ https://github.com/googleapis/google-cloud-go/pull/5493

**Comment by chingor13** [comment]
I manually ran the code in #1685 and it was able to find and tag the above the release.

Also #5339 is irrelevant because it was closed and not merged.

**Comment by tmatsuo** [comment]
Looks like it's done?
