### ISSUE TITLE
dotnet PackageVersion is not automatically updated

### ISSUE THREAD

**Issue by olavloite** [googleapis/release-please#1690]
Automatically generated releases for dotnet projects will update the `Version` tag in the .csproj file, but not the `PackageVersion` if that is also set in the project file. See for example this PR: https://github.com/googleapis/dotnet-spanner-entity-framework/pull/200/files

Would it be possible to add support for updating `PackageVersion` as well?

**Comment by chingor13** [comment]
We don't know which fields to update, so this is all done in config: https://github.com/googleapis/dotnet-spanner-entity-framework/blob/main/release-please-config.json#L11-L15

You should be able to add another entry that specifies the addition xpath in that file to update
