### ISSUE TITLE
Changing java-lts to java-backport in configuration didn't fix the version suffix

### ISSUE THREAD

**Issue by suztomo** [googleapis/release-please#1699]
Thanks for stopping by to ask us a question! Please make sure to include:
- What you're trying to do

In java-pubsub repository, 1.117.x branch was wrongly configured as java-lts and created https://github.com/googleapis/java-pubsub/pull/1343 "chore(1.117.x): release 1.117.1-sp.1". The "-sp.1" versioning is not what I want.

- What code you've already tried

I tried to fix the configuration file. https://github.com/googleapis/java-pubsub/pull/1344 and https://github.com/googleapis/java-pubsub/pull/1345 should fix the next release version but the pull request https://github.com/googleapis/java-pubsub/pull/1343 continues to have "-sp.1" suffix.

- Any error messages you're getting

**Comment by chingor13** [comment]
The last version released in that branch was `1.117.0-sp.1`. java-backport uses the always bump patch versioning strategy, but it does not clear any prerelease flags. To explicitly change that version, update the versions.txt to the non-sp version numbers (like 1.117.0) and then use a `Release-As: 1.117.1` in the commit body.

**Comment by chingor13** [comment]
Also, you can either look at the bot logs, or run with the CLI and `--debug --dry-run` and you can see what it's doing.

**Comment by suztomo** [comment]
Thank you. Trying

```
BEGIN_COMMIT_OVERRIDE
chore: fixing sp.1 version in 1.117.x branch

Release-As: 1.117.1
END_COMMIT_OVERRIDE
```

**Comment by suztomo** [comment]
It worked. Thank you.
