### ISSUE TITLE
"java-notification" does not get picked up by release-please 

### ISSUE THREAD

**Issue by ddixit14** [googleapis/release-please#1710]
In the java [monorepo](https://github.com/googleapis/google-cloud-java/), the module "java-notification" does not get picked up by release-please even though it has releasable commits.

![image](https://user-images.githubusercontent.com/90280028/196526957-04ab6208-8141-4ef2-bf48-26ede8f28c32.png)

**Comment by suztomo** [comment]
@ddixit14 I don't think the screenshot represents the problem. The version for java-notification is being updated in the screenshot.

**Comment by chingor13** [comment]
Java notification does not have any commits that update it, nor does it have cross component dependencies. It has a shared in-repo parent which is not allowed to have individual component releases.
