### ISSUE TITLE
Wrong version update in snapshot PR

### ISSUE THREAD

**Issue by ddixit14** [googleapis/release-please#1712]
In the java monorepo bump to snapshot PR, few of the versions being set are wrong:
![image](https://user-images.githubusercontent.com/90280028/196534353-077286d9-c656-46bd-ba28-43203ea95e93.png)

This is happening for the following modules:
1. [java-datalabeling](https://github.com/googleapis/google-cloud-java/tree/main/java-datalabeling)
2. [java-errorreporting](https://github.com/googleapis/google-cloud-java/tree/main/java-errorreporting)
3. [java-kms](https://github.com/googleapis/google-cloud-java/tree/main/java-kms)

This discrepancy in versions is causing the unit tests to fail.

**Comment by suztomo** [comment]
Memo: this is the snapshot pull request https://github.com/googleapis/google-cloud-java/pull/8628

**Comment by chingor13** [comment]
Going to close this as we switched to a single component setup.
