### ISSUE TITLE
x-version-update-start does not work with the root README.md when used with manifest

### ISSUE THREAD

**Issue by suztomo** [googleapis/release-please#1755]
Thanks for stopping by to let us know something could be better!

This is not a major blocker for something. Probably we can implement workaround with single-component setup. I wanted to record my finding so that I or somebody don't have to repeat issue reporting.

 **Is your feature request related to a problem? Please describe.**

In https://github.com/googleapis/java-cloud-bom repository, I had to manually update the version in README.md  https://github.com/googleapis/java-cloud-bom/pull/5645/files even though the section has `[//]: # ({x-version-update-start:libraries-bom:released})` annotation.

<img width="672" alt="Screen Shot 2022-11-21 at 11 05 16 AM" src="https://user-images.githubusercontent.com/28604/203102304-19280f1b-a9a9-4676-bdae-5d19bb55c38e.png">

 **Describe the solution you'd like**

The Release Please should understand the `[//]: # ({x-version-update-start:libraries-bom:released})` even when README.md is the root of the repository and not within the component of `libraries-bom` directory.

 **Describe alternatives you've considered**

Stop using manifest-based configuration and start using single-component setup.

 **Additional context**

Probably we can implement workaround with single-component setup. I wanted to record my finding so that I or somebody don't have to repeat issue reporting.

**Comment by chingor13** [comment]
`README.md` is not a file looked at by release-please by default. You could configure it via the `extra-files` option in the manifest config. In this case, you'd make the extra file `/README.md` because paths otherwise are relative to their configured path (`libraries-bom` in your example).

**Comment by suztomo** [comment]
Thank you for the guide.
