### ISSUE TITLE
Expo requires Android's `versionCode` to be a `integer` (not a `string`)

### ISSUE THREAD

**Issue by mrzmyr** [googleapis/release-please#1767]
When I try to build the application via Expo, I see this error:

```
Field: android.versionCode - should be integer.
```

For reference: [`versionCode` - Expo Documentation](https://docs.expo.dev/versions/latest/config/app/#versioncode)

Seems like this can be easily fixed here: 
https://github.com/googleapis/release-please/blob/9cb84cb18211c61ed94d856b936fff30036b0988/src/updaters/expo/app-json.ts#L89

**Comment by JaccoGoris** [comment]
Hi, this fix is currently not coming through in the github action because that needs to be updated separately. or is there a different way I can start using it right now? thanks :)
