### ISSUE TITLE
Bump support versions on older releases, bug fixes, patches etc.

### ISSUE THREAD

**Issue by dmi3y** [googleapis/release-please#1792]
I have a question about ability to release bug fix/minor versions for older releases:

e.g there is two active releases `v1.0.0` and `v2.0.0`.

And there is a critical bug found.

Fixing it bumping `v2.0.0` -> `v2.0.1`.

What would be the strategy to port this bug fix on `v1.0.0` to bump it to `v1.0.1`?

And very similar situation if there is some feature needed to be introduced in `v1.0.0` and needing to bump it up to `v1.1.0`?

Thanks!

I was not able to find answer in documentation and that's why I'm asking it here, sorry if I missed it.

**Comment by chingor13** [comment]
release-please does not do branch management, but can support multiple branches.

What we do is:
1. create a `1.x` or `1.0.x` branch from the latest 1.something release tag
2. configure release-please to run against the new branch (optionally change the versioning strategy to something like `always-bump-patch`)
3. cherry-pick/backport your fix commit to the backport branch

release-please is designed to look at commits on the target branch (it ignores other commits on other branches) and will try to determine the next version from the latest release on that branch. It can't distinguish between releases made from other branches so you'll have to make sure that the versions don't collide (e.g. if you merge a breaking change to your `1.x` branch, it'll try and propose a 2.0.0 version even though it may already exist).

**Comment by dmi3y** [comment]
Thank you @chingor13! I'll give it a try 👍
