### ISSUE TITLE
README.md documentation typo providing Expo example

### ISSUE THREAD

**Issue by dmi3y** [googleapis/release-please#1795]
There is a copy/paste typo in root [`README.md`](https://github.com/googleapis/release-please/blob/main/README.md?plain=1#L147) for Expo example provided via this [PR](https://github.com/googleapis/release-please/pull/1646/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R144) by @soulfresh 

Link for the Expo example is referencing https://github.com/yargs/yargs which is node example listed just above it. Expecting to see Expo example instead.

**Comment by dmi3y** [comment]
Shall anyone be interested, I have a [playground project](https://github.com/dmi3y/expo-release-please-example). Works like a charm 👍

**Comment by chingor13** [comment]
If you'd like to submit a PR to use your repo as an example, please re-open this and we can accept it. In the meantime, we will just remove the example link.

**Comment by dmi3y** [comment]
Adding link to playground project in README here https://github.com/googleapis/release-please/pull/2251

**Comment by dmi3y** [comment]
>If you'd like to submit a PR to use your repo as an example, please re-open this and we can accept it. In the meantime, we will just remove the example link.

Don't have a privilege to reopen issues, linked issue in the opened PR.
