### ISSUE TITLE
Make generated files adhere to prettier

### ISSUE THREAD

**Issue by tobiasdiez** [googleapis/release-please#1802]
**Is your feature request related to a problem? Please describe.**
If you lint your markdown files with prettier, then often the generated changelog entries are raising errors and one has to manually run prettier on the generated/modified files to ensure everything is compliant.

 **Describe the solution you'd like**
All generated files (Changelog, contributing, release manifest) should be compliant with prettier.

 **Describe alternatives you've considered**
Manually running prettier on the modified files after the PR is generated and commit fixes, e.g. as in https://github.com/remarkablemark/release-please-extra-files-demo/blob/master/.github/workflows/release-please.yml. This however is rather involved and has the drawback that the linter-commit doesn't trigger a workflow run.

 **Additional context**
Has been originally raised at https://github.com/google-github-actions/release-please-action/issues/542.

**Comment by chingor13** [comment]
Similar to https://github.com/googleapis/release-please/issues/2085, this is not something we are in a position to maintain. Formatting is a personal choice and we cannot feasibly configure formatting for every file type, nor do we plan to run any post-processing binaries.

Users are free to run post-processing on the release-please PRs to "clean up" formatting.
