### ISSUE TITLE
Is there any way to append a build number/semver meta to a release-please calculated version?

### ISSUE THREAD

**Issue by jeacott1** [googleapis/release-please#1816]
Hi,
 I'd like to be able to add a build number (github calculated for example) and/or a qualifier string to the release-please conventional commits calculated version such that my releases look like v1.2.3-98
I can see that its possible to manually replace the entire version with "Release-As", but what I'm looking for is a way to either auto extract the proposed release version and modify it prior to use (a hook of some kind?), or a means to set the Build metadata portion of a semver v2 version number.
Is this possible with release-please?

**Comment by chingor13** [comment]
Sorry this is not something that release-please is designed to do. It does not understand when you are attempting to do a non-release build unless you explicitly want to create a GitHub release on each build. If you do want a PR for every build attempt, you can implement a custom VersioningStrategy that knows how to increment the build number given a list of commits.

**Comment by jeacott1** [comment]
@chingor13 I want to be able to create a 'release-able' version on every merge to main, and that means distinct semver numbers+build numbers so that the build artifacts are distinct, so it's clear whether the code was the same but was rebuilt, can be stored in a npm/maven/nuget etc repo, e2e tested and ultimately tagged as good.
It's only after testing we can know if a release candidate will become a release. release-please doesn't need to understand the difference if there never is one. From my pov a tested release artifact is the artifact that gets released. not rebuilt later hoping its still the same.
it's ok. I definitely don't 'want a PR for every build attempt', I do want a build on every PR change and every merge to main, and they should all produce distinct version numbers - but I understand this is the model release-please is using. I've decided to go a different direction.
Cheers.
