### ISSUE TITLE
Badge status

### ISSUE THREAD

**Issue by octohuguesdumont** [googleapis/release-please#1818]
Thanks for stopping by and telling us that something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console] (https://cloud.google.com/support/) instead of filing it on GitHub. This will give you a quick response.

 **Is your feature request related to an issue? Please describe it.**
A clear and concise description of the nature of the problem. Ex. I am always frustrated when [...]
I'm quite frustrated when I can't get the latest release created in my project's status badge
 **Describe your desired solution**.
retrieve this value so that it can be displayed in the project's README.MD

**Comment by chingor13** [comment]
Sorry, it is out of scope for this project to create status badges. You may want to look into other open source products that can dynamically create badges, perhaps with data available from GitHub release/tag data produced by this library.
