### ISSUE TITLE
Release on release branch

### ISSUE THREAD

**Issue by nnelson-cen65665** [googleapis/release-please#1821]
Hi, 

I'd like to ask how to use Release please for trunk based development. I have NX monorepo with two app in it and it's working fine. My question is how to make release-please to do release for hotfix on a release branch? We usually create release branch (release/X.X.X) from master and deploy on PROD and when we need fix a bug, we fix in that release branch. So we need release-please to create release like x.x.x-hotfix.1. Can not make release-please to do it on release branch and ReleaseAs doesn't work because I have two app with different versions. Any help how to make it work? Thx

release-please.yml
```
primaryBranch: master
manifest: true
handleGHRelease: true
releaseType: node
branches:
  - handleGHRelease: true
    releaseType: node
    branch: release/*
```

.release-please-manifest.json

```
{
  "apps/appname1": "0.5.1",
  "apps/appname1 +FILLER": "0.0.0",
  "apps/appname2": "0.0.4",
  "apps/appname2 +FILLER": "0.0.0"
}
```

release-please-config.json

```
{
  "release-type": "node",
  "separate-pull-requests": true,
  "draft-pull-request": true,
  "packages": {
    "apps/appname1": {
      "changelog-path": "CHANGELOG.md",
      "package-name": "appname1",
      "extra-files": [
        {
          "type": "json",
          "path": "version.json",
          "jsonpath": "$.version"
        }
      ]
    },
    "apps/appname2": {
      "changelog-path": "CHANGELOG.md",
      "package-name": "appname2",
      "extra-files": [
        {
          "type": "json",
          "path": "version.json",
          "jsonpath": "$.version"
        }
      ]
    }
  }
}
```

**Comment by chingor13** [comment]
For backporting fixes, we usually set up release-please to run a couple of times against different branches.

For example, if we have a v1.2.3 release, we may create a 1.2.x branch starting from the v1.2.3 tag's SHA and configure that branch to use an `always-bump-patch` versioning strategy. Any commits to that branch will only look at commits since the last release on that branch's history.

**Comment by nnelson-cen65665** [comment]
Thank you for your answer. I tried to use `always-bump-patch` but it didn't work. Could you please provide some example where a how to use it to make it work? Thx

**Comment by channelninja** [comment]
@chingor13 I would also like to know how this works. How to I configure that 1.2.x branch to use `always-bump-patch`? I'm using the release-please github action.

**Comment by channelninja** [comment]
I think I figured it out. Let me know if this is the right approach to release hotfixes.

prerequisites: 
- install release-please cli: `npm i release-please -g`
- get github token
- run 
```
release-please bootstrap \
--token=github_token \
--repo-url=owner/repo \
--release-type=release_type
```

Then to create a hotfix for i.e. release v1.2.3 with multiple commits added after the release tag:
- new branch from commit with v1.2.3 tag, name it 1.2.x for example
- commit hotfix `fix: hotfixed something`
- push to origin
- run
```
release-please release-pr \
--token=github_token \
--repo-url=owner/repo \
--versioning-strategy=always-bump-patch \
--target-branch=1.2.x
```
- merge release PR into branch 1.2.x
- run
```
release-please github-release \
--token=github_token \
--repo-url=owner/repo \
--target-branch=1.2.x
```
- create PR to merge branch 1.2.x into main

It's a bit of work, but should work. Am I doing this right?

**Comment by chingor13** [comment]
> Now I have a release of my hotfix. But I need to get the fix back to main somehow without triggering release-please again. How does that work?

You will need to cherry-pick the change back to your main branch. Depending on your repo setup, you can do it directly on your branch or to a new branch and open a new PR. For our workflows, we generally fix in `main` first, then cherry-pick to our hotfix branch(es) (you may have to do this multiple times depending on how many backport releases you plan to make).

**Comment by airtonix** [comment]
> we generally fix in `main` first, then cherry-pick to our hotfix branch(es)

Can't do this when `main` has diverged enough from the last release branch.

How do you deal with that? 

or do you just: 

```
them: there's a bug in prod. can you do a hotfix.
you: nah. main has changed too much. wait till the next release
them: will that be in the next hour? 
you: no, end of the week.
them: HEADLESS CHICKEN MODE. HERESY HERESY HERESY
you: ./wrists T_T
```
