### ISSUE TITLE
manifest release: select which directories/assets to release

### ISSUE THREAD

**Issue by Tsanton** [googleapis/release-please#1843]
I'm using the manifest release to version multiple packages inside a single repository. 
It's all working as expected, minus the ability to chose which files/directories gets bundles into the released asset.
Is it possible to configure the manifest to only package assets as a function of globs, i.e.:

```json
{
    "packages": {
        "first-package": {
            "component": "first-package",
            "release-type": ....,
            "assets": [
                 "./**.go",
                 "/ROOT_README.md"
            ]
        },
        "second-package": {
            "component": "second-package",
            "release-type": ....,
        },
        "assets": [
             "./**.cs",
             "./**.yaml",
             "/ROOT_README.md"
        ]
}
```

/T

**Comment by chingor13** [comment]
Sorry for the delay in getting to this.

By assets, do you mean the zip file on the GitHub release? If so, `release-please` doesn't do that -- that source download is built into every GitHub release by default. `release-please` also does not actually handle publication -- it defers to whatever automation you want to run after creating a GitHub release.
