### ISSUE TITLE
Salesforce release type does not allow monorepo

### ISSUE THREAD

**Issue by dschach** [googleapis/release-please#1856]
#### Environment details

  - OS: OSX
  - Node.js version: 19.0.1
  - npm version:9.4.2
  - `release-please` version: 15.7.0

#### Steps to reproduce

  1. create a config file with two entries: "." and "force-app" which is the minimum required for a single metadata directory. Note: Many projects will have multiple metadata directories such as "unpackaged" and various extension directories.
  2. Create the same headings in the project config file.
  3. Attempt to run release-please release-pr (token, repo, branch) and get an error that says

**MissingRequiredFileError: salesforce (dschach/campaign-member-status): Missing required file: force-app/sfdx-project.json**

But a given SFDX project should have only ONE sfdx-project.json file, with a separate packageDirectories object for each package or metadata grouping.

For an example, see [my repo with three metadata directories (force-app, unpackaged, and triggerhandler)](https://github.com/dschach/campaign-member-status)

I am concerned that this Salesforce release type has not been tested properly. It already violates rules by putting version numbers in packageDirectories objects that don't have a value for package.

Release Please Manifest
```
{
  ".": "0.0.0",
  "force-app": "0.0.0",
  "triggerhandler": "0.0.0",
  "unpackaged": "0.0.0"
}
```

Release Please Config
```

{
  "packages": {
    ".": { "release-type": "salesforce" },
    "force-app": { "release-type": "salesforce" },
    "triggerhandler": { "release-type": "salesforce" },
    "unpackaged": { "release-type": "salesforce" }
  },
  "$schema": "https://raw.githubusercontent.com/googleapis/release-please/main/schemas/config.json",
  "release-type": "salesforce",
  "changelog-path": "CHANGELOG.md"
}
```

**Comment by scolladon** [comment]
Hi @dschach !

The actual implementation is written to work with the very simple use case where the `sfdx-project.json` contains one package.

It will works if the `packageDirectories` attribut contains multiple entry but will update only the default one containing a `versionNumber`.

So, it does not work for other package declared in the file yet.

That being said, I would like to help, what would be the result of using release please with multiple package ?
How should it behave ?

Per exemple 2 package A and B under force-app folder
- force-app/A
- force-app/B

and the following `sfdx-project.json`:
```json
{
    "packageDirectories": [
        {
            "path": "force-app/A",
            "default": true,
            "package": "A",
            "versionNumber": "1.0.0.NEXT"
        },
        {
            "path": "force-app/B",
            "default": true,
            "package": "A",
            "versionNumber": "3.2.0.NEXT"
        }
    ],
    "sfdcLoginUrl": "https://login.salesforce.com",
    "sourceApiVersion": "57.0"
}
```

Let's assume we have a commit creating a new major for A and a new minor for B
Then new content should be:
```json
{
    "packageDirectories": [
        {
            "path": "force-app/A",
            "default": true,
            "package": "A",
            "versionNumber": "2.0.0.NEXT"
        },
        {
            "path": "force-app/B",
            "default": true,
            "package": "A",
            "versionNumber": "3.3.0.NEXT"
        }
    ],
    "sfdcLoginUrl": "https://login.salesforce.com",
    "sourceApiVersion": "57.0"
}
```

They both share the same `changelog` file right ? What should be its content ?

**Note:**
I think the complexity here is the package definition is in the same file for every package (the lerna use case, kind of)

**Comment by dschach** [comment]
Thanks for the reply @scolladon - yes, I think the complexity lies in the single file tracking all version numbers, AND I think there may be some complexity in the package name having spaces (because Salesforce allows that) while release-please seems to prohibit spaces. It appears to look for a package name somewhere, though I admit that I don't understand that complexity completely.

There are some multi-repo Salesforce repos (unoffialSF uses one) but those have individual package.json files.

It seems we have to look at multiple use-cases... multi-sub-repo, and monorepo. And we should account for all of those. (And yes, it does look somewhat like the lerna use-case.)

BTW, in your last code example, it has package and version number, but keep in mind:

People may use their repos for making packages, but some just use it to maintain an org or to host open-source projects. Those projects sometimes have multiple metadata directories but no package name for some of them. For orgs just breaking up metadata on their path to org-dependent packages, it resembles the ISV model, so that's fine.

Sorry for rambling - I see a few use-cases for an sfdx project, and I'd like us to be able to allow for all of those. 

One last thought: Having separate changelogs would actually be really cool... as an option. Some orgs may want a unified changelog.

So much to think about... Of course Salesforce makes it complex. :)

**Comment by dschach** [comment]
To directly answer your question: Some packages have unpackaged metadata in separate directories, that are needed for Apex tests, or sometimes just for installation of extra metadata. See an example at https://github.com/salesforcelabs/actionplansv4 to see what I mean.
