### ISSUE TITLE
How to create PR after initial release using java strategy

### ISSUE THREAD

**Issue by surjitbhachu** [googleapis/release-please#1859]
I'm trying to test release-please and CLI with a java project (spring boot with gradle) but I am getting an error when trying to create a release pull request once v1.0.0 is published. 

I am using the latest release: 15.8.0

Here is what I did. 

1. Created a new GH repo
2. Bootstrapped the repo

`release-please bootstrap --token=$GITHUB_TOKEN --repo-url=<owner>/<repo> --release-type=java`

3. Merged the original PR
4. Added my Java project code
5. Created the PR

`release-please release-pr --token=$GITHUB_TOKEN --repo-url=<owner>/<repo>`

6. Merged the PR and then released

`release-please github-release --token=$GITHUB_TOKEN --repo-url=<owner>/<repo>`

This all worked correctly and created the v1.0.0 release but now when I make and commit some changes to the code and try to create a new PR by running this command

`release-please release-pr --token=$GITHUB_TOKEN --repo-url=<owner>/<repo>`

I get the following message and error:

```
❯ Fetching release-please-config.json from branch main
❯ Fetching .release-please-manifest.json from branch main
✔ Building pull requests
✔ Building strategies by path
❯ .: java
✔ Collecting release commit SHAs
❯ release search depth: 400
❯ Fetching releases with cursor undefined
❯ Found release for path ., v1.0.0
❯ release for path: ., version: 1.0.0, sha: 3ad5b05010af8b1a6c13d5cac5df819e6e338cff
✔ Collecting commits since all latest releases
❯ commit search depth: 500
❯ Set(1) { '3ad5b05010af8b1a6c13d5cac5df819e6e338cff' }
❯ Fetching merge commits on branch main with cursor: undefined
❯ Backfilling file list for commit: 2188045a4571c8f61e303022728c3f29f5e2bbad
❯ Found 1 files
❯ Backfilling file list for commit: d07113159a189a1953179f18574d576674bb2470
❯ Found 2 files
❯ Backfilling file list for commit: 3c03610f792d77483eb0a0b1c551c90ead36b5f0
❯ Found 10 files
❯ Backfilling file list for commit: b1e004ffbf02e077032908261c507cce269849ee
❯ Found 1 files
✔ Splitting 1 commits by path
✔ Building candidate release pull request for path: .
❯ type: java
❯ targetBranch: main
❯ commits: 1
❯ component: 
✔ Repository needs a snapshot bump.
✔ Looking for open release pull requests
✔ found 0 open release pull requests.
✔ Looking for snoozed release pull requests
✔ found 0 snoozed release pull requests.
✔ Empty change set provided. No changes need to be made. Cancelling workflow.
release-please release-pr

HttpError: Not Found
    at /usr/local/lib/node_modules/release-please/node_modules/@octokit/request/dist-node/index.js:78:21
    ... 8 lines matching cause stack trace ...
    at async Object.handler (/usr/local/lib/node_modules/release-please/build/src/bin/release-please.js:340:40) {
  status: 404,
  body: {
    message: 'Not Found',
    documentation_url: 'https://docs.github.com/rest/reference/pulls#get-a-pull-request'
  },
  name: 'GitHubAPIError',
  cause: RequestError [HttpError]: Not Found
      at /usr/local/lib/node_modules/release-please/node_modules/@octokit/request/dist-node/index.js:78:21
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /usr/local/lib/node_modules/release-please/build/src/github.js:168:30
      at async GitHub.getPullRequest (/usr/local/lib/node_modules/release-please/build/src/github.js:1222:20)
      at async /usr/local/lib/node_modules/release-please/build/src/github.js:160:20
      at async GitHub.createPullRequest (/usr/local/lib/node_modules/release-please/build/src/github.js:1222:20)
      at async Manifest.createOrUpdatePullRequest (/usr/local/lib/node_modules/release-please/build/src/manifest.js:507:32)
      at async Promise.all (index 0)
      at async Manifest.createPullRequests (/usr/local/lib/node_modules/release-please/build/src/manifest.js:447:33)
      at async Object.handler (/usr/local/lib/node_modules/release-please/build/src/bin/release-please.js:340:40) {
    status: 404,
    response: {
      url: 'https://api.github.com/repos/<owner>/<repo>/pulls/0',
      status: 404,
      headers: [Object],
      data: [Object]
    },
    request: {
      method: 'GET',
      url: 'https://api.github.com/repos/<owner>/<repo>/pulls/0',
      headers: [Object],
      request: [Object]
    }
  }
}
```

If I try to add the --dry-run parameter I get:

```
❯ Fetching release-please-config.json from branch main
❯ Fetching .release-please-manifest.json from branch main
✔ Building pull requests
✔ Building strategies by path
❯ .: java
✔ Collecting release commit SHAs
❯ release search depth: 400
❯ Fetching releases with cursor undefined
❯ Found release for path ., v1.0.0
❯ release for path: ., version: 1.0.0, sha: 3ad5b05010af8b1a6c13d5cac5df819e6e338cff
✔ Collecting commits since all latest releases
❯ commit search depth: 500
❯ Set(1) { '3ad5b05010af8b1a6c13d5cac5df819e6e338cff' }
❯ Fetching merge commits on branch main with cursor: undefined
❯ Backfilling file list for commit: 2188045a4571c8f61e303022728c3f29f5e2bbad
❯ Found 1 files
❯ Backfilling file list for commit: d07113159a189a1953179f18574d576674bb2470
❯ Found 2 files
❯ Backfilling file list for commit: 3c03610f792d77483eb0a0b1c551c90ead36b5f0
❯ Found 10 files
❯ Backfilling file list for commit: b1e004ffbf02e077032908261c507cce269849ee
❯ Found 1 files
✔ Splitting 1 commits by path
✔ Building candidate release pull request for path: .
❯ type: java
❯ targetBranch: main
❯ commits: 1
❯ component: 
✔ Repository needs a snapshot bump.
Would open 1 pull requests
fork: false
title: chore(main): release 1.0.1-SNAPSHOT
branch: release-please--branches--main
draft: false
body: :robot: I have created a release *beep* *boop*
---

### Updating meta-information for bleeding-edge SNAPSHOT release.

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).
updates: 0

```

What am I doing wrong?

**Comment by chingor13** [comment]
This library (really, the underlying `code-suggester` library) will not actually open the pull request unless there are files to update.

Without seeing a configuration file, it's hard to see why it's not finding files to update. Most `release-type`s look for certain files by convention for the language (e.g. pom.xml files for a maven project).

**Comment by surjitbhachu** [comment]
Thanks Jeff for replying. 

The thing is, there are multiple Java files which been updated and committed. It did do the initial release of 1.0.0 but not any subsequent ones.

For my Java project I am using [Gradle](https://gradle.org/) instead of Maven as my build tool. 

Here is my configuration file:

```
{
  "packages": {
    ".": {
      "changelog-path": "CHANGELOG.md",
      "release-type": "java",
      "bump-minor-pre-major": false,
      "bump-patch-for-minor-pre-major": false,
      "draft": false,
      "prerelease": false
    }
  },
  "$schema": "https://raw.githubusercontent.com/googleapis/release-please/main/schemas/config.json"
}
```

I have given you access to my test repo https://github.com/surjitbhachu/spring-boot-release-please.git  

If you try to use the release please CLI to create a release pr, it will give you error above even though there are committed changes to form a release. Please feel free to add a commit to reproduce.

**Comment by chingor13** [comment]
The `java` `release-type` does not specify any files to touch besides a `CHANGELOG.md`. For the `java` strategy, it tries to do a version bump to the next `-SNAPSHOT` version. If you don't care about the `-SNAPSHOT` versioning pattern that many Java libraries follow, then you can switch to the `simple` `release-type` which updates the same files by default.

In your case, you will need to specify `build.gradle` as an `extra-files` entry and then [annotate the file](https://github.com/googleapis/release-please/blob/main/docs/customizing.md#updating-arbitrary-files) to mark where the version needs to be updated.

Example:

```gradle
group = 'REDACTED'
// x-release-please-start-version
version = '0.0.1-SNAPSHOT'
// x-release-please-end
sourceCompatibility = '19'
```

**Comment by tboyd-eb** [comment]
We are experiencing the same issue, however we _are_ using the `simple` strategy. Our CI workflow had been updating the single release PR for the single package in our configuration (not the root directory, but a subfolder), but when we added a second package, we started seeing this error. I closed the release PR for the first package in our monorepo, as that managed to "reset" things in the past when it was a single package, but that isn't working anymore.

It looks like it's trying to get information about pull request 0 at some point in the process.

Here's our somewhat-redacted configuration:

```
{
	"packages": {
		"a-service": {
			"bump-minor-pre-major": true,
			"bump-patch-for-minor-pre-major": true,
			"changelog-path": "CHANGELOG.md",
			"draft": false,
			"extra-files": ["gradle.properties"],
			"package-name": "a-service",
			"prerelease": true,
			"release-type": "simple",
			"separate-pull-requests": true
		},
		"b-service": {
			"bump-minor-pre-major": true,
			"bump-patch-for-minor-pre-major": true,
			"changelog-path": "CHANGELOG.md",
			"draft": false,
			"extra-files": ["gradle.properties"],
			"package-name": "b-service",
			"prerelease": true,
			"release-type": "simple",
			"separate-pull-requests": true
		}
	},
	"$schema": "https://raw.githubusercontent.com/googleapis/release-please/main/schemas/config.json"
}
```

**Comment by tboyd-eb** [comment]
I was able to resolve this by manually running `release-please` with the `--path` parameter set to a single one of the packages and then repeating it afterward for the other. It created both pull requests. I'm curious if it will have issues in the future running against the root path, however.

**Comment by KasparovNikolay** [comment]
I have the same issue and still have no clue how to fix it.
I can't resolve this issue [in this way](https://github.com/googleapis/release-please/issues/1859#issuecomment-1544213329), because i need multi pr.
Should we reopen it? @chingor13

**Comment by michaelpeterswa** [comment]
I am encountering the same issue for a multiple module go repository, and it is still failing every time on the first commit (whether or not the Changelog is present on the commit), and I'm curious as to the behavior that causes the failure. I've tried looking through the upstream dependencies tracing the error message back to here [index.ts#L72 - Code Suggester](https://github.com/googleapis/code-suggester/blob/589b3ac11ac2575fd561afa45034907f301a375b/src/index.ts#L72) with no luck understanding why.

```
✔ Empty change set provided. No changes need to be made. Cancelling workflow.
Error: release-please failed: Not Found
```
I would also love to see this reopened with some enhanced clarity as to best practices in multi-release scenarios.

**Comment by s33dunda** [comment]
@chingor13 can this be reopened based off of @tboyd-eb findings. I was able to recreate this too.

> I was able to resolve this by manually running release-please with the --path parameter set to a single one of the packages and then repeating it afterward for the other. It created both pull requests. I'm curious if it will have issues in the future running against the root path, however.

> Edit: Confirmed. It blows up any time it's run without a --path parameter.

Instead of it finding the paths from the release-please-config.json packages it requires the --path.

Seems like a bug to me running on 16.18.0 and 17.0.0 (via npx).

For now, I'm going to parse the paths in the release-please-config.json and create a github matrix for each path.
