### ISSUE TITLE
PR merged, no git tag have been created.

### ISSUE THREAD

**Issue by adelin-b** [googleapis/release-please#1863]
I created a PR using release-please cli.

```
npx release-please release-pr --token=$GITHUB_TOKEN --repo-url=our-orga/our-repo
```
All went well, it took time because there was never a release before and more than 500 commits.

But there is no tag `git tag` show nothing.

```
$ sh ./scripts/release/release-please.sh
npm WARN config init.author.email Use `--init-author-email` instead.
npm WARN config init.author.name Use `--init-author-name` instead.
npm WARN config init.author.url Use `--init-author-url` instead.
❯ Fetching release-please-config.json from branch develop
❯ Fetching .release-please-manifest.json from branch develop
✔ Building pull requests
✔ Building strategies by path
❯ .: node
❯ Fetching package.json from branch develop
✔ Collecting release commit SHAs
❯ release search depth: 400
❯ Fetching releases with cursor undefined
⚠ Could not find releases.
⚠ Expected 1 releases, only found 0
⚠ Missing 1 paths: .
❯ looking for tagName: our-package-v1.0.0
⚠ Expected 1 releases, only found 0
✔ Collecting commits since all latest releases
❯ commit search depth: 500
```

 Why is there no tag after merging ? is there a setting when we merge with tags ? Is this in release-please ?

**Comment by talShtark** [comment]
The same happens to me.
I used Github action to create the release PR. After merging the PR it still has the "autorelease: pending" label...

**Comment by chingor13** [comment]
There are 2 commands from the CLI:

1. `release-pr` opens the release pull request
2. `github-release` looks for merged release pull requests and tags them

For the GitHub action, there are 2 `command`s (`release-pr` and `github-release`). Leave `command` blank if you want it to run both steps.
