### ISSUE TITLE
Commit overrides do not work when merges are not squashed

### ISSUE THREAD

**Issue by ivomurrell** [googleapis/release-please#1899]
#### Environment details

  - OS: macOS 13.1
  - Node.js version: 16.14.0
  - npm version: 8.5.4
  - `release-please` version: 15.9.2

#### Steps to reproduce

  1. Make a commit to branch `foo` that's designated as a breaking change with a commit message like `feat!: rewrite in rust`
  2. Create a PR to merge `foo` into `main`
  3. Merge `foo` to your `main` branch along with a merge commit with `git merge --no-ff foo`. This is GitHub's [behaviour](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/about-merge-methods-on-github) when merging a PR with the 'Create a merge commit' dropdown option.
  4. Try to override the semver resolution to only do a minor version bump by overriding the commit message in the PR body with something like
```
BEGIN_COMMIT_OVERRIDE
feat: rewrite in rust
END_COMMIT_OVERRIDE
```
  5. Note that the PR generated by release-please is still treating the change as a major version bump.

This is because only the merge commit has a [`pullRequest`](https://github.com/googleapis/release-please/blob/af30ea6a99d8ae02038043467e7c6c900a15b50d/src/commit.ts#L410) associated with it, and so only the merge commit is overridden, whilst the rest of the commits merged in are preserved. So in this example the commits from this merge will be overridden from
```
Merge pull request #1 from example/repository
feat!: rewrite in rust
```
to
```
feat: rewrite in rust
feat!: rewrite in rust
```
So the major version bump from the original commit message wins out.

This means that it isn't possible to drop a change from a major version bump to a minor version bump via the PR body if you selected GitHub's 'Create a merge commit' option rather than its 'Squash and merge' option, even though both are [stated](https://github.com/googleapis/release-please/blob/af30ea6a99d8ae02038043467e7c6c900a15b50d/README.md?plain=1#L26-L27) to be supported by release-please.

**Comment by chingor13** [comment]
As you stated, only the merge commit is associated with the pull request, so it's very difficult to try to handle commit overrides in the plain merge case. 

We highly recommend squash-merging (to keep a linear history and ensure every commit in the release branch is stable). We will update the docs to reflect this.
