### ISSUE TITLE
release-pr ignores commits before the previous release

### ISSUE THREAD

**Issue by tuxmachine** [googleapis/release-please#1932]
We noticed release-please didn't open a new PR after merging a feature PR. After running the release-please CLI locally and adding some extra logs to the code we figured out why.

The commit history it fetches from the GitHub API is chronological, and the CLI loops through them until it finds the previous release-commit (https://github.com/googleapis/release-please/blob/2b56b2213c10c6a0d3265746b10b19fbfce47292/src/manifest.ts#L619-L621)

In our case that would be the list below
![image](https://user-images.githubusercontent.com/692443/234018062-a3d4f5d9-baf7-4245-81a2-93e4a6044981.png)

Commits that were part of the merges, but were committed before the previous release are listed below the release. Only 2 commits now satisfy the conventional-changelog template and neither are `fix` or `feat`. So the CLI quits with "No user facing commits found".

#### Environment details

  - OS: Linux
  - Node.js version: 16
  - npm version: 8.19
  - `release-please` version: 15.10.4

#### Steps to reproduce

  1. Commit features to PR
  2. Release other stuff
  3. Merge feature PR from (1)
  4. No new release-pr gets opened

**Comment by chingor13** [comment]
This is a major reason that we highly [recommend using a linear git history](https://github.com/googleapis/release-please#linear-git-commit-history-use-squash-merge) (via squash-merge or rebase-merge). The primary reason is that we need to support multiple possible release branches.

To identify if a commit is on the branch, we need to iterate backwards through history on that branch and doing so, we need to pick a time to stop iterating (this is usually when we see a previous release tag or see a release PR or a max commit limit). It would be non-trivial in API calls and logic to identify merge commits and go down those commit lines to "go past" the release tags.

**Comment by tuxmachine** [comment]
Fair enough, should've read the manual a bit closer. And agreed, it's a non-trivial problem. Too bad because it does limit the value; not all teams can/want to do linear history.
