### ISSUE TITLE
Failing build due to not compatible dependencies

### ISSUE THREAD

**Issue by alex-enchi** [googleapis/release-please#1936]
Currently all builds are failing see [job run](https://github.com/googleapis/release-please/actions/runs/4819130759/jobs/8581951125?pr=1935)

It is due to the fact octokit types and dependency itself are not compatible. It would be great to have dependencies locked to avoid those sudden issues.

To reproduce that issue currently you can delete `package-lock.json` file and `node_modules` and re-install dependencies.

See partially related issue on [octokit](https://github.com/octokit/plugin-paginate-rest.js/issues/521)

**Comment by chingor13** [comment]
We locked the dependencies in this repo with a package-lock.json which is not ideal, but it's too disruptive when octokit breaks their types via diamond dependencies while they rollout all their releases.
