### ISSUE TITLE
Can I get manifest releaser to update node's devDependencies / peerDependencies fields too?

### ISSUE THREAD

**Issue by TimothyJones** [googleapis/release-please#1943]
### What I am trying to do

I have a node monorepo managed with lerna, and I'm using release-please manifest. Inside the monorepo, I have some linked packages that compile with [jsii](https://aws.github.io/jsii/). These need to link to each other with `peerDependencies` and `devDependencies`, instead of `dependencies`. 

However, when the manifest releaser bumps the package numbers for linked packages, it only modifies the versions from `dependencies`. This means the release PR fails the build.

Is there a way I can get manifest-releaser with release-type: node  to also update linked packages in devDependencies and peerDpendencies?
 
### What code I've already tried

Extensively searched the documentation

### Any error messages you're getting

Error messages on build because the versions that are included are not correct (not errors from release-please).

**Comment by TimothyJones** [comment]
Apologies, it appears to update devDependencies - but not peerDependencies.

**Comment by TimothyJones** [comment]
Perhaps this is actually a bug report? I haven't read the code too closely, but it looks like maybe `peerDependencies` should be in [this list](https://github.com/googleapis/release-please/blob/main/src/plugins/node-workspace.ts#L368)?

**Comment by TimothyJones** [comment]
Anything I can do to help investigate this one?

**Comment by weaintplastic** [comment]
I'd also be interested in a solution to this.

**Comment by TimothyJones** [comment]
I [raised a PR](https://github.com/googleapis/release-please/pull/2094) with a fix for this.
