### ISSUE TITLE
Can 'release-please' be used with Azure DevOps Git repository? 

### ISSUE THREAD

**Issue by lamelyan** [googleapis/release-please#1954]
I wanted to use the [standard-version tool](https://github.com/conventional-changelog/standard-version#standard-version), however, it says that it's deprecated. Recommendation to use please-release **"if you are a GitHub user**".  Does this imply that please-release only works with GitHub?  What about other products like Azure DevOps Git Repos?

**Comment by chingor13** [comment]
Yes, it only supports GitHub currently (and no imminent plans to support other vendors)
