### ISSUE TITLE
release-please fails with "Not Found" when attempting to release new version

### ISSUE THREAD

**Issue by Nickersoft** [googleapis/release-please#1955]
I'm currently facing an odd issue in a repo of mine where releasing by deploying to `main` [seems to be breaking](https://github.com/TheOpenDictionary/odict/actions/runs/5030831520/jobs/9023516139). The GitHub releases are created properly, but the action still fails with "release-please failed: Not Found" (see link). This prevents the associated newly-released packages from deploying. Looking through the logs, I can't seem to be pinpoint any particular reason it's failing.

My release-please configuration [can be found here](https://github.com/TheOpenDictionary/odict/blob/main/release-please-config.json). 

Unsure what have caused this, as it just seemed to start happening recently.

#### Environment details

  - OS: macOS Venture 13.1
  - Node.js version: 18.16.0
  - npm version: 9.5.1
  - `release-please` version: latest

**Comment by ycrc5** [comment]
I have also ran into this issue and from the looks of it, it seems to only happen to the first package listed in the config file. I have separated each of my packages into prs with `"separate-pull-requests": true` and only the PR with the first package seems to fail. Hope this gives a clue to the cause.

**Comment by Nickersoft** [comment]
Hey 👋🏻  Just following up here four months later – in my case, this is happening for a single PR, and started to surface between [April and May](https://github.com/search?q=repo:TheOpenDictionary/odict+release+main&type=commits&p=2) for me. I checked my commits during that time and I didn't seem to structure the folders any different that would lead to some sort of wonky failure.

Still seeing this issue four months later – any advice or steps I could take to resolve this would be greatly appreciated 👍🏻  Right now have just been skirting the issue by manually publishing my Python and Node packages after `release-please` creates the releases, then fails the CI.

**Comment by Nickersoft** [comment]
Update here: I believe this is an issue with the GH Action for `release-please`, not with the executable itself. [This PR](https://github.com/google-github-actions/release-please-action/pull/753) seems to have broken things for me. Closing this PR and moving it to the other repo.
