### ISSUE TITLE
SBOM generation for release PRs

### ISSUE THREAD

**Issue by lance** [googleapis/release-please#2014]
This is a duplicate of https://github.com/google-github-actions/release-please-action/issues/794 since the feature is probably more appropriately located here. I'm happy to close one or the other if necessary.

### TL;DR

I am trying to generate an SBOM for my npm module upon release. However, there is a bit of a chicken and egg problem. When the release PR is merged, this includes changes to the package-lock.json file which in turn results in a modification of the SBOM, which means that when the release is published, the SBOM is out of date.

A tangible example:

- clone this repository: https://github.com/nodeshift/faas-js-runtime
- change into the repo directory and run `git checkout v2.2.1` (the most recent release tag)
- run `npm run sbom` which generates an SBOM based on the current `package-lock.json` file
- run `git diff` to see what should have been included in the release SBOM

<details>
<summary>SBOM diff</summary>

```diff
diff --git a/sbom.json b/sbom.json
index 8c54a78..3a71768 100644
--- a/sbom.json
+++ b/sbom.json
@@ -3,9 +3,9 @@
   "bomFormat": "CycloneDX",
   "specVersion": "1.4",
   "version": 1,
-  "serialNumber": "urn:uuid:1a3adee4-7f98-4b19-8c50-97eda0e1d650",
+  "serialNumber": "urn:uuid:c6ddbb8b-facb-47bb-ac8e-ea46ecb8a489",
   "metadata": {
-    "timestamp": "2023-07-13T21:02:27.796Z",
+    "timestamp": "2023-07-13T21:56:55.035Z",
     "tools": [
       {
         "vendor": "@cyclonedx",
@@ -55,8 +55,8 @@
     "component": {
       "type": "application",
       "name": "faas-js-runtime",
-      "version": "2.2.0",
-      "bom-ref": "faas-js-runtime@2.2.0",
+      "version": "2.2.1",
+      "bom-ref": "faas-js-runtime@2.2.1",
       "author": "Red Hat, Inc.",
       "description": "A Node.js framework for executing arbitrary functions in response to HTTP or cloud events",
       "licenses": [
@@ -66,7 +66,7 @@
           }
         }
       ],
-      "purl": "pkg:npm/faas-js-runtime@2.2.0?vcs_url=git%2Bhttps%3A//github.com/nodeshift/faas-js-runtime.git",
+      "purl": "pkg:npm/faas-js-runtime@2.2.1?vcs_url=git%2Bhttps%3A//github.com/nodeshift/faas-js-runtime.git",
       "externalReferences": [
         {
           "url": "git+https://github.com/nodeshift/faas-js-runtime.git",
@@ -2764,7 +2764,7 @@
   ],
   "dependencies": [
     {
-      "ref": "faas-js-runtime@2.2.0",
+      "ref": "faas-js-runtime@2.2.1",
       "dependsOn": [
         "cloudevents@7.0.1",
         "commander@11.0.0",
```
</details>

It seems that it may be possible to do this with plugins (https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md#plugins). But it's not clear or straightforward.

### Detailed design

As a part of the PR generation, `release-please` could use the `@cyclonedx/cyclonedx-library` to optionally generate an SBOM and commit the changes.

### Additional information

A stopgap solution may be to create a draft release and manually update it with modifications to the SBOM but this will need to happen with each update to the release PR.

**Comment by lance** [comment]
I have a workaround currently that updates the release PR branch with an updated SBOM during the github action. See: https://github.com/nodeshift/faas-js-runtime/pull/278

**Comment by chingor13** [comment]
Generating SBOMs is currently out of scope of this tool. A few options:
1. When the release-please PR is opened, use another tool to generate the SBOM and add a commit to the PR
2. At publication time, generate the SBOM for the library you are releasing. This is the general strategy we plan to use for our libraries.
