### ISSUE TITLE
Recommended way to Update additional files within a release.

### ISSUE THREAD

**Issue by aaronware** [googleapis/release-please#2022]
This is potentially an extension of #1798 that I reported in January. We have some additional files that we want to edit related to a given release. Were not looking to update versions but more so looking to update arbitrary information within comment blocks.  

A few real-world examples for us beyond #1798. When a release is happening we update about 7-10 files with version number bumps however for our projects we have dependencies that we also like to list in the release and the versions of each of those dependencies typically within various readme files. Since our projects primarily are WordPress based; those dependencies could be composer, npm, or even a list of WordPress plugins associated with the project. 

These types of files changes are not something the core of release-please should really need to worry about so I was wondering if there was a specific hook/event or ability to create custom updaters or have them included without making a pull request on top of a pull request? Mainly we want to be able to define our list of files in the release-please-config.js and a path to a custom updater that could run through and update accordingly (probably based on other clearly defined comment blocks.

Not really sure about the security implications or the complexity or if this approach makes sense

If there is a "better" approach to accomplish what I am trying, or if I should hit up the release-please-action project I can do that as well.

**Comment by chingor13** [comment]
My personal recommendation is to chain automations rather than trying to get release-please to do what you want here. You can configure release-please to add arbitrary labels to the PR it creates which you can use in other automations to identify a release PR. Other automations can potentially make changes in that branch and directly commit to that branch.

**Comment by aaronware** [comment]
I don't necessarily disagree. I'll give it some experimentation. Thanks @chingor13

**Comment by danielo515** [comment]
Can someone detail that strategy a bit more? How do you add those attributes, and how do you read data from them?
