### ISSUE TITLE
How versions are updated in simple projects with "version-file" option

### ISSUE THREAD

**Issue by unjust** [googleapis/release-please#2025]
Thanks for stopping by to ask us a question! Please make sure to include:
- What you're trying to do
I have a monorepo with some projects that aren't node and a bit "no code" just content, so I configured them as 'simple'. I created a `version.json` in each of these projects, thinking that `release-please` would update the json with `{ "version": "1.whatever.version" }` Instead it just overwrites the json object with text `1.0.0`. Is there a way to get it to edit the object properly? 
- What code you've already tried
here is [the config ](https://github.com/unjust/bootcamp/blob/3dc4ddd49f3281ba50784249fbd459e350ff60cb/release-please-config.json#L47-L51)
and [the version.json](https://github.com/unjust/bootcamp/blob/3dc4ddd49f3281ba50784249fbd459e350ff60cb/projects/03-ux-consultancy/version.json)
- Any error messages you're getting
after the release-pr command the version.json [looks like this](https://github.com/unjust/bootcamp/blob/d169ac9bb528e79fd49e0af221c9ef5dae2fcce0/projects/03-ux-consultancy/version.json)
 Is there a way to get it to edit the object properly? or will release-please always just override it as text?

**Comment by unjust** [comment]
Maybe [this can be used](https://github.com/googleapis/release-please/blob/8ea20e29aed278271684351f3cc5a8607c5c1824/docs/customizing.md#updating-arbitrary-json-files) ?

**Comment by chingor13** [comment]
Sorry for the late reply, but yes, you should use the `extra-files` option.
