### ISSUE TITLE
extra-files configuration stopped working 

### ISSUE THREAD

**Issue by parthea** [googleapis/release-please#2032]
In https://github.com/googleapis/python-aiplatform, there is an `extra-files` [configuration](https://github.com/googleapis/release-please/blob/main/docs/customizing.md#updating-arbitrary-files) [here](https://github.com/googleapis/python-aiplatform/blob/cb904d772abd0836f67b1034074395ce7a032d66/release-please-config.json#L6) to  update `**/gapic_version.py` files in the repository. 

In [release 1.28.1 of aiplatform](https://github.com/googleapis/python-aiplatform/pull/2358), and earlier versions, release-please updated the files as expected. In the latest release, [1.29.0 of aiplatform](https://github.com/googleapis/python-aiplatform/pull/2391), release-please didn't update the files. 

There were no changes in the release-please configuration between 1.28.1 and 1.29.0

**Comment by chingor13** [comment]
https://github.com/googleapis/python-aiplatform/commit/cb904d772abd0836f67b1034074395ce7a032d66#diff-35de1d9d9feb5d407dc0e1ca40e9490c335cdd441607bdaf49f8c1bb0a5e0c7d removed the `manifest: true` option so the release-please app is ignoring the configuration in `release-please-config.json`

**Comment by SurferJeffAtGoogle** [comment]
@parthea In light of Jeff's reply, do you think this is still a bug?

**Comment by parthea** [comment]
This was a false bug report. Closing.
