### ISSUE TITLE
Add default reviewers for release PRs

### ISSUE THREAD

**Issue by marcel-stainless** [googleapis/release-please#2037]
When a release PR is created, it needs to be approved by a certain set of approvers. Would be nice if there could be a default set of reviewers for each project that release-please would then add

**Comment by chingor13** [comment]
As mentioned in #2038, reviewers feels out of scope of this automation. There is often more logic desired for assigning or requesting reviews.

This most straightforward way on GitHub is to add a CODEOWNERS file/rule for the files that need updating.
