### ISSUE TITLE
Any way to configure the package headings in the PR comments?

### ISSUE THREAD

**Issue by dabeeeenster** [googleapis/release-please#2045]
Is there any way to configure the package headings in the PR comments that Release Please generates? 

As per https://github.com/Flagsmith/flagsmith/pull/2628

<img width="853" alt="image" src="https://github.com/googleapis/release-please/assets/173290/f44503b9-02df-49a7-9e89-ac511fb20f8a">

We would like to include the package names - `api|frontend|docs` in the highlighted subheadings? Couldnt find anything in the docs for this. 

Thanks!

**Comment by chingor13** [comment]
Apologies for the late reply.

These headings should use `component` for the headings (also included in the tag). Some `release-type`s can autodetect the component name (e.g. node looks at the name in package.json). If not, you can specify the `component` in the `packages` section:

```
{
  "release-type": "simple",
  "packages": {
    "path/to/api": {
      "component": "api"
    },
    "path/to/frontend": {
      "component": "frontend"
    }
  }
}
```

In the above example, we would create one PR with 2 sections (assuming both had releases pending). The titles would be something like `api: 1.2.3` and `frontend: 2.3.4` respectively and the releases tagged would be `api-v1.2.3` and `frontend-v2.3.4`.
