### ISSUE TITLE
How to combine arbitrary files and json files in `extra-files` configuration?

### ISSUE THREAD

**Issue by christopherhex** [googleapis/release-please#2052]
I want to update the version number both in arbitrary files `x-release-please-*` tag and in JSON files. 

In the repository that I'm working on (https://github.com/fibricheck/ios-camera-sdk), I'm using the `release-please-config.json` file to configure which files needs to be updated.

✅ This configuration will update the version in `documentation/project_info.json`
```
{
    "packages": {
        ".": {
            "release-type": "simple",
            "extra-files": [
                "README.md",
                "FibriCheckCameraSDK.podspec",
                "documentation/project_info.json"
            ]
        }
    }
}
```

❌ However the following configuration will not update `documentation/project_info.json`:

```
{
    "packages": {
        ".": {
            "release-type": "simple",
            "extra-files": [
                "README.md",
                "FibriCheckCameraSDK.podspec",
                "documentation/project_info.json",
                {
                    "type": "json",
                    "path": "documentation/project_info.json",
                    "jsonpath": "$.version"
                }
            ]
        }
    }
}
```

The content of `documentation/project_info.json`:
```json
{
  "description": "FibriCheck Camera SDK...",
  "extra": [],
  "name": "ios-camera-sdk",
  "safetyClass": "A",
  "version": "0.1.3"
}
```

I would expect both configurations to work. Is this a bug or is providing multiple types of `extra-files` not supported?

**Comment by chingor13** [comment]
You should be able to specify the different types of extra files. Try:

```
{
    "packages": {
        ".": {
            "release-type": "simple",
            "extra-files": [
                "README.md",
                "FibriCheckCameraSDK.podspec",
                {
                    "type": "json",
                    "path": "documentation/project_info.json",
                    "jsonpath": "$.version"
                }
            ]
        }
    }
}
```

Note the removal of the plain `documentation/project_info.json`. Also note that the configuration must be exist in the target branch (usually `main`).

Example: https://github.com/chingor13/ios-camera-sdk/commit/8bbb0c227f90932518fa2e9f25d3749e4d1fd12e which then created https://github.com/chingor13/ios-camera-sdk/pull/1 (ignore any incorrect commit messages -- my fork does not have any existing releases/tags)
