### ISSUE TITLE
Don't increment major version on breaking change to a preview artifact

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/release-please#2059]
If an artifact is currently at version `0.x.y` (where the `0` indicates a preview version), release-please should keep  it as a preview version even when encountering breaking changes, which are acceptable in previews. The version number should be incremented to `0.x+1.0`. Currently, we have to do this ourselves, which is unnecessary toil.

**Comment by parthea** [comment]
Closing as I found a toggle switch available via the `bump-minor-pre-major` setting.

```
  // BREAKING CHANGE only bumps semver minor if version < 1.0.0
  // absence defaults to false
  "bump-minor-pre-major": true,
```

https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md#configfile
