### ISSUE TITLE
Support for dot separation inside prerelease versions

### ISSUE THREAD

**Issue by bhvngt** [googleapis/release-please#2090]
**Is your feature request related to a problem? Please describe.**

Thanks for this repo. While trying to bump version with `prerelease` strategy, I have noticed that the current code does not support [dot separation](https://semver.org/#backusnaur-form-grammar-for-valid-semver-versions). In the spec, dot-separation is optional. However, in practice its a fairly common format used to separate `prerelease id` from its version number.

For example,  code currently supports following prerelease version bumps
```
'2.0.0-beta01': '2.0.0-beta02',
```
With support for `dot separation`, it will also support following format
```
'2.0.0-beta.01': '2.0.0-beta.02',
or
'2.0.0-beta.1': '2.0.0-beta.2',
```

This is a completely backward compatible change. 

 **Describe the solution you'd like**

I have looked through the code and with simple change in the [PRERELEASE_PATTERN](https://github.com/googleapis/release-please/blob/a55a85c2384f088f4a7a71ff8a9d4a3c50789bef/src/versioning-strategies/prerelease.ts#L20) regexp and adding separator inside [nextPrerelease](https://github.com/googleapis/release-please/blob/a55a85c2384f088f4a7a71ff8a9d4a3c50789bef/src/versioning-strategies/prerelease.ts#L39) in case if the separator exists, `dot separation` can be supported.

If the core team supports this enhancement then I can create a PR to support this change.

 **Describe alternatives you've considered**

An alternative could be to create a separate [semver v2](https://semver.org/spec/v2.0.0.html) compliant versioning strategy. However, that will be a much bigger scope.

 **Additional context**

While the spec supports many other formatting options. I am not too sure if any of those are part of the roadmap.

**Comment by kalosisz** [comment]
Hey! Look at https://github.com/googleapis/release-please/pull/2083

**Comment by bhvngt** [comment]
Thanks a ton @kalosisz. This should solve my problem. I will close this issue.
