### ISSUE TITLE
Run a command in release PR.

### ISSUE THREAD

**Issue by solankiarpan** [googleapis/release-please#2091]
Every time a release PR is created i want to run one command to modify the code and then commit the changes back into the release PR.
Is this possible to do within release please?

**Comment by TimothyJones** [comment]
Release please doesn't support this directly, but you could put a process together with a github action

**Comment by chingor13** [comment]
> Is this possible to do within release please?

No, this is outside the scope of this library. It runs as a node function and we cannot guarantee the runtime of that code. You would want to build another automation on top of the PR that is created.
