### ISSUE TITLE
changelog-path in a parent folder

### ISSUE THREAD

**Issue by truehumandesign** [googleapis/release-please#2113]
- I am trying to get the CHANGELOG.md generated in the parent folder even if I build a package in a sub-folder
- This is my release-please-config.json for this
```json
{
    "release-type": "rust",
    "packages": {
        "crates/slain-backend": {
            "include-component-in-tag": false
            "changelog-path": "../../CHANGELOG.md"
        }
    }
}
```

- The path just gets appended to the package path e.g. 
`crates/slain-backend/../../CHANGELOG.md` and it is not working

**Comment by chingor13** [comment]
If you use an "absolute path", it will be relative to the root of the repository.

```json
{
  "release-type": "rust",
  "packages": {
    "crates/slain-backend": {
      "include-component-in-tag": false
      "changelog-path": "/CHANGELOG.md"
    }
  }
}
```

**Comment by truehumandesign** [comment]
Thanks for clarifying 👍
