### ISSUE TITLE
"Multiple fixes or features" on PR does not create multiple lines in changelog

### ISSUE THREAD

**Issue by dschach** [googleapis/release-please#2118]
#### Environment details

  - OS: OSX
  - Node.js version: 18.17.1
  - npm version: 10.2.2
  - `release-please` version: action v3, RP v16.1.0

#### Steps to reproduce

  1. Create a PR with the following:
     - Title: chore: update my library
     - Body: 
```
test: tests run faster
  hyperspeed description

style: make CSS pretty
```

  2. Use Squash and Merge to merge to main
  3. You will see that when that PR is merged, only the title goes into the changelog. The docs [seem to say](https://github.com/googleapis/release-please/tree/main?tab=readme-ov-file#what-if-my-pr-contains-multiple-fixes-or-features) that it will make multiple entries.

Am I doing something wrong with my title and description? Does this only work with a commit that is in a PR and not the PR itself?

**Comment by chingor13** [comment]
The "extended" description, if interspersed with the conventional commit messages will break parsing as it's defined in the conventional commit spec's grammar.  Extra commit messages are parsed bottom-up from the footer and anything that doesn't look like a message is then included in the extended description.

```
chore: update my library

test: tests run faster
  hyperspeed description  <-- this is line doesn't look like a conventional commit message

style: make CSS pretty
```
For this commit, release-please would see 2 commit message:
1. `chore: update my library`
2. `style: make CSS pretty`

Also note that release-please by default wouldn't include `chore`, `style`, or `test` commit types in the release notes.
