### ISSUE TITLE
Clean up release branches

### ISSUE THREAD

**Issue by dwsupplee** [googleapis/release-please#212]
Hello 👋,

Thanks for this great tooling. I've got a minor feature request which would help save a few clicks on the consumers end - would we be able to automatically delete release branches after they have been merged or marked inactive?

**Comment by chingor13** [comment]
The core release-please library can't do this because it doesn't listen to events. It's possible to add something on the GitHub app however, with v13, we now re-use branch names. This re-use should alleviate the need to delete a bunch of branches.
