### ISSUE TITLE
Commit body in COMMIT_OVERRIDE

### ISSUE THREAD

**Issue by jlippold** [googleapis/release-please#2136]
The readme shows this, which works as expected:

```
BEGIN_COMMIT_OVERRIDE
feat: add ability to override merged commit message
fix: another message
chore: a third message
END_COMMIT_OVERRIDE
```

I would think the library would also accept a description of the change, but it's not taking. I've tried with various new line placements to no avail.

```
BEGIN_COMMIT_OVERRIDE
feat: add ability to override merged commit message
this is a description of the feat
chore: a third message
this is a description of the chore
END_COMMIT_OVERRIDE
```

Is it currently not possible to override and/or set the description in a comment override?

Thanks for the help!

**Comment by uncenter** [comment]
Is the extended message meant to show up somewhere in the release notes / changelog? I used your example above (for testing) in the body of https://github.com/catppuccin/github-file-explorer-icons/pull/118, and then re-ran my Release Please workflow (which successfully completed and logs showed no issues). However, [the release PR](https://github.com/catppuccin/github-file-explorer-icons/pull/115) doesn't contain anything about my "Some extra note." extended description
