### ISSUE TITLE
Is it possible to define several release types?

### ISSUE THREAD

**Issue by RedstonePfalz** [googleapis/release-please#2148]
Hello,
I have a repository with two subfolders. In one there is a Maven project with a pom.xml and in the second folder there is a Node project. How can I have the pom.xml and the package.json updated automatically?
Many thanks for your help

**Comment by chingor13** [comment]
Yes, you will want to use a manifest config.

Example:
```json
{
  "packages": {
    "path/to/node: {
      "release-type": "node",
      "component": "name-of-node-artifact"
    },
    "path/to/maven: {
      "release-type": "maven",
      "component": "name-of-maven-artifact"
    }
  }
}
```
