### ISSUE TITLE
Help with release-please-action Configuration for a Project with Nested package.json

### ISSUE THREAD

**Issue by jevgenijsblaus** [googleapis/release-please#2155]
Hi GitHub Community,

I'm currently working on a project that has a unique structure and I'm facing challenges configuring the release-please-action correctly. My project structure is as follows:

```
.github/
app/
  |- src/
  |_ package.json
docs/
CHANGELOG.md
README.md
```

My objective is to manage releases for the entire project, encompassing changes both in the root directory and within the app/ directory, where all source files and package managers files like package.json and composer.json are located. However, since the CHANGELOG.md is located in the root of the repository and there is no package.json file at this level, I am seeking a solution to update the changelog as part of the release process managed by release-please-action, despite the absence of package.json in the root directory.

I've tried the following configurations in my release-please-config.json, but I'm encountering errors:

```
{
    "packages": {
        "app": {
            "package-name": "laravel-app"
        },
        ".": {
            "changelog-path": "CHANGELOG.md"
        },
    },
    "changelog-sections": [
        // sections here
    ]
}
```

This configuration results in the following error:

```Error: release-please failed: node (org/laravel-app): Missing required file: package.json```

```
{
    "packages": {
        "app": {
            "package-name": "laravel-app",
            "changelog-path": "./../CHANGELOG.md"
        }
    },
    "changelog-sections": [
        // sections here
    ]
}
```

However, this leads to a different error:

```Error: release-please failed: illegal pathing characters in path: app/../CHANGELOG.md```

I am looking for guidance on how to correctly set up the release-please-config.json for my project structure. Specifically, I need to handle releases for the package in the app/ directory while keeping the CHANGELOG.md in the root directory. Any advice or suggestions on how to configure this properly would be greatly appreciated.

Thank you in advance for your help!

**Comment by chingor13** [comment]
For `changelog-path`, try `/CHANGELOG.md`. An "absolute" path is calculated from the root of the repository.

```
{
    "packages": {
        "app": {
            "package-name": "laravel-app",
            "changelog-path": "/CHANGELOG.md"
        }
    },
    "changelog-sections": [
        // sections here
    ]
}
```

**Comment by jevgenijsblaus** [comment]
@chingor13, thank you for your suggestion to use an "absolute" path for the changelog-path. I tried updating my release-please-config.json as you recommended:

```
{
    "packages": {
        "app": {
            "package-name": "laravel-app",
            "changelog-path": "/CHANGELOG.md"
        }
    },
    "changelog-sections": [
        // sections here
    ]
}
```

However, I'm still encountering an issue where the CHANGELOG.md is being created in the app directory, rather than in the root directory of the repository.

**Comment by chingor13** [comment]
Please ensure that the config is in your release branch.

Tested using the CLI with
* config: https://github.com/chingor13/release-please-playground/blob/debug-2155/release-please-config.json
* command: `node build/src/bin/release-please.js release-pr --token=${GITHUB_TOKEN} --repo-url=chingor13/release-please-playground --target-branch=debug-2155`
* PR: https://github.com/chingor13/release-please-playground/pull/51 which creates the CHANGELOG.md in the root directory
