### ISSUE TITLE
GH action not finding .release-please-manifest.json 

### ISSUE THREAD

**Issue by RicardoE105** [googleapis/release-please#2156]
Thanks for stopping by to ask us a question! Please make sure to include:
- What you're trying to do
   Trying to run release-it-please action for the first time
- What code you've already tried
  I have the same config files in another repo and everything works great! Wonder if it's an issue with the token permissions 
- Any error messages you're getting

<img width="995" alt="image" src="https://github.com/googleapis/release-please/assets/16496553/202c04e6-40e2-48f1-8121-799eaedf8e23">

The file at root of the repo, so not sure why it's not finding the file. See that it seems to find the configuration file that is also in the repo

The error seems to be triggered [here](https://github.com/googleapis/release-please/blob/ea774cbb1ef76ada0897e057016c6ad4bb171104/src/manifest.ts#L1396).

**Comment by chingor13** [comment]
Please add your configuration or a link to it otherwise, all we can do is speculate.

Note that we recently released v4 of the action which changed a bunch of configuration options.

**Comment by chingor13** [comment]
Feel free to reopen when there's more info that we can use to debug.

**Comment by RicardoE105** [comment]
It the token did not have the right permissions! Thanks!
