### ISSUE TITLE
Release Please Notes are not consistently linking to JIRA in Github 

### ISSUE THREAD

**Issue by Drishtantr** [googleapis/release-please#2166]
We are encountering inconsistency in the inclusion of Jira links within our release notes. We use release-please in Github. Although release-please is successfully generating the notes, not all commits are consistently linked to their corresponding Jira issues. We want to have every commit linked to its respective Jira issue within GitHub, and we expect this information to be reflected in the .MD file produced by Release Please.

**Comment by chingor13** [comment]
Release-please does not do anything special for Jira references (nor does GitHub by default). Do you have an example of how this works or would work?
