### ISSUE TITLE
`workspace:*` is updated to a specific version when working with pnpm workspace

### ISSUE THREAD

**Issue by YiCChi** [googleapis/release-please#2173]
Hi! I'm using release-please in a pnpm workspace based monorepo throuth release-please-action to publish packages to a private registry.
It worked well on v3. But once I updated it to v4 I got an error due to `workspace:*`` was updated to a specific version.
I found that release-please-action bump release-please from 15.3 to 16.3 on v4, and the releated PRs are https://github.com/googleapis/release-please/pull/2058 and https://github.com/googleapis/release-please/pull/2117.

According to [pnpm's documentation](https://pnpm.io/workspaces#publishing-workspace-packages), it dynamically replace any `workspace:` dependency. So we don't need to update version of deps manually. And it is what v3 did.
Of course, I can keep using v3, but I want to know if there is any other solution.

here is a repo to reproduce. https://github.com/YiCChi/front-monorepo

- PR created by v3. https://github.com/YiCChi/front-monorepo/pull/32
- PR created by v4. https://github.com/YiCChi/front-monorepo/pull/35

error log

```text
 ERR_PNPM_OUTDATED_LOCKFILE  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is not up to date with packages/math/package.json

Note that in CI environments this setting is true by default. If you still need to run install in such cases, use "pnpm install --no-frozen-lockfile"

    Failure reason:
    specifiers in the lockfile ({"@yicchi/is-even":"workspace:*","@yicchi/is-odd":"workspace:*"}) don't match specs in package.json ({"@yicchi/is-odd":"workspace:*","@yicchi/is-even":"0.9.0"})
```

**Comment by alexander-kuznetsov-fnz** [comment]
yes, it seems that previously lerna handled logic of "workspace:" versioning, now after moving to internal implementation of graph #2117 the only workspace handler left is [that](https://github.com/googleapis/release-please/blob/f78f87b3ec986344c9265a9bd225b92a41aeac23/src/plugins/node-workspace.ts#L480-L486)
```
      if (currentDepVer.startsWith('workspace:')) {
        depUpdates.push(`\n    * ${depName} bumped to ${newVersionString}`);
      } else if (newVersionString !== origDepVer) {
        depUpdates.push(
          `\n    * ${depName} bumped from ${origDepVer} to ${newVersionString}`
        );
        //handle case when "workspace:" version is used
```

**Comment by chrispcampbell** [comment]
Any updates on this issue?  We would like to migrate to v4 of release-please-action, which includes a couple fixes from release-please v16 that we've been waiting for, but our project makes use pnpm and `workspace:*`, so we are stuck in a holding pattern like the original submitter.

**Comment by everyx** [comment]
Is there any workaround？

**Comment by shinebayar-g** [comment]
[Yarn workspaces](https://yarnpkg.com/features/workspaces#cross-references) are also affected. Release please keeps replacing `workspace:^` with hardcoded version.

**Comment by niieani** [comment]
Submitted [a PR with a fix](https://github.com/googleapis/release-please/pull/2281).

**Comment by axeen** [comment]
> Submitted [a PR with a fix](https://github.com/googleapis/release-please/pull/2281).

Could this please be released for [release-please-action v4](https://github.com/googleapis/release-please-action/tree/v4) as well? 🙏  It seems to still use 16.10.2
