### ISSUE TITLE
[PHP] Support tag to show up in release notes for miscellaneous 

### ISSUE THREAD

**Issue by bshaffer** [googleapis/release-please#2189]
We'd like to configure a tag that will allow release notes to appear for things like `deprecations` (see https://github.com/googleapis/google-auth-library-php/commit/8cfb95c04e036e744393a49d6ea404f62f0e0ffc) or other such changes that do not fall under `fix` or `feat`, but are still something we'd like to highlight in our release notes.

The proposal here would be `misc`, where we could do something like `misc(deprecation):` and have it show up in the release notes like this:

```md
### Miscellaneous

**deprecation**: Removed support for lib v2
```

**Comment by chingor13** [comment]
Which changelog sections appear is configurable on a per-repository basis. Please use a `release-please-config.json` configuration and set the `changelog-sections` configuration option: https://github.com/googleapis/release-please/blob/f78f87b3ec986344c9265a9bd225b92a41aeac23/schemas/config.json#L31-L52

This should override the default configuration: https://github.com/googleapis/release-please/blob/f78f87b3ec986344c9265a9bd225b92a41aeac23/src/strategies/php.ts#L24-L36

**Comment by bshaffer** [comment]
@chingor13 this is super helpful, thank you.

I think we DO want to override the base `php` strategy, so that the behavior is consistent across all our repositories
