### ISSUE TITLE
Allow forcing the use of the generic updater in `extra-files`

### ISSUE THREAD

**Issue by LoicFerrot** [googleapis/release-please#2205]
**Is your feature request related to a problem? Please describe.**
Since #2072, any JSON, XML, YAML or TOML file is updated using their corresponding updater, meaning that the value of a top level `version` key, if existing, is bumped. It should be possible to override this default behavior.

My use case is to bump a docker image tag in a `docker-compose.yaml` file, that contains a top-level `version` key, like such:
```yaml
# docker-compose.yaml
version: "3.8"  # Docker version: https://docs.docker.com/compose/compose-file/04-version-and-name/

services:
  my-service:
    ...
    image: my-org/my-repo:v0.1.0 # x-release-please-version
```
I tried two things:

```yaml
"extra-files": ["docker-compose.yaml"]
```
When using this config, the `version: "3.8"` is replaced by `version: v0.1.1`, and the `image` value is left untouched.

```json
"extra-files": [
  {
    "type": "yaml",
    "path": "docker-compose.yaml",
    "jsonpath": "services.my-service.image"
  }
]
```
When using this second config, the `image` value is transformed to `v0.1.1`, deleting the `my-org/my-repo:` part.

 **Describe the solution you'd like**
Allow something like this, that won't attempt to modify the top-level `version`:
```json
"extra-files": [
  {
    "type": "generic",
    "path": "docker-compose.yaml"
  }
]
```

 **Describe alternatives you've considered**
As specified [there](https://docs.docker.com/compose/compose-file/04-version-and-name/), the `version` key is not strictly necessary for a docker-compose file, so removing this key leads to the desired behavior. However, this is only a temporary workaround.

**Comment by regseb** [comment]
The `jsonpath` must begin with a [`$`](https://github.com/googleapis/release-please/blob/HEAD/docs/customizing.md#updating-arbitrary-yaml-files). You'll get an error because [_jsonpath_](https://www.npmjs.com/package/jsonpath) library doesn't support `-` (https://github.com/dchester/jsonpath/issues/90#issuecomment-397335671):

```
Error: release-please failed: Lexical error on line 1. Unrecognized text.
$.services.my-service.image
-------------^
```

The property must be enclosed in quotes:

```JSON
"extra-files": [
  {
    "type": "yaml",
    "path": "docker-compose.yaml",
    "jsonpath": "$.services[\"my-service\"].image"
  }
]
```

**Comment by philippeboyd** [comment]
@regseb this won't work with type as it will reformat the file and remove comments and purge quotes as per issues https://github.com/google-github-actions/release-please-action/issues/896 and https://github.com/googleapis/release-please/issues/2195

We would want to keep the generic updater with yaml files if we want or prevent the yaml updater from reformating the whole file when setting the new version
