### ISSUE TITLE
feat: the include-component-in-tag should default to false

### ISSUE THREAD

**Issue by AnzhiZhang** [googleapis/release-please#2216]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**

From google-github-actions/release-please-action#889, this seems should be default to false. The action is default to false, so it is reasonable to set advanced config corresponding to the action.

 **Describe the solution you'd like**

Set the `include-component-in-tag` default to `false`.

 **Describe alternatives you've considered**

Set it manully.

 **Additional context**

#2076 

Related documents:

https://github.com/googleapis/release-please/blob/72b0ab360c3d6635397e8b02f4d3f9f53932e23c/schemas/config.json#L77-L80

https://github.com/googleapis/release-please/blob/72b0ab360c3d6635397e8b02f4d3f9f53932e23c/docs/manifest-releaser.md?plain=1#L314-L337

**Comment by chingor13** [comment]
This behavior is for historical reasons and changing the default would be a breaking change (and a large disruption to existing users).

Originally, release-please-action was targeted only for single component repositories (i.e. 1 repository : 1 library). So the default behavior was to assume the repository only has a single component and thus have no component name in the created tag. FWIW, https://github.com/google-github-actions/release-please-action/pull/889 was to fix a regression to restore the default to `false` for the action.

The manifest configuration file was originally only for monorepos that have > 1 component and so the default was to include the component name in the tags.
