### ISSUE TITLE
Release multiple packages without prefix

### ISSUE THREAD

**Issue by bhuism** [googleapis/release-please#2223]
Hello, I've read the docs and relevant issues.

Should it at all be possible the release multiple packages (with github) without a prefix (component tag)?

When I use: ```include-component-in-tag: false``` only one (the root?) package seems to be considered.

If I understand correctly this configuration should give my desired behaviour:

```bash
{
  "$schema": "https://raw.githubusercontent.com/googleapis/release-please/main/schemas/config.json",
  "include-component-in-tag": false,
  "packages": {
    ".": {
      "release-type": "node",
      "exclude-paths": ["deploy"],
      "component": "node"
    },
    "deploy/helm": {
      "release-type": "helm",
      "component": "helm"
    }
  },
  "plugins": [
    {
      "type": "linked-versions",
      "groupName": "One release to rule them all",
      "components": ["node", "helm"]
    }
  ]
}
```

I this behaviour possible?

**Comment by chingor13** [comment]
`include-component-in-tag` can be set on individual packages.

This should work:
```
{
  "$schema": "https://raw.githubusercontent.com/googleapis/release-please/main/schemas/config.json",
  "packages": {
    ".": {
      "release-type": "node",
      "exclude-paths": ["deploy"],
      "include-component-in-tag": false,
      "component": "node"
    },
    "deploy/helm": {
      "release-type": "helm",
      "component": "helm"
    }
  },
  "plugins": [
    {
      "type": "linked-versions",
      "groupName": "One release to rule them all",
      "components": ["node", "helm"]
    }
  ]
}
```

**Comment by bhuism** [comment]
Thanks Jeff, am afraid that config does not work, now it only considers the
first ("node") component like so:

https://github.com/bhuism/nextjstryout2/pull/51/files

When ```include-component-in-tag``` is used anywhere, only one package is
considered

When no include-component-in-tag is used, I see noth packages considered
like so:

https://github.com/bhuism/nextjstryout2/pull/49

but then I have the prefixes in the release tag

**Comment by bhuism** [comment]
I did get what I wanted with extra-files 🙇🏻‍♂️
