### ISSUE TITLE
php strategy should upgrade composer.lock hash if present

### ISSUE THREAD

**Issue by Tbaile** [googleapis/release-please#2274]
Hello!
When releasing a tag using release-please in a php project, the `content-hash` part of the `composer.lock` file is kept unchanged. This triggers warnings in composer due to the `composer.json` file may not be synced with the `composer.lock`.
This is a kink of composer, due to the fact that no other dependency manager that I know of does this (release please works like a breeze in nodejs projects).

I've looked up in the code and the only reasonable way to do this is adding an `Update` in the [`src/strategies/php.ts`](https://github.com/googleapis/release-please/blob/main/src/strategies/php.ts). But this cannot be done due to the fact that I need to change the `composer.lock` based off the now updated `composer.json` file, and the `Update` interface does not support multiple paths where to load the file from.

Any suggestions on how to implement this?

**Comment by JuanVqz** [comment]
Hey! Something similar happened to me with Ruby, please-release updates the version.rb but does not includes the Gemfile.lock in the release PR, how can we include the lock file? Thanks!

**Comment by Tbaile** [comment]
In the end, I've ended up removing the field entirely, as stated by the [composer json schema](https://getcomposer.org/doc/04-schema.md#version), the version field should be omitted entirely.

I hanno no clue how ruby handles the releases tho, maybe it can be safely removed too?

**Comment by JuanVqz** [comment]
yes, we can remove it as well, but I'll continue to update it manually
