### ISSUE TITLE
The release-please GitHub action no longer works after the GitHub Organization URL was changed from `google-github-actions` to `googleapis`

### ISSUE THREAD

**Issue by sebmellen** [googleapis/release-please#2288]
#### Steps to reproduce

  1. Attempt to use the `release-please` GitHub action with `- uses: google-github-actions/release-please-action@main`
  2. You will receive the following error `Error: Unable to resolve action. Repository not found: google-github-actions/release-please-action`

See https://github.com/googleapis/release-please-action/issues/980 for more context.

I have opened a PR to resolve this here: https://github.com/googleapis/release-please/pull/2287.

**Comment by agrahamlincoln** [comment]
relevant issue from the action's repository: https://github.com/googleapis/release-please-action/issues/980
