### ISSUE TITLE
Formatting `package.json` is changed by release-please

### ISSUE THREAD

**Issue by nico-w** [googleapis/release-please#2319]
Similar to the issue here https://github.com/googleapis/release-please/issues/777, the format shouldn't change.

#### Environment details

  - OS: Ubuntu 22.04.4
  - Node.js version: 20.14.0
  - `release-please` version: The one used by the latest release-please-action@v4.1

#### Steps to reproduce

  1. Having a `package.json` with arrays, e.g. `sideEffects` or `workspaces` - have them in a single line. We're using [biome](https://github.com/biomejs/biome) for that.
  2. Observe that on the release-please branch those properties have changed to an incompatible format.
  
Example:
  
```shell
diff --git a/package.json b/package.json
--- a/package.json
+++ b/package.json
@@ -32,10 +32,7 @@
-  "workspaces": [
-    "apps/*",
-    "packages/*"
-  ],
+  "workspaces": ["apps/*", "packages/*"],
```
and
```
diff --git a/packages/XYZ/package.json b/packages/XYZ/package.json
--- a/packages/XYZ/package.json
+++ b/packages/XYZ/package.json
@@ -4,9 +4,7 @@
-  "sideEffects": [
-    "./src/entrypoints/*.tsx"
-  ],
+  "sideEffects": ["./src/entrypoints/*.tsx"],
  ```

Thanks a ton!

**Comment by simonostendorf** [comment]
I have the same problem with prettier and a custom json file.

**Comment by chingor13** [comment]
Similar to https://github.com/googleapis/release-please/issues/2085, this is not something we are in a position to maintain. Formatting is a personal choice and we cannot feasibly configure formatting for every file type, nor do we plan to run any post-processing binaries.

Users are free to run post-processing on the release-please PRs to "clean up" formatting.

**Comment by lindenquan** [comment]
This is bug. It shouldn't be closed. release-please shouldn't change the format of package.json, but it does.
The root cause is [jsonStringify](https://github.com/googleapis/release-please/blob/64ffba96734bf158818121c067870077d903611b/src/util/json-stringify.ts#L17) changed the format.
