### ISSUE TITLE
Can a component be a single file?

### ISSUE THREAD

**Issue by sysadmiral** [googleapis/release-please#2325]
- What you're trying to do
I'm trying to create some centralised github reusable workflows. Workflows can only be called from a remote repo if they are under `.github/workflows/` in the remote. I'd like to version each workflow separately but it's unclear from the docs if the `path` in a manifest can be a single file.
- What code you've already tried
I'm still piecing this together so I will post an update to this.
I have tried:
- workflows in separate dirs
  - this works for release-please as I can treat each workflow as a component
  - this doesn't work for github workflow calls as mentioned previously
I am about to try:
- workflows in `.github/workflows`
  - I suspect this won't work for release-please but I will report back with findings (I'll create a docs update if this is the case)
- Any error messages you're getting

**Comment by sysadmiral** [comment]
After testing it would seem the path of a package cannot be a single file. I'll create a docs update to make this a little clearer.

**Comment by jizusun** [comment]
Hi @sysadmiral  I'm trying to manage different reusable workflows in a single repo with `release-please`.

As reported with Github Actions run
> invalid value workflow reference: workflows must be defined at the top level of the .github/workflows/ directory

There is no way to put a reusable workflows file in a subdirectory to make it a path.

Do you have any solution for this?
