### ISSUE TITLE
Unable to configure signoff commits in config

### ISSUE THREAD

**Issue by mysteq** [googleapis/release-please#2333]
#### Environment details

  - OS: ubuntu-latest
  - Node.js version: N/A (run via release-please-action GitHub Action)
  - npm version: N/A (run via release-please-action GitHub Action)
  - `release-please` version: 16.12.0 (run via release-please-action GitHub Action)

#### Steps to reproduce

1. Add $.signoff to config as [per documentation of release-please-action](https://github.com/google-github-actions/release-please-action?tab=readme-ov-file#package-options)

```json
{
  "signoff": "foo <foo@users.noreply.github.com>",
  "packages": {
    ".": {
      "release-type": "simple"
    }
  }
}
```

2. Run release-please

3. Example relevant output from debug-config

```
....
separatePullRequests: true,
fork: false,
signoffUser: undefined,
releaseLabels: [ 'autorelease: tagged' ],
labels: [ 'autorelease: pending' ],
....
```

This issue is related to https://github.com/google-github-actions/release-please-action/issues/904  and also seems to have been tried to be solved here https://github.com/googleapis/release-please/issues/2246 .

**Comment by shanduur** [comment]
Can we reopen this issue? The signoff option never worked.

**Comment by mysteq** [comment]
At least using it with the Github Action v4.1.4 or newer works for me
