### ISSUE TITLE
Release please doesn't take into account multiple commit lines in BEGIN_NESTED_COMMIT

### ISSUE THREAD

**Issue by bshaffer** [googleapis/release-please#2352]
See https://github.com/googleapis/google-cloud-php/pull/7579

The conventional commit messages in `BEGIN_NESTED_COMMIT` do not show up in the release PR, and so the version is not appropriately incremented.

```
BEGIN_NESTED_COMMIT
feat: [Dialogflow] Add Proactive Generative Knowledge Assist endpoints and types
feat: Add Generator related services and types
...
END_NESTED_COMMIT
```

We had to use `BEGIN_COMMIT_OVERRIDE` because only the `chore` in the title was looked at for the [release PR](https://github.com/googleapis/google-cloud-php/pull/7593).

The expected behavior is that owlbot also includes the nested conventional commits in the release, instead of just the most recent one.

**Comment by chingor13** [comment]
This was because the commit that hit `main` was incorrectly formatted. If the PR body were used, then it would have worked.
