### ISSUE TITLE
Why does the version number not change with commits?

### ISSUE THREAD

**Issue by OXY2DEV** [googleapis/release-please#2353]
## What I am trying to do

I am trying to get `release-please` to bump the PATCH number as new `fix` commits are added.

## Expected behavior

`release-please` increases the PATCH version number by 1 on every `fix` commit.

## Actual behavior

`release-please` only chnaged the version for the initial commit but didn't change the number for any of the commits done after that.

![Screenshot_2024-08-10-07-57-35-244_mark via gp-edit](https://github.com/user-attachments/assets/0557c6a5-504d-4955-a801-bcb508f422e1)

Why is it adding fixes to the list but not increasing the version number?

**Comment by chingor13** [comment]
Without a repro, we cannot hypothesize at what's happening. Please try troubleshooting with https://github.com/googleapis/release-please/blob/main/docs/troubleshooting.md
