### ISSUE TITLE
[Bug] Commit override duplicates comments for each commit

### ISSUE THREAD

**Issue by legobeat** [googleapis/release-please#2355]
#### Environment details

  - `release-please` version: 16.12.0

#### Steps to reproduce

  1. Create PR with `n` > 1 commits
  2. Merge PR using GitHub Web UI "Rebase and merge" button
    - Default branch now has `n` new commits
  3. Edit PR body and replace with [commit override](https://github.com/googleapis/release-please?tab=readme-ov-file#how-can-i-fix-release-notes) message
  4. Rerun release-please workflow

Release notes will now contain the same new message `n` times, one for each commit in the original PR, with a link to the commit hash of each.

### Related
- Previously reported in https://github.com/googleapis/release-please/issues/2188#issuecomment-2262268972. It's not clear why that issue was closed as "completed" @chingor13 ?

**Comment by chingor13** [comment]
Release-please needs a [linear git commit history](https://github.com/googleapis/release-please?tab=readme-ov-file#linear-git-commit-history-use-squash-merge). If you do a rebase and merge, it is committing `n` commit messages to main and the override cannot group them (they may not even be in order in commit history).

**Comment by legobeat** [comment]
@chingor13 These cases are all with linear commit history, though, no merge commits involved...?
