### ISSUE TITLE
[python] release-please creating release PRs with the wrong version

### ISSUE THREAD

**Issue by danieleades** [googleapis/release-please#2371]
Release-please is bumping my project version from `0.2.3` to `0.1.0`

see https://github.com/danieleades/sphinx-graph/pull/174

Context:
- I've recently introduced `release-please`, there are no previous tags
- the version is set in a `pyproject.toml` file
- the package is published on Pypi

**Comment by chingor13** [comment]
We highly recommend using the "manifest config" -- a config file and versions file. See https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md

Otherwise, release-please relies on the latest tag/release in order to determine the next version. Since you do not have any tags, it assumes this is an initial release and defaults to 0.1.0 (for python).

**Comment by danieleades** [comment]
> We highly recommend using the "manifest config" -- a config file and versions file. See https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md
> 
> Otherwise, release-please relies on the latest tag/release in order to determine the next version. Since you do not have any tags, it assumes this is an initial release and defaults to 0.1.0 (for python).

ah that's a shame. I was expecting similar behaviour to the rust-specific 'release-plz' which also polls the registry for existing published versions

**Comment by danieleades** [comment]
@chingor13 this doesn't appear to have worked the way i expected.

I added a manifest as per the instructions in your link:

> # Initial Version
> The simplest way to tell release-please the current version for a package it has never released before is to manually add an entry into .release-please-manifest.json. This change should be made directly on the default/configured branch or on a separate, user-created branch/PR which is then merged into the default/configured branch.
> ```json
> {
>   "path/to/pkg": "1.1.1"
> }
> ```
> release-please will now use "1.1.1" as the last-released/current version for "path/to/pkg" and suggest the next version according to coventional commits it has found since the last merged release PR (or "bootstrap-sha" if this is the first run).

`release-please` has just changed the value in the manifest, rather than using it as the first release version as indicated by the docs:

https://github.com/danieleades/sphinx-graph/pull/174/files
