### ISSUE TITLE
How to work around potential hotfix version clashes under the default versioning strategy?

### ISSUE THREAD

**Issue by michaelowolf** [googleapis/release-please#2407]
I'm trying to support a trunk-based workflow for an application, in which we have the possibility of releasing hotfixes made against a live release version. The aim would be to follow the default versioning strategy for "scheduled" releases, while bumping the patch version for hotfixes. Hotfixes would be backported into the trunk branch (although I don't think this directly impacts the question).

I haven't been able to test this workflow thoroughly, but if I understand correctly then it is achievable with Release Please with one caveat - when the next scheduled release includes only bug fixes, it would produce the same version as the hotfix release:

```
trunk      feat: a --- v1.1.0 ---- fix: b ----- fix: c (backport) --- v1.1.1 (scheduled)
                           \                           /
hotfix/c                    \ --- fix: c (hotfix) --- / --- v1.1.1 (hotfix)

```

This seems undesirable.

I've considered a few options as to how we can work around this edge case:

1. Take a different versioning strategy for scheduled vs. hotfix releases. As an example, we could use `always-bump-minor` for scheduled releases, and `always-bump-patch` for hotfixes. However, with the requirement to use a manifest file to configure the versioning strategy it seems awkward to achieve this (compared to e.g. providing it as an input through the GitHub action), and I'd prefer to keep the breaking changes behaviour of the default strategy.
2. Add [`release-as` commits](https://github.com/googleapis/release-please?tab=readme-ov-file#how-do-i-change-the-version-number) to the trunk branch after a hotfix, to try to manually set the next scheduled release version. However, that forces us to manually keep track of what commits have landed in trunk, and removes the benefit of using a tool like Release Please.
3. Add empty `feat` commits to the trunk branch after a hotfix, to guarantee the minor version will be bumped for the next scheduled release. This seems the most likely option currently.
4. There is some suggestion that it's possible to [create a new versioning strategy](https://github.com/googleapis/release-please/blob/main/docs/customizing.md#versioning-strategies), but this seems more aimed at creating new predefined strategies that would be bundled with Release Please, as I can't see how we could implement and configure the use of an ad-hoc versioning strategy on a per-case basis. This would probably be my ideal solution as it would give us full control over the versioning strategy (ideally inheriting from the predefined strategies).

I'm wondering if my conclusions to far are correct and, if so, whether there's any advice for handling this case?

**Comment by michaelowolf** [comment]
One other option I forget - I can't see that it's possible with Release Please, but if we could configure custom Conventional Commit types within a versioning strategy (e.g. "backport" -> minor bump), then we might also have a way to address this.

**Comment by michaelowolf** [comment]
Having put a bit more time into this, I’ve realised the first option is much easier than I had thought - it’s trivial to implement a release config per branch pattern (we use the GitHub action, so we can simply change which config file we point to based on the branch that triggered the workflow). We can then just include a `release-as` commit on our trunk branch if we ever want to bump the major version.

I do think there could be potentially be some improvement to the ease of implementing more intricate/non-standard versioning strategies, but it's not crucial for our requirements. Going to close this off.

**Comment by ddennis** [comment]
@michaelowolf Thanks for sharing 👍
