### ISSUE TITLE
How to get release-please to recognize multiple commits in squash merge

### ISSUE THREAD

**Issue by iton0** [googleapis/release-please#2438]
Thanks for stopping by to ask us a question! Please make sure to include:
- I am trying to squash and merge multiple commits on a PR such that the release will show all of the fixes and feats.
- I checked the README.md and looked at some of the issues related this (#2358 & #2357) but to no avail.
- Any error messages you're getting

**Comment by jcazallasc** [comment]
Could we have any update on this? I'm in the same situation

**Comment by Achllle** [comment]
It's surprising to say the least that squash merging is recommended but squash merge commits don't follow conventional commit structure and so are ignored. Or am I missing something?
@iton0 can you shed any light as to why this isn't supported?

**Comment by iton0** [comment]
> It's surprising to say the least that squash merging is recommended but squash merge commits don't follow conventional commit structure and so are ignored. Or am I missing something?
> @iton0 can you shed any light as to why this isn't supported?

Honestly not sure. What worked for me (and why I closed the issue) that produced similar results was to use the "Rebase and merge" button via the GitHub UI. I found this way I can have multiple commits on a PR and the changelog.md will reflect all of them. I hope that helps.
