### ISSUE TITLE
Manually tagging a release causes permissions issues with future release PRs

### ISSUE THREAD

**Issue by dwsupplee** [googleapis/release-please#258]
Kokoro was experiencing an outage and we needed to get a release out so we manually tagged, circumventing the autorelease process. This prevented subsequent release PRs from being generated with the failure message `command github-release failed with status 401` (See full log [here](https://sponge.corp.google.com/target?id=0da812ce-8fe1-4794-b0ff-730f34fb3875&target=cloud-devrel%2Fclient-libraries%2Fnodejs%2Fcontinuous%2Fgoogleapis%2Fgoogle-cloud-php%2Fnode10%2Ftest&searchFor=)).

As per @bcoe's suggestion, adding the `autorelease-closed` label to [the release PR](https://github.com/googleapis/google-cloud-php/pull/2265) resolved the 401 - but it may be worth further investigating why this occurred in the first place.

**Comment by bcoe** [comment]
@dwsupplee I think this would be solved by moving over to a GitHub app for releases. @chingor13 has added a feature which allows you to add a label to re-generate the release.

**Comment by bcoe** [comment]
switching this one to process, @dwsupplee I think it would be worth switching to a GitHub App eventually, which will ensure branches are created by the same automation user (which should help avoid the permission issue you bumped into here).

**Comment by chingor13** [comment]
I'm going to close this one because it's a usage issue, not a release-please issue. Whatever is running release-please should be consistent.
