### ISSUE TITLE
Open / close PR state is flapping

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/release-please#278]
I was taking a look at this PR:
https://github.com/googleapis/nodejs-tasks/pull/279

It looks like any time there was a push to master while the PR was open, the release PR got closed and then re-opened. Every time this happens, it pushes another GitHub notification to anyone watching the repo, and generally just generates a lot of noise.  It would be nice to clean this up :)

**Comment by chingor13** [comment]
Fixed since v6.0.0 in #536 with the switch to code-suggester.
