### ISSUE TITLE
[TESTING GH ACTIONS] proposal for next release

### ISSUE THREAD

**Issue by bcoe** [googleapis/release-please#29]
testing the concept of a next release issue, which will always contain information about the next release that would go out the door.

**Comment by bcoe** [comment]
this should result in a release.

**Comment by bcoe** [comment]
this seems like it should be working

**Comment by bcoe** [comment]
release please

**Comment by bcoe** [comment]
release please

**Comment by bcoe** [comment]
release-please

**Comment by bcoe** [comment]
this should create a release.

**Comment by evocateur** [comment]
:shipit:

**Comment by bcoe** [comment]
release please.
