### ISSUE TITLE
feat: parse footer for release-as, which should take precedence

### ISSUE THREAD

**Issue by bcoe** [googleapis/release-please#293]
to allow a bump from `0.x.x` to `1.0.0`, let's allow folks to provide a `Relese-As:` footer, it would look something like this:

```
feat: we are going ga \o/

Release-As: 1.0.0
```

**Comment by dazuma** [comment]
What would the semantics be if there are multiple commits with different `Release-As` notations?

**Comment by bcoe** [comment]
perhaps take the most chronologically recent?
