### ISSUE TITLE
All commits are [skip ci]

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/release-please#312]
Now that I have the bot set up in https://github.com/google/gts/pull/390, I noticed that all of the commits have [skip ci] on them.  This, predictably, is causing CI to get skipped :)

**Comment by bcoe** [comment]
let's make this a config setting, the skip is required for or PHP mono-repo, but not other repos.

**Comment by chingor13** [comment]
This is fixed now that we're using code-suggester under the hood and it's making a single commit
