### ISSUE TITLE
Create documentation for release-please.yml

### ISSUE THREAD

**Issue by leone145** [googleapis/release-please#416]
**Is your feature request related to a problem? Please describe.**
No clear instructions for the release-please.yml in main documentation.
 **Describe the solution you'd like**
Explain where to place the file and options within it as described here https://github.com/googleapis/repo-automation-bots/tree/master/packages/release-please

**Comment by bcoe** [comment]
@leone145 we should add a section on the GitHub app, thanks for the recommendation.

**Comment by chingor13** [comment]
This was added to the [README](https://github.com/googleapis/release-please#running-as-a-github-app) as a link to the GitHub app's documentation.
