### ISSUE TITLE
Have the ability to insert major, minor and revision constants into source files.

### ISSUE THREAD

**Issue by dpcollins-google** [googleapis/release-please#435]
It should be possible to access the version of a library in code. Currently this is (afaik) only possible in java with https://googleapis.dev/java/gax/latest/com/google/api/gax/core/GaxProperties.html#getLibraryVersion-java.lang.Class-, which reaches into the maven metadata to do so.

It would be useful to be able to paste MAJOR_VERSION = x MINOR_VERSION = y, REVISION = z constants in each language, or even just the numbers representing them by regex substitution into source files upon release.

**Comment by bcoe** [comment]
@dpcollins-google the way folks tend to do this in the Node.js community is to `require('package.json')`, as Node.js allows you to require JSON, and the version is in the `package.json` file.

I'd would be curious to know the best way to approach this for Python, happy to add language specific stuff like this.

**Comment by chingor13** [comment]
We now support an `extraFiles` option which, for Java, will do it's standard version replacements (via those special comment annotations) in arbitrary files configured. Here's an example in the Bigtable repo: https://github.com/googleapis/java-bigtable/pull/715/files#diff-35de1d9d9feb5d407dc0e1ca40e9490c335cdd441607bdaf49f8c1bb0a5e0c7d

For other languages, we would want something similar - a generic way to mark what versions need to be updated.

**Comment by chingor13** [comment]
Note: code search is a very expensive API call, so we cannot be consistently searching across all the source for a variety of patterns. Since the source file will likely differ from project to project, a configurable list of extra files to consider seems reasonable.

**Comment by chingor13** [comment]
Also related to #305
