### ISSUE TITLE
release-please rewrites indentation on package.json

### ISSUE THREAD

**Issue by coreyfarrell** [googleapis/release-please#453]
#### Environment details

Tested with Github action bcoe/release-please-action@1.2.1 (uses release-please@5.2.0).

#### Steps to reproduce

1. Setup release-please-action on a repository with tab indented package.json
2. Wait for release to be requested
3. Note that PR changes all indentation of package.json to 2 spaces, example cfware/fastify-babel#45.

Other tools like `standard-version` seem to detect the existing indentation and leave it alone.

**Comment by coreyfarrell** [comment]
I did a little digging, `standard-version` updates package.json at https://github.com/conventional-changelog/standard-version/blob/master/lib/updaters/types/json.js.  Fixing this issue in `src/updaters/package-json.ts` seems like a simple enough change but I'm not sure how to add a test for this.  TBH I struggle with all but the simplest changes to TS projects.

**Comment by bcoe** [comment]
Hey @coreyfarrell I'd be happy to take this on, thanks for the request 👍 excited to have you using it.
