### ISSUE TITLE
Python: Add commits of type `docs` to the changelog

### ISSUE THREAD

**Issue by busunkim96** [googleapis/release-please#459]
See https://github.com/googleapis/python-pubsub/pull/117#issuecomment-641789106

Also clarify that it is normal to not see all the commits listed in the release notes. (This has been a point of confusion a few times in the Python repositories).

CC @plamut

**Comment by bcoe** [comment]
@busunkim96 👋 this can be configured. I think we can use the same approach we used for Ruby for Python:

https://github.com/googleapis/release-please/blob/master/src/releasers/ruby-yoshi.ts#L29

**Comment by jcornaz** [comment]
> this can be configured.

Great!

How do we configure it? Can you point to some documentation please?

**Comment by busunkim96** [comment]
@jcornaz The [PR](https://github.com/googleapis/release-please/pull/460/files) shows an example of this

**Comment by busunkim96** [comment]
Closing as the original issue is resolved.

**Comment by jcornaz** [comment]
> @jcornaz The PR shows an example of this

I don't understand. That's a code change in this repository.

Does it mean that the only way to "configure" is to actually fork this repository and change the code?

Nevertheless as this issue is closed should I open a new issue for adding the documentation?

**Comment by busunkim96** [comment]
@jcornaz 👍  I think opening a new issue with your question would be best.

**Comment by jcornaz** [comment]
@busunkim96 I created #511

**Comment by tswast** [comment]
Has this been reverted by https://github.com/googleapis/release-please/pull/1104#pullrequestreview-820573534?
