### ISSUE TITLE
Apply multiple file updates in a single commit

### ISSUE THREAD

**Issue by socsieng** [googleapis/release-please#469]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**

Each file that is updated by `release-please` has it's own commit. This is presumably because it is using the [Contents API](https://developer.github.com/v3/repos/contents/).

> For example, the [Contents API](https://developer.github.com/v3/repos/contents/) generates a git commit for each addition or change and uses the current time as the timestamp.

When one or two files are updated, this isn't as much of an issue, however, this is less than ideal once more files are updated (e.g. the addition of `package-lock.json` with #464).

 **Describe the solution you'd like**

Ideally, all the updates related to the version number bump would be applied in a single commit. It looks like this could technically be achieved by using the [Commits API](https://developer.github.com/v3/git/commits/).

Using the Commits API looks more complicated than the Contents API so I can understand if you don't think the increase in complexity is unjustified.

 **Describe alternatives you've considered**

The alternative is to continue with individual commits and remember to merge the release pull request with the squash and merge option.

 **Additional context**

![Example of commits with three changes](https://user-images.githubusercontent.com/2647062/84606353-4409bd00-ae5a-11ea-9632-730f85d70df4.png)
_Example of commits with three changes_

**Comment by chingor13** [comment]
This was completed in #536 and released in v6.0.0. We now use the code-suggester library to create the commit/pull request.
