### ISSUE TITLE
Automatic detection of default branch doesn't work for private repositories

### ISSUE THREAD

**Issue by mateuszpodraza** [googleapis/release-please#474]
#### Environment details

  - OS: macOS Catalina 10.15.5
  - Node.js version: 12.18.1
  - npm version: 6.14.5
  - `release-please` version: 5.4.0

#### Steps to reproduce
Trying from CLI is enough, although the same can be reproduced using a Github action
  
  1. Try and create a release PR for a private repository, with a token that does have access to it
  2. Automatic detection of the default branch fails with `404 Not found`:
```
✔ found 3 commits since 2cdb083e8574b07991fcc1f6332bb84c8263d71f
✔ release as minor: There are 0 BREAKING CHANGES and 1 features
✖ branch release-v2.3.0 already exists
✔ updating CHANGELOG.md
✔ updating package.json from 2.2.2 to 2.3.0
✔ updating package-lock.json from 2.2.2 to 2.3.0
✖ file samples/package.json did not exist
command release-pr failed with status 404
```

When I've hooked a debugger into the process I noticed that the `GET /repos/:owner/:repo` call to Github's API does not have an authorisation header at all, but I didn't spend enough time looking through https://github.com/googleapis/release-please/pull/468 to figure out why.

There is a simple workaround - specifying the default brach manually allows release-please to continue.

**Comment by bcoe** [comment]
@mateuszpodraza thank you for the bug report 👍 I could have sworn the client was authenticated during instantiation (I will need to dig into this).

**Comment by lancedikson** [comment]
I ran into the same issue today. The same problem is failing our release-please gh action, and there's no such a way to use a workaround by specifying the default branch manually as there's no such input param in the action. So, I dug deeper a bit and it seems that octokit expects headers in the `repos.get` method as well.

**Comment by lancedikson** [comment]
This bug is the only obstacle we have on the way of using release-please action in our team processes, so @bcoe I would appreciate if you could take a look at this PR soonish 🙏

**Comment by lancedikson** [comment]
While the fix is not released I came up with a fork that heels the bug — may be useful for somebody else, who encountered the issue. You can use this action as for now:
```yaml
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: lancedikson/release-please-action@tmp-patch-release-please-version
```

**Comment by jef** [comment]
Thanks @bcoe !
