### ISSUE TITLE
Too large blob to fetch via the Github API

### ISSUE THREAD

**Issue by lancedikson** [googleapis/release-please#546]
#### Short overview

In a nutshell, release-please can't handle big files (**bigger than 1 MB**) due to the limitations of Github API. This may cause the bug with release-please not being able to prepare a change-set for a PR.
![image](https://user-images.githubusercontent.com/1955931/92790537-889ee900-f3b4-11ea-9ade-00a63ab758d6.png)

#### Environment details

  - OS: MacOS and Github Actions (Linux)
  - Node.js version: 12.3.1
  - npm version: 6.13.4
  - `release-please` version: 6.1.0

#### Steps to reproduce

  1. Fork [the example repo](https://github.com/lancedikson/release-please-403-example) I created for reproducing the error and run `release-please` locally, or via Github Actions. 

Here's an example of a failed Action: https://github.com/lancedikson/release-please-403-example/actions/runs/248586960

#### Error details

Here's  an example of a stack trace we're getting in a private repo, but it's fully reproducible from the example repo:
```
---------
HttpError: This API returns blobs up to 1 MB in size. The requested blob is too large to fetch via the API, but you can use the Git Data API to request blobs up to 100 MB in size.: {"resource":"Blob","field":"data","code":"too_large"}
    at /home/an/.nvm/versions/node/v12.18.3/lib/node_modules/release-please/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async GitHub.getChangeSet (/home/an/.nvm/versions/node/v12.18.3/lib/node_modules/release-please/build/src/github.js:475:31)
    at async GitHub.openPR (/home/an/.nvm/versions/node/v12.18.3/lib/node_modules/release-please/build/src/github.js:434:25)
    at async Node.openPR (/home/an/.nvm/versions/node/v12.18.3/lib/node_modules/release-please/build/src/release-pr.js:158:20)
    at async Node._run (/home/an/.nvm/versions/node/v12.18.3/lib/node_modules/release-please/build/src/releasers/node.js:83:9)
```

**Comment by bcoe** [comment]
@lancedikson sorry it took me a little while to get a release out the door, `release-please-action@2.4.0` should have this functionality now. Let me know if it does the trick for you?

**Comment by lancedikson** [comment]
@bcoe, thanks for the release, yes, it works just fine. Closing the issue.
