### ISSUE TITLE
Cannot make release PR

### ISSUE THREAD

**Issue by ocervell** [googleapis/release-please#555]
I'm getting an error trying to make a new release PR:
```
release-please release-pr --repo-url=google/slo-generator --token=<MY_TOKEN> --package-name=slo-generator
✖ pull #21 2790f8765db7e628f7eeea1e8016971b05b13225 has not yet been released
```
Pull request in question is [here](https://github.com/google/slo-generator/pull/21) and has been merged to master.

Could you please help ?

**Comment by ocervell** [comment]
Seems like the release PR was not correctly tagged `autorelease: tagged`, so had to do it manually. 

I'm now getting:

```
release-please release-pr --repo-url=google/slo-generator --token=<MY_TOKEN> --package-name=slo-generator
✔ found 6 commits since 2790f8765db7e628f7eeea1e8016971b05b13225
✔ release as minor: There are 0 BREAKING CHANGES and 1 features
command release-pr failed with status 404
```

**Comment by bcoe** [comment]
@ocervell my hunch is that this is potentially permission related, it might be easiest for us to dig into this together.

**Comment by bcoe** [comment]
I see your issue based on that error message, I think it's using the default release type `node`, but the type should be `python`. I'm looking at your upstream repository, and it looks like `python` is configured, so wondering if perhaps you worked through this?
