### ISSUE TITLE
Python: update 'version.py' in release PRs

### ISSUE THREAD

**Issue by tseaver** [googleapis/release-please#579]
@crwilcox It looks like PR #560 added support for reading the version from `version.py`, but not for updating it.  See:

https://github.com/googleapis/python-cloud-core/pull/41#issuecomment-704464276

**Comment by tseaver** [comment]
FWIW, the most recent `python-api-core` release *did* have `version.py` [updated](https://www.github.com/googleapis/python-api-core/commit/d480d97e41cd6705325b3b649360553a83c23f47) by the bot.

**Comment by crwilcox** [comment]
@tseaver the issue is the way we detect files (via an index). I closed and restarted release-please and all is well.
