### ISSUE TITLE
Provide an option to omit the package name in GitHub release name

### ISSUE THREAD

**Issue by weareoutman** [googleapis/release-please#612]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
The auto created GitHub release name is verbose and may make the version number invisible.

![image](https://user-images.githubusercontent.com/2338946/97593707-e8bd1d80-1a3c-11eb-82cd-47f85fa7160f.png)

 **Describe the solution you'd like**
Provide an option to omit the package name in GitHub release name.

 **Describe alternatives you've considered**
Or make it be omitted by default.

 **Additional context**
N/A

**Comment by P4sca1** [comment]
It would be great if there was an option to configure a tag prefix, instead of just having an option to omit the package name.
I have something like this in mind: `--tag-prefix=myPackage@`. This would result in a tag of `myPackage@1.0.0` for example.

**Comment by chingor13** [comment]
In v13 (releasing soon), there is a `includeComponentInTag` option which is surfaced in the CLI via the `--monorepo-tags` option or `include-component-in-tag` in the manifest config. If you are making a standalone release (i.e. not using a manifest config), this option defaults to false so it will not include the component name in the tag.
