### ISSUE TITLE
[Terraform] Update submodule README versions

### ISSUE THREAD

**Issue by morgante** [googleapis/release-please#637]
Currently, the Terraform module releaser only [updates](https://github.com/googleapis/release-please/blob/master/src/releasers/terraform-module.ts#L81-L88) the root README. Instead, it should update the version tag in all submodules so that examples don't get out of date ([context](https://github.com/terraform-google-modules/terraform-google-lb-http/pull/140)).

**Comment by morgante** [comment]
I can take this.

**Comment by bharathkkb** [comment]
An approach similar to versions.tf for submodules should work
https://github.com/googleapis/release-please/blob/6b654ae17cb00f79103b8b58ed73d081d0b85c9a/src/releasers/terraform-module.ts#L90
