### ISSUE TITLE
Fail to update pom file versions when proposing release PR

### ISSUE THREAD

**Issue by stephaniewang526** [googleapis/release-please#656]
Below proposed release PR is missing pom file updates:
https://github.com/googleapis/java-bigquery/pull/972/files

**Comment by sofisl** [comment]
@bcoe, feel free to reassign as you see fit!

**Comment by chingor13** [comment]
This is likely caused the the GitHub search API not returning pom.xml files via the API. The search API is eventually consistent and can possibly by flaky or have race conditions with indexing.
