### ISSUE TITLE
Python releaser not finding version.py with path option

### ISSUE THREAD

**Issue by joeldodge79** [googleapis/release-please#664]
We have a python project under `sdk-codegen/python` in a [monorepo](https://github.com/looker-open-source/sdk-codegen) (e.g. `sdk-codegen/python/setup.py`, `sdk-codegen/python/looker_sdk/version.py`) When I specify `path: python` in the action config I see a log error something like: "cannot find `python/python/looker_sdk/version.py`". Consequently our `python/looker_sdk/version.py` file is not updated.

It seems like the combination of `this.gh.findFilesByFilename` + `this.addPath` when `this.path` is defined [here](https://github.com/googleapis/release-please/blob/9ba60ee3f8f3bfc9c0dee3180dce3b16386aa1b1/src/releasers/python.ts#L120) produces an extra path prefix

I can take a stab at fixing it but not sure what the best solution is:
1. s/`path: this.addPath(path)`/`path: path`/ in the [python releaser](https://github.com/googleapis/release-please/blob/9ba60ee3f8f3bfc9c0dee3180dce3b16386aa1b1/src/releasers/python.ts#L120)
2. try to build some logic detecting `this.path` already in `file` in [`addPath`](https://github.com/googleapis/release-please/blob/9ba60ee3f8f3bfc9c0dee3180dce3b16386aa1b1/src/release-pr.ts#L324) (seems error prone)
3. add a `prefix?: string` parameter to [`findFilesByFilename`](https://github.com/googleapis/release-please/blob/9ba60ee3f8f3bfc9c0dee3180dce3b16386aa1b1/src/github.ts#L1001) and return the results relative to that path prefix?

**Comment by joeldodge79** [comment]
whether or not #3 is a solution you might want to consider passing in `path:prefix` to the github code search

**Comment by crwilcox** [comment]
Seeing an issue as well on https://github.com/googleapis/python-crc32c/pull/44/files where it isn't finding our version in `setup.cfg`

**Comment by bcoe** [comment]
@crwilcox I don't think I'm understanding what happened to you in that PR you've linked, it doesn't appear to be related to path issues (also it looks like the subsequent update worked? https://github.com/googleapis/python-crc32c/pull/46).

The version # that is proposed in `synth.py` and the CHANGELOG is based on the branch names of prior releases, or prior tags that were published, if no appropriately named branch can be found.

If you're still having problems like you've linked to above, mind opening a separate issue?
