### ISSUE TITLE
Check multiple pages of merged PRs for release PR

### ISSUE THREAD

**Issue by bcoe** [googleapis/release-please#699]
With the current approach to finding release PRs, we grab a single page of merged release PRs and look through it for release PRs.

This just caused an issue for @codyoss, because our page size was 25, and there were more than 25 PRs that had been newer than the prior release.

In the context of creating a GitHub release, we should look for a few pages of release PRs.

**Comment by joeldodge79** [comment]
I read this and thought for a minute:

"wow, >25 PRs landed between merging the Release PR and the release-please-action receiving the `push` event and searching for merged Release PRs?"

Then I realized this is probably related to using the release-please cli, right? I add this comment mostly as a way to confirm my new-to-release-please{-action} understanding of the world.

**Comment by bcoe** [comment]
@joeldodge79 I think once merged PRs are the order of created, so the problem was a monorepo where one package hadn't been released in quite a while, but others had been.

**Comment by chingor13** [comment]
This was fixed in #720
