### ISSUE TITLE
Rebasing the main branch makes release-please get confused

### ISSUE THREAD

**Issue by safarmer** [googleapis/release-please#713]
I work on a small team that is moving quick and we sometimes make mistakes in our git history/commits. If we rebase or update the main branch and push to correct issues, the release-please PR that is generated contains all changes since the start of the project.

#### Steps to reproduce

  1. Make a mistake and push it to the main branch
  2. Check that the release-please PR has the correct list of changes
  3. Fix the mistake with rebasing etc
  4. Push the update to the main branch
  5. Check the release PR again

If the release PR commit hashes change, release-please cannot find a commit hash that matches. Since the release PRs are mostly immutable once they are merged, it is not possible to ignore a previous (potentially failed) release PR. One possible solution is to use the assumption that the github-release step is going to tag released PRs.

**Comment by chingor13** [comment]
We are discussing alternative ways to identify the last release tomorrow and labels is under consideration.

For your case, when you force-update your main branch, are your release tags invalidated as well?

**Comment by safarmer** [comment]
Releases and tags all seem fine. I have created an empty repo that I used to try and repro the issue. I finally got into a state where the latest release PR is including everything.

https://github.com/safarmer/release-please-issue/pull/6

The best I can find for instructions/steps is the git reflog:
```
ae85f76 HEAD@{0}: rebase (finish): returning to refs/heads/main
ae85f76 HEAD@{1}: rebase (pick): fix: add yet another more commits to the release
bd2feac HEAD@{2}: rebase (pick): chore: add yet another more commits to the release
7cdfadb HEAD@{3}: rebase (pick): chore: add yet another more commits to the release
8cca666 HEAD@{4}: rebase (pick): fix: add yet another more commits to the release
7b9a57d HEAD@{5}: rebase (pick): chore: add yet another more commits to the release
07d1908 HEAD@{6}: rebase (start): checkout HEAD~6
70b8472 HEAD@{7}: commit: fix: add yet another more commits to the release
9281ac5 HEAD@{8}: rebase (finish): returning to refs/heads/main
9281ac5 HEAD@{9}: rebase (pick): chore: add yet another more commits to the release
9b446d3 HEAD@{10}: rebase (pick): chore: add yet another more commits to the release
2e75ba6 HEAD@{11}: rebase (pick): fix: add yet another more commits to the release
83009d5 HEAD@{12}: rebase (start): checkout HEAD~4
8c39d05 HEAD@{13}: commit: fix: add yet another more commits to the release
f131482 HEAD@{14}: pull --rebase (finish): returning to refs/heads/main
f131482 HEAD@{15}: pull --rebase (pick): chore: add yet another more commits to the release
6f128a2 HEAD@{16}: pull --rebase (pick): chore: add yet another more commits to the release
83009d5 HEAD@{17}: pull --rebase (pick): chore: add yet another more commits to the release
c01e522 HEAD@{18}: pull --rebase (start): checkout c01e522f03ecfb8aa165910327c9144e86364098
942d397 HEAD@{19}: commit: chore: add yet another more commits to the release
530ccfc HEAD@{20}: commit: chore: add yet another more commits to the release
b61348a HEAD@{21}: commit: chore: add yet another more commits to the release
5575010 HEAD@{22}: pull --rebase (finish): returning to refs/heads/main
5575010 HEAD@{23}: pull --rebase (pick): fix!: breaking change
c6d06ed HEAD@{24}: pull --rebase (start): checkout c6d06edb183382ec4e713e4e9e372e3977a2136f
e24d9bc HEAD@{25}: commit (amend): fix!: breaking change
efbc5e2 HEAD@{26}: commit: fix\!: breaking change
53f2805 HEAD@{27}: commit: chore: add yet another more commits to the release
d245ae8 HEAD@{28}: commit: fix: add another more commits to the release
5cbe20a HEAD@{29}: commit: fix: add another commit
d869914 HEAD@{30}: pull: Fast-forward
ddb270a HEAD@{31}: commit: chore: configure release-please
f0c47b1 HEAD@{32}: pull: Fast-forward
437a815 HEAD@{33}: Branch: renamed refs/heads/master to refs/heads/main
437a815 HEAD@{35}: commit (initial): feat: create new repo
```

**Comment by bcoe** [comment]
@safarmer give this a shot `npm i release-please@9.5.0-candidate.0`, @chingor13 finished up a big refactor that makes how we find the prior release smarter (it should now filter directly to the appropriate branch name).

**Comment by bcoe** [comment]
@safarmer if this issue hasn't been addressed by our recent changes to how we approach querying for the last release, there's an alternate approach you can now use, _manifests_.

These allow you to specify a [`sha` for bootstrapping your release](https://github.com/googleapis/release-please/blob/master/docs/manifest-releaser.md#bootstrapping), which in an edge-case situation like this, could be updated to point at whatever `sha` in the history you want to start analyzing commits at.

If you are using manifests on a repository that releases a single module, you can use the special shorthand ".", I've been doing this to release security fixes for yargs, [here's an example](https://github.com/yargs/yargs/blob/16.x.x/release-please-config.json).

**Comment by safarmer** [comment]
Thanks @bcoe. It looks like the latest round of fixes has solved my problem. The only thing I have done since then was remove a tag from a release that failed (or was closed for what ever reason) and the next release went fine.

**Comment by bcoe** [comment]
@safarmer awesome 👌
