### ISSUE TITLE
release branch name collisions when releasing from multiple branches

### ISSUE THREAD

**Issue by chingor13** [googleapis/release-please#719]
It's possible when releasing from multiple feature branches that release-please tries to use the same version. In this case, release-please would stomp on the other feature branches' release versions.

We probably need to construct a release branch naming structure such that they can never collide across branches.

**Comment by bcoe** [comment]
Calling this a feature request, since it mainly crops up in the multiple release branch scenario, and we have work in motion to fix the problem.
