### ISSUE TITLE
Support Helm Chart Packages

### ISSUE THREAD

**Issue by abhinavkhanna-sf** [googleapis/release-please#747]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**

Helm Chart is not supported 

 **Describe the solution you'd like**
I want it automatically update Helm Chart version while creating a release
 **Describe alternatives you've considered**
 **Additional context**

**Comment by bcoe** [comment]
@abhinavkhanna-sf thank you for the suggestion, and better still the PR 👏 

Will work on getting this reviewed for you soon -- you might want to ensure you've rebased against the latest code, as we've been in the process of some minor refactors recently.

**Comment by abhinavkhanna-sf** [comment]
@bcoe Thank you for quick response. I forked couple of hours ago so it should be good. 
Unfortunately, I am unable to test it. Do you have any suggestions for testing the GitHub Action built around it?

**Comment by bcoe** [comment]
@abhinavkhanna-sf I would run it as a CLI while developing, to do so you can do:

```
npm run compile
node ./build/src/bin/release-please.js --help
```

It exposes a `release-pr` and `github-release` command, which correlate to the commands in the GitHub action.

You can then use a personal access token off GitHub to experiment on a test repo.

**Comment by abhinavkhanna-sf** [comment]
@bcoe Sounds good. I will try that. Thanks again.

**Comment by abhinavkhanna-sf** [comment]
@bcoe Looks like Github-release-please-action is still on v9. I cannot test my code with the Action.
It is first time writing mocha test cases only managed to add test case for Chart.yaml version change and it is passing. 

Let me know if there's a way to test it with Action or if you want me to work on something else for the PR.

**Comment by bcoe** [comment]
@abhinavkhanna-sf the action is a tiny bit behind, because we've been working on a pretty major refactor of the release process (and testing a bit internally before we release it wider).

> Let me know if there's a way to test it with Action or if you want me to work on something else for the PR.

I left some comments on the PR. I'm comfortable shipping as soon as we have even a simple test for the releaser 😄

**Comment by bcoe** [comment]
@abhinavkhanna-sf opening this up until we can test, and add the tests for the releaser.

I've published a testing branch of the action you can reference by `sha` here, to experiment:

https://github.com/google-github-actions/release-please-action/pull/216

**Comment by mehdicopter** [comment]
Hello,
I did try with the App and when specifying release type to `helm` it does not trigger the PR

Could you help me ?
