### ISSUE TITLE
Formatting of setup.py is changed by release-please

### ISSUE THREAD

**Issue by targos** [googleapis/release-please#777]
#### Environment details

  - OS: Ubuntu
  - `release-please` version: The one used by the latest `release-please-action@v2`

#### Steps to reproduce

  1. Use `release-please` in a Python project where `setup.py` is formatted using psf/black
  2. Observe that the release pull request changes the formatting (adds spaces around the `=` operator)
  3. Because of that, we always have to correct the commit before merging to remove the spaces.

See https://github.com/nodejs/gyp-next/commit/5b3fa5c3c756e37fade6487b78573341b9655e73

```diff
diff --git a/setup.py b/setup.py
index 31f0117..ec313b0 100644
--- a/setup.py
+++ b/setup.py
@@ -15,7 +15,7 @@
 
 setup(
     name="gyp-next",
-    version="0.8.0",
+    version = "0.8.1",
     description="A fork of the GYP build system for use in the Node.js projects",
     long_description=long_description,
     long_description_content_type="text/markdown",
```

**Comment by bcoe** [comment]
@targos agreed that this is annoying, will work on patching soon 👍

**Comment by targos** [comment]
I created a PR: https://github.com/googleapis/release-please/pull/782
