### ISSUE TITLE
Document release complete process

### ISSUE THREAD

**Issue by nzakas** [googleapis/release-please#778]
**Is your feature request related to a problem? Please describe.**
As a new user, it’s unclear how to actually create a release. For instance:

1. when merging a release PR, what merge strategy should be used? My projects generally use squashed merges, but that clearly won’t work correctly with a release PR. What is the expected merge strategy?
2. Make it clear that we have to manually tag releases ourselves. This surprised me and isn’t very clear from the README.
3. How do I go from a release PR to a GitHub release? Am I expected to manually create one?
4. Is it expected that releases are always cut from the main branch?

 **Describe the solution you'd like**

Update the README to describe how to do a release.

**Comment by bcoe** [comment]
> when merging a release PR, what merge strategy should be used? My projects generally use squashed merges, but that clearly won’t work correctly with a release PR. What is the expected merge strategy?

I aways use squash for merging, bot the release PR and the standard release PRs. Both squash or merge commits should work.

> Make it clear that we have to manually tag releases ourselves. This surprised me and isn’t very clear from the README.

You should not need to manually tag releases yourself. Could you share your configuration?

> How do I go from a release PR to a GitHub release? Am I expected to manually create one?

A GitHub release is automatically created when you merge a release PR.

> Is it expected that releases are always cut from the main branch?

For JavaScript, today, it is expected that you will always release from `main`. There is work progress to support LTS and other release lines.

**Comment by bcoe** [comment]
@nzakas one thing that jumps out at me looking at the repository you shared the other day, was that it was on `v1.3.0` (which we still had documented in the README). The action is up to `v2.19.0` and there have been various improvements around branch handling:

https://github.com/google-github-actions/release-please-action

**Comment by nzakas** [comment]
Ah ok! I guess I was confused between this repo and that one. Just FYI, the README in this repo still [shows v1.3.0](https://github.com/googleapis/release-please#github-action-recommended), and that's where I copied it from. I'll try upgrading and see how it goes. I don't have any special configuration, I just copied this workflow file and went from there.

**Comment by bcoe** [comment]
@nzakas I'm happy to help debug on whatever repository you're installing on. I feel like `v1.3.0` should have worked still, which makes me think there might be some other configuration issue biting you.

Here's the config [for yargs](https://github.com/yargs/yargs/blob/master/.github/workflows/release-please.yml) it's pretty standard for a JavaScript repo.

**Comment by nzakas** [comment]
Thanks, I'll check that out. Here was the file I was using: https://github.com/humanwhocodes/memory/blob/1d13d684a4cc4be77c0c975c47541cdefdba9c98/.github/workflows/release-please.yml

When I merged the PR, it didn't create a tag and didn't generate a release, which prompted me opening this issue.

**Comment by bcoe** [comment]
@nzakas I think what likely bit you was that it assumes releases are happening against the primary branch. @chingor13 has been doing work to make this more flexible, but it hasn't rolled out to all release types yet.

The medium term goal is that you could have a few release lines for a library.

**Comment by nzakas** [comment]
@bcoe I'm not sure I understand. `main` is the primary branch in my repo, and that is reflected in both GitHub settings and the workflow file. Is there some other way to designate the primary branch that I'm unaware of? Or maybe you're assuming the primary branch is always `master`?

**Comment by nzakas** [comment]
Update: Upgrading to v2 seemed to solve all of the problems! :tada: The tag was created, the release was created, and the package was published to npm.

**Comment by nzakas** [comment]
It appears that a release PR is not generated with the first commit after a release is something like `refactor:`. Even though you can argue that a refactor isn't release-worthy, I actually wanted to do a release with some refactors for better stability. Is this configurable in some way, or maybe it's a bug?

**Comment by bcoe** [comment]
@nzakas you can configure this  with the `changelog-types` input in the action, which is the serialized JSON of this array:

```js
[
  {type: 'feat', section: 'Features'},
  {type: 'fix', section: 'Bug Fixes'},
  {type: 'perf', section: 'Performance Improvements'},
  {type: 'deps', section: 'Dependencies'},
  {type: 'revert', section: 'Reverts'},
  {type: 'docs', section: 'Documentation'},
  {type: 'style', section: 'Styles', hidden: true},
  {type: 'chore', section: 'Miscellaneous Chores', hidden: true},
  {type: 'refactor', section: 'Code Refactoring', hidden: true},
  {type: 'test', section: 'Tests', hidden: true},
  {type: 'build', section: 'Build System', hidden: true},
  {type: 'ci', section: 'Continuous Integration', hidden: true},
]
```

**Comment by nzakas** [comment]
Another question I don’t see documented anywhere, what does the “autorelease:pending” label do? Is there an autorelease feature where the PR is automatically merged at some point?

**Comment by bcoe** [comment]
@nzakas I carried these labels over from my team's existing automations, it goes from:

`autorelease:pending` -> `autorelease:tagged` -> `autorelease:published`.

And is updated by different steps in our process. By keeping these labels consistent, we were able to split out release PRs, from the creation of actual releases on GitHub.

**Comment by nzakas** [comment]
Ah gotcha! So it’s the state of the PR. Thanks.
