### ISSUE TITLE
Add option for fixing semver of the release on multi-module projects

### ISSUE THREAD

**Issue by chingor13** [googleapis/release-please#802]
For multimodule releases, using `Release-As: x.y.z` may not suffice - it's not necessarily clear which module versions this should override. 

The use case is for trying to fix a release version. Consider the case where we accidentally merge a breaking change commit message, but it wasn't actually a breaking change. It would be nice to be able to go back and somehow fix the commit message.

Potential options:
* if a semver label is applied to the PR, assume that semver bump type over the commit message
* add a `Release-Semver: [major|minor|patch]` git trailer that will override the semver bump we use on all modules in the proposed pull request

**Comment by stephaniewang526** [comment]
An example in java-bigquerystorage where a [breaking change](https://github.com/googleapis/java-bigquerystorage/pull/924) in v1beta2 resulted in a [major version bump](https://github.com/googleapis/java-bigquerystorage/pull/927/commits/1e83db67800ebc30e9892eaeccd92752bba6fe87) in the release PR proposed by release-please. It should've been a [minor bump](https://github.com/googleapis/java-bigquerystorage/pull/927). Manual changes were required to fix all the pom files, versions.txt, and PR subject line.

**Comment by kolea2** [comment]
Adding example for java-bigtable-hbase: https://github.com/googleapis/java-bigtable-hbase/pull/2825. We would have liked all version numbers to be bumped in this case

**Comment by chingor13** [comment]
#1161 allows you to override the commit message of the merged pull request. This should work to "undo" the breaking change.
