### ISSUE TITLE
Multiple changes in single commit doesn't always work

### ISSUE THREAD

**Issue by rsenden** [googleapis/release-please#821]
While working with [release-please-action](https://github.com/google-github-actions/release-please-action), I've noticed a couple times that features or fixes that are listed in the body/footer of a commit message don't get included in the changelog.

I don't recall all the circumstances where this happened, but at least this seems to occur if there are lines in the commit message footer that do not adhere to the Conventional Commits layout.

As an example, following is the commit message for https://github.com/rsenden/release-please-test/commit/868873d0b39b4545341f09ee76cb70f9cd2d4bd1

```
feat: Feature with extra messages

feat: FeatExtraFooter1

feat: FeatExtraFoorer2

Some other text

Something else
```

As can be seen at https://github.com/rsenden/release-please-test/runs/2084824783?check_suite_focus=true#step:3:14, release-please only recognizes 1 feature instead of the 3 features listed in this commit message. This can also be seen in the generated pull request, where the changelog doesn't list the `FeatExtraFooter1` and `FeatExtraFooter2` features: https://github.com/rsenden/release-please-test/pull/4

**Comment by live627** [comment]
seems to work for me?

https://github.com/live627/SCEditor/commit/d6fcbbce28dd03ac154d4a9b7c26aad80e8ee7bb

https://github.com/live627/SCEditor/pull/37

so maybe it only works for node...

**Comment by bcoe** [comment]
@live627 @rsenden the it has to do with the parser. We parse footers from the bottom up, so when the text is broken up like:

````
footer: a
footer: b

free form text that doesn't look like a footer.
```

The multiple footers are not parsed.

**Comment by rsenden** [comment]
> it has to do with the parser. We parse footers from the bottom up

Good to know, any plans to get this fixed? Maybe in the meantime it would be good to add a note to the documentation.

**Comment by bcoe** [comment]
@rsenden this was an intentional decision when we wrote [the parser](https://github.com/conventional-commits/parser), due to it being ambiguous as to which parse goal we'd like.

No immediate plan to fix, so updating docs might be a good compromise.

**Comment by tswast** [comment]
I'd like to +1 the need for docs improvements. Looking at the "What if my PR contains multiple fixes or features?" section in the README, I see all the example extra commits include "PiperOrigin-RevId: 345559154". It's not clear to me if this is required or not, and is confusing if working on a repo that isn't mirrored from google3/piper.

**Comment by live627** [comment]
it's not strictly required
