### ISSUE TITLE
List Breaking Changes first

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/release-please#86]
'Allo! I was just looking at [this generated release](https://github.com/googleapis/nodejs-pubsub/pull/609), and I was thinking it would be nice if the `BREAKING CHANGES` came first on the list for maximum visibility. Actually, maybe even jazzing it up wouldn't be going too far:

## ⚠️ Breaking Changes!

**Comment by bcoe** [comment]
I like this idea @stephenplusplus :+1:, here's where it's implemented:

https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-conventionalcommits

So we'll need to make the change upstream.

**Comment by bcoe** [comment]
I have confirmed that the new template format lists breaking changes first, see:

https://github.com/bcoe/c8/pull/105
