### ISSUE TITLE
support alternative ways of changing proposed release version

### ISSUE THREAD

**Issue by codyoss** [googleapis/release-please#876]
**Is your feature request related to a problem? Please describe.**

Currently the only way to change the release version is to create a dummy commit that is then processed by release please. It would be nice if there was a way to do this without having to create a commit at all, keeping the trunk cleaner.

 **Describe the solution you'd like**

One option for doing this would be for release please PRs to honor some commands. Example a person could type the following command as a comment on the release PR: `/releaseAs v1.18.0`

**Comment by chingor13** [comment]
I think the feature that overrides the commit message in conjunction with a `Release-As: x.y.z` should suffice. An additional comment format will increase the burden on integrations (listening to more events) and would need a design for monorepos (you would have to build a grammar for assigning a version to a specific component).
