### ISSUE TITLE
support a general Go releaser

### ISSUE THREAD

**Issue by codyoss** [googleapis/release-please#882]
**Is your feature request related to a problem? Please describe.**

The current Go release is specific to our client libraries. A general implementation would be nice for the community and other Go repositories found in our org.

 **Describe the solution you'd like**

A new releaser type: `go`

**Additional context**

Was recently talking with someone on getting release-please on a new cloud events repo written in Go: https://github.com/googleapis/google-cloudevents-go

**Comment by chingor13** [comment]
Can you describe which files need to be updated?

**Comment by codyoss** [comment]
There are no required files to be updated for a simple project (no pom.xml equivalent that states a version) so I guess just a changelog. I believe the base case for a single module (unit of packaged code) codebase is relatively basic. If we wanted the releaser to support mutil-module projects generically, such as we have with our [google-cloud-go](https://github.com/googleapis/google-cloud-go), that is where the tricky bits would lie.

I suspect supporting the base case would be good enough for now. Mutil-module projects are quite rare in the ecosystem.

**Comment by chingor13** [comment]
The base `ReleasePR` class (or an empty `Go` class that extends `ReleasePR` to provide a future place for customization) would do this. We would just need to adjust the factories to be able to build that type.
