### ISSUE TITLE
feature: support updating npm-shrinkwrap.json

### ISSUE THREAD

**Issue by erezrokah** [googleapis/release-please#886]
**Is your feature request related to a problem? Please describe.**

Release please PR doesn't update `npm-shrinkwrap.json`. It does update `package-lock.json`

 **Describe the solution you'd like**

Release please should detect the `npm-shrinkwrap.json` file and update its version

 **Describe alternatives you've considered**

Modifying the release PR manually.

**Comment by bcoe** [comment]
@erezrokah this should now be released in the latest version of `release-please-action`.

**Comment by erezrokah** [comment]
Thank you for the quick turnaround @bcoe! This is amazing 🎉
