### ISSUE TITLE
feature(monorepos): allow excluding file paths when create release PRs

### ISSUE THREAD

**Issue by erezrokah** [googleapis/release-please#908]
**Is your feature request related to a problem? Please describe.**

More likely to happen in monorepos. We recently added a feature to a package in a monorepo that also updated tests snapshots in another package https://github.com/netlify/build/pull/2785

That resulted in creating a release for both packages, where the desired result is to create a release only for the first one.

 **Describe the solution you'd like**
Ability to exclude specific paths from the release diffing logic, for example `exclude: ["packages/build/tests"]`

 **Describe alternatives you've considered**
We could separate https://github.com/netlify/build/pull/2785 into two PRs, one for each package but that means tests for both PRs will fail until we merge both.

 **Additional context**
We might be able to use GitHub commit diff API to get a list of changed paths, and return an empty commit array if all changed paths are excluded.
I think the place to implement it will be around https://github.com/googleapis/release-please/blob/d1e5714dd6f5082da1e5eb59662cd15846f40dc7/src/release-pr.ts#L330

**Comment by lukekarrys** [comment]
We would be interested in this as well for https://github.com/npm/cli. Our use case is slightly different but I think it could also be accomplished with a config like `exclude`. 

We currently use release-please to release everything inside `workspaces/` using the `path` config. But the root of the monorepo is `npm` itself, which we would like to convert to using release-please in the future. But I believe we would run into an issue where we would like any commits that touch files *only* in `workspaces/*` to be excluded from consideration when generating an `npm` release.

Are there any design decisions to be made around this feature? I'd be open to contributing it but would like to make sure it handles other's use cases as well.
