### ISSUE TITLE
Adding 'go' as the release type makes changes to 'CHANGES.md' instead of CHANGELOG.md

### ISSUE THREAD

**Issue by atreya2011** [googleapis/release-please#924]
https://github.com/googleapis/release-please/pull/890

I noticed a recent pull request adds a generic go release type and the documentation is not up to date to reflect the same.

**Comment by atreya2011** [comment]
It also seems like the go release-type creates CHANGES.md instead of updating an existing CHANGELOG.md
Is there any way to override this behaviour?

**Comment by bcoe** [comment]
@codyoss is it common for go to use CHANGES.md rather than CHANGELOG.md? or was this design decision specific to how we were doing things on our team?

**Comment by codyoss** [comment]
@bcoe CHANGES was a pre-existing pattern that our team Go libraries had used. I think in general CHANGELOG is more prevalent, but even then I don't actually see most projects use them as they seem to just favor using Github releases.

**Comment by bcoe** [comment]
@codyoss I think we use `go-yoshi` everywhere for our internal stuff now? wondering if we could make the `go` releaser use `CHANGELOG`, and address @atreya2011's hiccup.

**Comment by codyoss** [comment]
@codyoss Yup, we are fully migrated. That sounds good to me!

**Comment by abeMedia** [comment]
Any update on this? Would be great if the `changelogPath` option actually worked but even just changing the go releaser to `CHANGELOG.md` would already be good!

**Comment by bcoe** [comment]
@abeMedia @atreya2011 this should be working now 👍 sorry it took a little while to get to.

**Comment by abeMedia** [comment]
Awesome, thanks!

**Comment by atreya2011** [comment]
Thank you 🙏🏼
