### ISSUE TITLE
Support cherrypicking commits for release.

### ISSUE THREAD

**Issue by sasha-gitg** [googleapis/release-please#935]
**Is your feature request related to a problem? Please describe.**
Generally, bug fixes and new features are interleaved into the main branch. We would like to only select bug fixes for releases so we can release as a patch instead of minor version rev.
 **Describe the solution you'd like**
Select commits to include in release.
 **Describe alternatives you've considered**
- Manually releasing as a patch but this has the downside of including the new features.
- Force changing the commit history to temporarily remove the features and only include bug fixes, then release, and then add features back to commit history.

**Comment by bcoe** [comment]
@sasha-gitg with the GitHub action, I've been experimenting with using the manifest-based releaser to configure multiple release branches for back-porting changes, here's an example:

https://github.com/yargs/yargs-parser/tree/15.x.x

I would like to make the configuration more straightforward for every release strategy, @chingor13 is planning some refactoring work this quarter that I think could help make the library more malleable, and therefore easier to make the changes I have in mind...

_Having said this, you should be able to get the behavior you want to today with some fiddling._

**Comment by codyoss** [comment]
I think my FR is related here: #879

**Comment by chingor13** [comment]
This seems more like branch management process is needed rather than a release-please feature. Perhaps you want something like a `next` or `feature` branch to keep `main` open for bugfixes.

Cherry-picking can be non-trivial - what happens when there are conflicts?

**Comment by chingor13** [comment]
We're building a cherry-pick-bot: https://github.com/googleapis/repo-automation-bots/pull/3057 which should make it easier for maintainers to quickly cherry-pick changes between branches via the GitHub UI.

Closing this issue as we won't be adding any features to release-please around cherry-picking (it already supports multiple release branches and is agnostic to how the change got to that branch).
