### ISSUE TITLE
Support/Document terraform monorepos

### ISSUE THREAD

**Issue by pragmaticivan** [googleapis/release-please#951]
**Is your feature request related to a problem? Please describe.**
I would like to have one repo (monorepo) for multiple reusable terraform repos.
Each repo should have its own semver and release lifecycle

 **Describe the solution you'd like**
It's not clear to me how that would work with terraform but I see a lot of projects creating a single repo because it's not trivial to individually release different versions like you would do in nodejs with lerna.

**Comment by bcoe** [comment]
@pragmaticivan today, I believe you could pull this off with the [Manifest](https://github.com/googleapis/release-please/blob/master/docs/manifest-releaser.md) releaser, but we need to do some work to clean up the code-base, and make every releaser work as expected with manifests (_I'm not sure if the terraform releaser works with it).

**Comment by chingor13** [comment]
In v13 (coming soon), all release strategies should work with manifest (mono-repo) repositories. If they are truly independent, the it should work out of the box keeping release tags separate via a prefix (component name). If they are interlinked, we would need to implement a manifest plugin that post-processes the release PRs.
