### ISSUE TITLE
Add manifest support Rust releaser

### ISSUE THREAD

**Issue by fasterthanlime** [googleapis/release-please#953]
**Is your feature request related to a problem? Please describe.**

I've noticed release-please got this new manifest releaser and it sounds _exactly_ like what we need.

The docs say only the `node` and `python` releasers are supported (off the top of my head).

I'd like to use the `rust` releaser but.. _I contributed the rust releaser_ about six months ago.

So the problem is I now want to add support for `manifest-pr` / `manifest-release` to the Rust releaser.

 **Describe the solution you'd like**

I'd like to open a PR to support that in the near future and eventually get it merged.

 **Describe alternatives you've considered**

Merging individual PRs as usual. I don't like that.

 **Additional context**

I've already started work, this can serve as a tracking issue and I'll open the PR when I get it working.

**Comment by fasterthanlime** [comment]
The implementation is coming along nicely, but I've run into a snag: multiple `Update`s are overwriting each other, I may have to teach `GitHub.getChangeSet` to handle multiple updates touching the same file (by looking up the content in the changeset first).

**Comment by bcoe** [comment]
@fasterthanlime thanks for doing this work 👏 looks like @joeldodge79 is already providing review.
