### ISSUE TITLE
Allow better control over the release notes/CHANGELOG

### ISSUE THREAD

**Issue by chingor13** [googleapis/release-please#967]
Sometimes repository maintainers need to tweak the published release notes and changelog entries for either correctness or readability. Currently, the release notes are rewritten every time release-please runs.

**Comment by plamut** [comment]
I was just about to report this.

In addition, in our concrete case the bot included a release note about a PR that was subsequently reverted. Here's the release PR:
https://github.com/googleapis/python-bigquery/pull/756

The problematic item is the first one in the Features section, i.e. "add always_use_jwt_acces". That PR was subsequently [reverted](https://github.com/googleapis/python-bigquery/pull/722), but the bot did not detect that. Should have been the reversal PR prefixed with `revert:` instead?

**Comment by chingor13** [comment]
Proposal: Add a parsable section to the merged pull request that overrides the commit message for that commit.

Example:
```
BEGIN_COMMIT_OVERRIDE
fix: rewritten commit message
docs: another commit message
END_COMMIT_OVERRIDE
```

This does not grant full control over the release notes, but should be good enough for most cases.
