### ISSUE TITLE
Java file version bump not working on non default branches

### ISSUE THREAD

**Issue by kolea2** [googleapis/release-please#968]
We have am embedded java file that release please increments the version on for each release. It seems to work fine on the default branch:
https://github.com/googleapis/java-bigtable/pull/893/files#diff-872c3c6b3fd52460b8f485ffa56921b841e02c4a563598aad8ad1be186292625R23

But not on a branch release:
https://github.com/googleapis/java-bigtable/pull/831 (I had to push the version number myself)

**Comment by kolea2** [comment]
CC @igorbernstein2

**Comment by chingor13** [comment]
`extraFiles` option is a per-branch configuration - in your [`.github/release-please.yml`](https://github.com/googleapis/java-bigtable/blob/master/.github/release-please.yml), `extraFiles` are configured at the root (for the default branch), but not on the 1.22.0-sp branch
