### ISSUE TITLE
close stale patch PRs

### ISSUE THREAD

**Issue by codyoss** [googleapis/release-please#981]
## **Is your feature request related to a problem? Please describe.**

release-please does not close stale release PRs. Occasionally a fix will land before a feat which will create vX.X.1 release PR. Then if a PR lands a feat after a vX.X+1.0 release-please PR is created. The old PR stays open. 

 ## **Describe the solution you'd like**

I would like release please to close patch PRs if a minor PR is later opened. Or at least have a setting to due as much.

 ## **Describe alternatives you've considered**

Manually close the PRs. This can be tedious in mono-repos where you are releasing many projects from one github repo.

## Example

I had to manually close https://github.com/googleapis/google-cloud-go/pull/4446 after https://github.com/googleapis/google-cloud-go/pull/4467 was opened.

**Comment by chingor13** [comment]
As far a I know, it's supposed to do this automatically.

**Comment by codyoss** [comment]
Another example was https://github.com/googleapis/google-cloud-go/pull/4521 was not closed after https://github.com/googleapis/google-cloud-go/pull/4557 was opened.

**Comment by codyoss** [comment]
Another example: https://github.com/googleapis/google-cloud-go/pull/4800 https://github.com/googleapis/google-cloud-go/pull/4809

**Comment by bcoe** [comment]
This might be an issue with how mono repos behave vs., non-mono-repos (just a guess).

**Comment by chingor13** [comment]
This should no longer be an issue in v13 as we no longer put the version into branch name.

**Comment by sofisl** [comment]
This issue is going OOSLO soon.

**Comment by chingor13** [comment]
Closing as it'll be fixed moving forward in v13 (it won't close out older PRs, but it will re-use the branches/PRs moving forward).
