### ISSUE TITLE
release-please bot is attempting the release of same version after every new merge

### ISSUE THREAD

**Issue by vi3k6i5** [googleapis/release-please#988]
After every PR merge on github repo release-please bot is trying to do a release of an already released version.

Example:
Successful release of 2.2.1b2 : https://github.com/googleapis/python-spanner-django/pull/687

still reattempted by bot:

https://github.com/googleapis/python-spanner-django/pull/689
https://github.com/googleapis/python-spanner-django/pull/690
Any idea what is causing this and how to resolve it ?

There is a whole list with 2.2.1b1 https://github.com/googleapis/python-spanner-django/pulls?q=is%3Apr+is%3Aclosed

1) Is this a client library issue or a product issue?
 - Not sure, maybe just a client level issue in configuration or maybe a version name mismatch from the django client.

2) Did someone already solve this?
  - NA

3) Do you have a support contract?
  - NA

#### Environment details

  - OS: NA
  - Node.js version: NA
  - npm version: NA
  - `release-please` version: latest in production

#### Steps to reproduce

  1. Merge a commit to repo https://github.com/googleapis/python-spanner-django master branch.
  2. Release please bot will create a new release PR similar to this: chore: release 2.2.1b2 #690

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by bcoe** [comment]
We don't currently support pre-releases with the format `1.0.0b1`, `1.0.0b2`, etc. The syntax Node.js and Java use for this is to have the prerelease version after a hyphen:

```
1.0.0-beta.1
1.0.0-beta.2
etc.
```

Is `1.0.0b1` common syntax for Python?

**Comment by bcoe** [comment]
@chingor13 @joeldodge79 another need for a [custom version bumping strategy](https://github.com/googleapis/release-please/pull/903)?

**Comment by chingor13** [comment]
> @chingor13 @joeldodge79 another need for a [custom version bumping strategy](https://github.com/googleapis/release-please/pull/903)?

Probably. This is related to @parthea's feature request and requires thought about signal the version bump. How do we signal whether the next version should be 1.0.0b2, 1.1.0b1, 1.0.0 or 1.1.0?

**Comment by tseaver** [comment]
@bcoe [PEP 440](https://www.python.org/dev/peps/pep-0440/#id27) describes `X.YbZ` as the "normal" form, and [accepts some others](https://www.python.org/dev/peps/pep-0440/#id34) such as `X.Y-beta.Z` which are expected to be normalized back to it by tooling.

@chingor13 I would expect that `release-please` would stay with `-b#` unless / until a PR with `Release-As:` bumped it (i.e., no automation).

**Comment by bcoe** [comment]
@vi3k6i5 I believe this should be corrected now, I believe before the fix this PR would have contained all changes since last non alpha or beta release:

https://github.com/googleapis/python-spanner-django/pull/698

**Comment by bcoe** [comment]
release-please had to be rolled back due to an unrelated issue, I will close this issue once we re-land.

**Comment by bcoe** [comment]
fix has been redeployed.

**Comment by alexanderankin** [comment]
how is this supposed to be used? i can set a python version strategy somehow? sorry to revive a dead thread... we've been talked into using release-please over at testcontainers/testcontainers-python and I've been using `npx -y release-please` but i've been doing `--release-as 4.15.0-rc1` but it has been published to pypi as `4.15.0rc1` (which is correct) because python follows [pep 440](https://peps.python.org/pep-0440/) instead of semver (so the version we store in our pyproject.toml is actually illegal. perhaps everything is working as it should? should i read anything specific to improve my understanding?
